import React from 'react';
import { CheckCircle2, ExternalLink, Loader2, MapPin, Users, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Button } from '../ui/button';

export const GeoDetailPanel = ({ feature, onClose, selectedPerson, canConfirm = false, confirming = false, onConfirmLocation }) => {
  if (!feature) return null;
  const item = feature.properties || {};
  const labels = { household: `Hogar · ${item.resident_count || 0} personas`, person: item.person_number || 'Persona 360', cell: 'Célula', front_group: 'Grupo Frontal · Centroide', church: 'Ancla institucional' };
  const href = item.entity_kind === 'cell' ? `/celulas/${item.entity_id}` : item.entity_kind === 'front_group' ? '/grupos-frontales' : item.entity_kind === 'person' ? `/personas/${item.entity_id}` : null;
  const selectedResident = selectedPerson && (item.entity_kind === 'person' ? item.entity_id === selectedPerson.person_id : (item.residents || []).some((resident) => resident.person_id === selectedPerson.person_id));
  const confirmed = selectedPerson && (item.entity_kind === 'person' ? item.verification_status === 'manual_verified' : (item.verified_person_ids || []).includes(selectedPerson.person_id));
  return <aside className="absolute bottom-4 left-4 right-4 z-10 max-h-[70%] overflow-y-auto border bg-white p-4 shadow-2xl md:left-auto md:right-4 md:top-4 md:w-80" data-testid="geo-feature-detail-panel">
    <div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-amber-700">{labels[item.entity_kind] || 'Mapa 360'}</p><h3 className="font-['Spectral'] text-xl font-semibold" data-testid="geo-feature-name">{item.name || `${item.count || 0} ubicaciones`}</h3></div><Button variant="ghost" size="icon" onClick={onClose} aria-label="Cerrar detalle" data-testid="close-geo-feature-detail"><X className="h-4 w-4" /></Button></div>
    <div className="mt-4 space-y-2 text-sm"><p className="flex items-start gap-2"><MapPin className="mt-0.5 h-4 w-4 shrink-0 text-amber-700" /><span>{item.address || `Zona ${item.zone_number || item.zone || '—'} · ${item.subzone || 'sin subzona'}`}</span></p>{item.sector_name && <p><b>Sector:</b> {item.sector_name}</p>}{item.entity_kind === 'cell' && <><p><b>Líder:</b> {item.leader || 'Pendiente'}</p><p><b>Reunión:</b> {item.meeting_day || '—'} {item.meeting_time || ''}</p><p className="flex items-center gap-2"><Users className="h-4 w-4" />{item.members || 0} / {item.capacity || '—'} personas</p></>}{item.entity_kind === 'front_group' && <><p className="flex items-center gap-2"><Users className="h-4 w-4" />{item.members || 0} personas vinculadas</p><p className="text-xs text-slate-500">Posición aproximada calculada desde sus miembros; no representa lugar de reunión.</p></>}{item.entity_kind === 'person' && <><p><b>Categorías:</b> {(Array.isArray(item.categories) ? item.categories : []).join(', ') || 'Sin categoría'}</p><p><b>Etapa:</b> {item.stage || 'Sin proceso activo'}</p>{item.phone && <p><b>Teléfono:</b> {item.phone}</p>}</>}{item.entity_kind === 'household' && <div className="mt-3 space-y-2" data-testid="geo-household-residents">{(item.residents || []).map((resident) => <Link key={resident.person_id} to={resident.profile_path} className="flex items-center justify-between border-l-2 border-amber-500 bg-amber-50 px-3 py-2 hover:bg-amber-100" data-testid={`open-geo-household-resident-${resident.person_id}`}><span><b className="block">{resident.name}</b><small className="text-slate-500">{resident.household_role || resident.person_number || 'Persona 360'}</small></span><ExternalLink className="h-4 w-4" /></Link>)}</div>}</div>
    {selectedResident && <div className="mt-4 border border-emerald-200 bg-emerald-50 p-3" data-testid="geo-selected-person-location"><p className="text-xs font-semibold uppercase text-emerald-800">Persona seleccionada</p><p className="mt-1 text-sm font-bold text-slate-950" data-testid="geo-selected-person-name">{selectedPerson.name}</p>{confirmed ? <p className="mt-2 flex items-center gap-2 text-sm font-semibold text-emerald-800" data-testid="geo-location-confirmed-badge"><CheckCircle2 className="h-4 w-4" />Ubicación confirmada</p> : canConfirm ? <Button type="button" className="mt-3 w-full bg-emerald-700 text-white hover:bg-emerald-800 hover:text-white" onClick={onConfirmLocation} disabled={confirming} data-testid="confirm-selected-person-location-button">{confirming ? <Loader2 className="h-4 w-4 animate-spin" /> : <CheckCircle2 className="h-4 w-4" />}Confirmar que aquí vive</Button> : <p className="mt-2 text-xs text-slate-600">Solo un administrador de ubicaciones puede confirmar esta vivienda.</p>}</div>}
    {href && <Button asChild className="mt-4 w-full" data-testid="open-geo-feature-record"><Link to={href}><ExternalLink className="h-4 w-4" />Abrir ficha</Link></Button>}
  </aside>;
};