import React from 'react';
import { CircleAlert, Edit3, Filter, Flame, Home, Layers3, Map, MapPin, MapPinOff, Plus, Presentation, RefreshCw, Satellite, Users } from 'lucide-react';
import { Button } from '../ui/button';
import { Popover, PopoverContent, PopoverTrigger } from '../ui/popover';
import { Tabs, TabsList, TabsTrigger } from '../ui/tabs';
import { GeoFilters } from './GeoFilters';
import { GeoPersonSearch } from './GeoPersonSearch';

const countFilters = (filters) => Object.values(filters).filter(Boolean).length;
const targetStatuses = [['', 'Todos los estados'], ['detected', 'Detectadas'], ['assigned', 'Asignadas'], ['visited', 'Visitadas'], ['follow_up', 'Seguimiento'], ['connected', 'Conectadas'], ['do_not_visit', 'No visitar']];

export const GeoMapToolbar = ({
  kind, setKind, mode, setMode, filters, setFilters, catalog, summary, canViewPrecise, canManage, canUseTerritorial,
  providerConfigured, compare, setCompare, basemap, setBasemap, satelliteAvailable = false, backfilling, onBackfill, onReview, onPersonSelect, onEditSectors,
  onPresent, onUnlocated, evangelismStatus, setEvangelismStatus, evangelismTotal, onAddEvangelism,
}) => {
  const evangelism = kind === 'evangelism';
  return <header className="relative z-40 shrink-0 overflow-visible border-b bg-white px-2 py-2 shadow-sm" data-testid="geo-map-toolbar"><div className="flex flex-wrap items-center gap-2">
    <div className="flex shrink-0 items-center gap-2 pr-1"><div className="flex h-9 w-9 items-center justify-center bg-slate-950 text-white"><MapPin className="h-5 w-5" /></div><div className="hidden xl:block"><h1 className="font-['Spectral'] text-xl font-semibold leading-none">Mapa 360</h1><p className="mt-1 text-[10px] uppercase text-amber-700">Territorio y evangelismo</p></div></div>
    <Tabs value={kind} onValueChange={setKind}><TabsList className="h-9 bg-slate-100" data-testid="geo-map-tabs">{canUseTerritorial && <><TabsTrigger value="people" className="h-8 px-3" data-testid="geo-people-tab"><Users className="mr-1.5 h-3.5 w-3.5" />Personas</TabsTrigger><TabsTrigger value="cells" className="h-8 px-3" data-testid="geo-cells-tab"><Layers3 className="mr-1.5 h-3.5 w-3.5" />Células</TabsTrigger></>}<TabsTrigger value="evangelism" className="h-8 px-3" data-testid="tab-map-casas-visitar"><Home className="mr-1.5 h-3.5 w-3.5" /><span className="hidden sm:inline">Casas por visitar</span><span className="sm:hidden">Casas</span></TabsTrigger></TabsList></Tabs>
    {!evangelism && <GeoPersonSearch disabled={!canViewPrecise} onSelect={onPersonSelect} />}
    <div className="flex h-9 shrink-0 items-center border border-slate-300 bg-slate-50 p-0.5" data-testid="geo-basemap-control" aria-label="Tipo de mapa"><Button type="button" size="sm" variant="ghost" className={`h-7 rounded-none px-2 text-xs ${basemap === 'clear' ? 'bg-white text-slate-950 shadow-sm hover:bg-white hover:text-slate-950' : 'text-slate-500 hover:bg-white hover:text-slate-950'}`} onClick={() => setBasemap('clear')} data-testid="geo-basemap-clear"><Map className="h-3.5 w-3.5" /><span className="hidden lg:inline">Mapa</span></Button><Button type="button" size="sm" variant="ghost" className={`h-7 rounded-none px-2 text-xs ${basemap === 'satellite' ? 'bg-slate-900 text-white shadow-sm hover:bg-slate-900 hover:text-white' : 'text-slate-500 hover:bg-white hover:text-slate-950'}`} onClick={() => satelliteAvailable && setBasemap('satellite')} disabled={!satelliteAvailable} title={satelliteAvailable ? 'Vista satelital' : 'Configura REACT_APP_SATELLITE_TILE_URL para habilitar Satélite'} data-testid="geo-basemap-satellite"><Satellite className="h-3.5 w-3.5" /><span className="hidden lg:inline">Satélite</span></Button></div>
    {!evangelism && <div className="flex h-9 shrink-0 border bg-white" data-testid="geo-map-mode-control">{canViewPrecise && <Button type="button" size="sm" variant={mode === 'pins' ? 'default' : 'ghost'} className="h-8 rounded-none px-2" onClick={() => setMode('pins')} data-testid="geo-mode-pins" aria-label="Puntos individuales"><MapPin className="h-4 w-4" /><span className="hidden xl:inline">Puntos</span></Button>}<Button type="button" size="sm" variant={mode === 'heatmap' ? 'default' : 'ghost'} className="h-8 rounded-none px-2" onClick={() => setMode('heatmap')} data-testid="geo-mode-heatmap" aria-label="Densidad"><Flame className="h-4 w-4" /><span className="hidden xl:inline">Densidad</span></Button></div>}
    {evangelism && <><select value={evangelismStatus} onChange={(event) => setEvangelismStatus(event.target.value)} className="h-9 max-w-[180px] border bg-white px-2 text-sm" data-testid="evangelism-status-filter">{targetStatuses.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><span className="border border-emerald-200 bg-emerald-50 px-2 py-1.5 text-xs font-semibold text-emerald-900" data-testid="evangelism-target-total">{evangelismTotal || 0} casas</span><Button size="sm" className="h-9 bg-emerald-700 hover:bg-emerald-800" onClick={onAddEvangelism} data-testid="btn-quick-add-house"><Plus className="h-4 w-4" />Registrar casa</Button></>}
    {!evangelism && <><div className="hidden shrink-0 items-center gap-1.5 2xl:flex" data-testid="geo-summary-compact"><span className="border px-2 py-1 text-xs"><b>{summary.people_total || 0}</b> personas</span><span className="border px-2 py-1 text-xs"><b>{summary.front_groups_total || 0}</b> grupos</span><span className="border px-2 py-1 text-xs"><b>{summary.cells_total || 0}</b> células</span></div>
      <Popover><PopoverTrigger asChild><Button variant="outline" size="sm" className="h-9" data-testid="open-geo-filters"><Filter className="h-4 w-4" /><span className="hidden lg:inline">Filtros</span>{countFilters(filters) > 0 && <span className="bg-amber-600 px-1.5 text-[10px] text-white">{countFilters(filters)}</span>}</Button></PopoverTrigger><PopoverContent align="end" className="w-[min(92vw,720px)] bg-white p-4"><GeoFilters filters={filters} setFilters={setFilters} catalog={catalog} /></PopoverContent></Popover>
      <Button variant={compare ? 'default' : 'outline'} size="sm" className="h-9" onClick={() => setCompare((value) => !value)} data-testid="toggle-geo-comparison"><Layers3 className="h-4 w-4" /><span className="hidden 2xl:inline">Comparar</span></Button>
      <Button variant="outline" size="sm" className="h-9 border-slate-900 text-slate-900" onClick={onPresent} data-testid="open-geo-presentation"><Presentation className="h-4 w-4" /><span className="hidden xl:inline">Presentar</span></Button>
      {canManage && <Button variant="outline" size="sm" className="h-9" onClick={onEditSectors} data-testid="open-geo-sector-editor"><Edit3 className="h-4 w-4" /><span className="hidden xl:inline">Sectores</span></Button>}
      {canManage && <Button variant="outline" size="sm" className="h-9 border-amber-400 bg-amber-50 text-amber-950" onClick={onUnlocated} data-testid="open-geo-unlocated"><MapPinOff className="h-4 w-4" /><span className="hidden xl:inline">Sin ubicación</span>{summary.unlocated_total > 0 && <span className="text-xs font-bold" data-testid="geo-unlocated-badge">{summary.unlocated_total}</span>}</Button>}
      {canManage && <Button variant="outline" size="sm" className="h-9" onClick={onBackfill} disabled={backfilling || !providerConfigured} data-testid="geo-backfill-button"><RefreshCw className={`h-4 w-4 ${backfilling ? 'animate-spin' : ''}`} /><span className="hidden 2xl:inline">Geocodificar</span></Button>}
      {canManage && <Button variant="outline" size="sm" className="h-9" onClick={onReview} data-testid="open-geo-review-button"><CircleAlert className="h-4 w-4" /><span className="hidden xl:inline">Verificar</span>{summary.review_total > 0 && <span className="text-xs">{summary.review_total}</span>}</Button>}
    </>}
  </div></header>;
};