import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { Loader2, MapPinned, RefreshCw } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '../../context/AuthContext';
import { apiErrorMessage } from '../../lib/apiErrors';
import { Button } from '../ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '../ui/dialog';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { GeoPinEditor } from './GeoPinEditor';

export const GeoReviewDialog = ({ open, onOpenChange, center, onResolved }) => {
  const { API, getAuthHeaders } = useAuth(); const [items, setItems] = useState([]);
  const [selected, setSelected] = useState(null); const [point, setPoint] = useState(null);
  const [reason, setReason] = useState('Corrección manual verificada por personal autorizado'); const [busy, setBusy] = useState('');
  const load = async () => { const response = await axios.get(`${API}/api/geo/review-queue`, getAuthHeaders()); setItems(response.data.items || []); setSelected((current) => current && response.data.items.find((item) => item.review_id === current.review_id)); };
  useEffect(() => { if (open) load().catch((error) => toast.error(apiErrorMessage(error, 'No se pudo cargar la cola'))); }, [open]); // eslint-disable-line react-hooks/exhaustive-deps
  const retry = async (item) => { setBusy(item.review_id); try { await axios.post(`${API}/api/geo/review-queue/${encodeURIComponent(item.review_id)}/retry`, {}, getAuthHeaders()); toast.success('Reintento programado'); await load(); } catch (error) { toast.error(apiErrorMessage(error, 'No se pudo reintentar')); } finally { setBusy(''); } };
  const resolve = async () => { if (!selected || !point) return; setBusy(selected.review_id); try { await axios.post(`${API}/api/geo/review-queue/${encodeURIComponent(selected.review_id)}/resolve`, { ...point, reason }, getAuthHeaders()); toast.success('Ubicación verificada manualmente'); setSelected(null); setPoint(null); await load(); await onResolved(); } catch (error) { toast.error(apiErrorMessage(error, 'No se pudo guardar el pin')); } finally { setBusy(''); } };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92vh] max-w-5xl overflow-y-auto bg-white" data-testid="geo-review-dialog"><DialogHeader><DialogTitle className="flex items-center gap-2"><MapPinned className="h-5 w-5 text-amber-700" />Ubicación necesita verificación</DialogTitle><DialogDescription>Reintente Census o coloque un pin manual. La corrección prevalecerá mientras la dirección no cambie.</DialogDescription></DialogHeader><div className="grid gap-5 lg:grid-cols-[.75fr_1.25fr]"><section className="max-h-[60vh] overflow-y-auto border" data-testid="geo-review-list">{items.length === 0 && <p className="p-5 text-sm text-slate-500" data-testid="geo-review-empty">No hay ubicaciones pendientes.</p>}{items.map((item) => <article key={item.review_id} className={`border-b p-3 ${selected?.review_id === item.review_id ? 'bg-amber-50' : 'bg-white'}`}><button type="button" className="w-full text-left" onClick={() => { setSelected(item); setPoint(item.candidate_location || null); }} data-testid={`select-geo-review-${item.review_id}`}><b className="text-sm">{item.label}</b><p className="text-xs text-slate-500">{item.address || 'Dirección incompleta'}</p><span className="text-[10px] uppercase text-amber-700">{item.reason}</span></button><Button size="sm" variant="outline" className="mt-2" disabled={busy === item.review_id} onClick={() => retry(item)} data-testid={`retry-geo-review-${item.review_id}`}><RefreshCw className="h-3.5 w-3.5" />Reintentar Census</Button></article>)}</section><section>{selected ? <div className="space-y-4"><div><h3 className="font-['Spectral'] text-xl font-semibold">{selected.label}</h3><p className="text-sm text-slate-500">{selected.address}</p></div><GeoPinEditor center={center} value={point} onChange={setPoint} /><div className="grid gap-3 sm:grid-cols-2"><div><Label>Latitud</Label><Input readOnly value={point?.latitude?.toFixed(6) || ''} data-testid="manual-location-latitude" /></div><div><Label>Longitud</Label><Input readOnly value={point?.longitude?.toFixed(6) || ''} data-testid="manual-location-longitude" /></div></div><div><Label htmlFor="manual-location-reason">Motivo</Label><Input id="manual-location-reason" value={reason} onChange={(event) => setReason(event.target.value)} data-testid="manual-location-reason" /></div><Button className="w-full bg-slate-900 text-white" disabled={!point || reason.trim().length < 3 || busy === selected.review_id} onClick={resolve} data-testid="save-manual-location-button">{busy === selected.review_id && <Loader2 className="h-4 w-4 animate-spin" />}Guardar pin verificado</Button></div> : <div className="flex min-h-72 items-center justify-center border border-dashed text-sm text-slate-500">Seleccione una ubicación pendiente.</div>}</section></div></DialogContent></Dialog>;
};