import React, { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Church, Expand, Home, LogOut, Map, Route, Users } from 'lucide-react';
import { Button } from '../ui/button';
import { GeoMapCanvas } from './GeoMapCanvas';
import { pointInPolygon, zoneGeometry } from './geoGeometry';

const zoneLabels = { north: 'Zona 1 · Norte', east: 'Zona 2 · Este', south: 'Zona 3 · Sur', west: 'Zona 4 · Oeste' };

export const Presentation2To1Shell = ({ config, sectors, features, onExit }) => {
  const [history, setHistory] = useState([{ level: 'zone', zoneId: null, sectorId: null, householdId: null }]); const [index, setIndex] = useState(0);
  const current = history[index]; const selectedSector = sectors.find((item) => item.sector_id === current.sectorId) || null;
  const selectedHousehold = features.find((item) => item.properties?.entity_id === current.householdId) || null;
  const navigate = (next) => { setHistory((items) => [...items.slice(0, index + 1), next]); setIndex((value) => value + 1); };
  const chooseZone = (zoneId) => navigate({ level: 'sector', zoneId, sectorId: null, householdId: null });
  const chooseSector = (sectorId) => navigate({ level: 'sector', zoneId: sectors.find((item) => item.sector_id === sectorId)?.zone_id, sectorId, householdId: null });
  const visibleSectors = current.zoneId ? sectors.filter((item) => item.zone_id === current.zoneId) : sectors;
  const visibleFeatures = useMemo(() => {
    if (current.level !== 'households' || !selectedSector) return [];
    return features.filter((item) => item.properties?.entity_kind === 'household' && pointInPolygon(item.geometry.coordinates, selectedSector.geometry));
  }, [current.level, features, selectedSector]);
  const focusGeometry = selectedSector?.geometry || (current.zoneId ? zoneGeometry(config.zones, current.zoneId) : null);
  const title = selectedHousehold?.properties?.name || selectedSector?.name || (current.zoneId ? zoneLabels[current.zoneId] : 'Territorio completo');
  const levelLabel = { zone: 'Zonas', sector: 'Sectores', streets: 'Calles', households: 'Hogares' }[current.level];
  const enterFullscreen = () => document.documentElement.requestFullscreen?.();
  return <div className="fixed inset-0 z-[100] flex items-center justify-center overflow-hidden bg-black" data-testid="geo-presentation-overlay">
    <div className="geo-presentation-stage relative overflow-hidden bg-slate-950" data-testid="geo-presentation-2to1-stage">
      <GeoMapCanvas center={config.center} zones={config.zones} subzones={config.subzones} sectors={current.level === 'zone' ? [] : visibleSectors} features={visibleFeatures} mode="pins" presentationLevel={current.level} focusGeometry={focusGeometry} selectedSectorId={current.sectorId} onSelectZone={current.level === 'zone' ? chooseZone : undefined} onSelectSector={current.level === 'sector' ? chooseSector : undefined} onSelect={(feature) => feature.properties?.entity_kind === 'household' && navigate({ ...current, level: 'households', householdId: feature.properties.entity_id })} />
      <header className="absolute left-0 right-0 top-0 z-20 flex items-center gap-2 border-b border-white/15 bg-slate-950/95 px-3 py-2 text-white backdrop-blur-xl md:gap-4 md:px-5 md:py-3" data-testid="geo-presentation-header"><div className="flex h-10 w-10 shrink-0 items-center justify-center bg-rose-800 md:h-12 md:w-12"><Church className="h-6 w-6 md:h-7 md:w-7" /></div><div className="min-w-0 flex-1"><p className="text-[10px] font-bold uppercase text-amber-400 md:text-xs" data-testid="geo-presentation-level">{levelLabel}</p><h1 className="truncate font-['Spectral'] text-xl font-bold md:text-3xl" data-testid="geo-presentation-title">{title}</h1></div><div className="flex gap-1 md:gap-2"><Button variant="outline" size="icon" className="h-9 w-9 border-white/30 bg-slate-900 text-white" onClick={() => setIndex((value) => Math.max(0, value - 1))} disabled={index === 0} data-testid="geo-presentation-back" aria-label="Atrás"><ArrowLeft className="h-5 w-5" /></Button><Button variant="outline" size="icon" className="h-9 w-9 border-white/30 bg-slate-900 text-white" onClick={() => setIndex((value) => Math.min(history.length - 1, value + 1))} disabled={index >= history.length - 1} data-testid="geo-presentation-forward" aria-label="Adelante"><ArrowRight className="h-5 w-5" /></Button><Button variant="outline" size="icon" className="hidden h-9 w-9 border-white/30 bg-slate-900 text-white sm:inline-flex" onClick={enterFullscreen} data-testid="geo-presentation-fullscreen" aria-label="Pantalla completa"><Expand className="h-5 w-5" /></Button><Button variant="outline" size="icon" className="h-9 w-9 border-white/30 bg-slate-900 text-white md:w-auto md:px-4" onClick={onExit} data-testid="exit-geo-presentation" aria-label="Salir de presentación"><LogOut className="h-5 w-5" /><span className="hidden md:inline">Salir</span></Button></div></header>
      {current.level === 'zone' && <aside className="absolute bottom-3 left-3 z-20 grid w-[calc(100%-1.5rem)] max-w-[800px] grid-cols-2 gap-2 md:bottom-5 md:left-5 md:w-[min(94%,800px)] md:grid-cols-4" data-testid="geo-presentation-zone-selector">{Object.entries(zoneLabels).map(([zoneId, label]) => <button key={zoneId} type="button" className="border border-white/20 bg-slate-950/95 p-3 text-left text-white shadow-2xl backdrop-blur-xl transition-transform hover:-translate-y-1 hover:bg-slate-900 md:p-4" onClick={() => chooseZone(zoneId)} data-testid={`geo-presentation-zone-${zoneId}`}><Map className="mb-1 h-5 w-5 text-cyan-400 md:mb-2 md:h-6 md:w-6" /><b className="block text-sm md:text-lg">{label}</b><span className="text-[10px] text-slate-300 md:text-xs">{sectors.filter((item) => item.zone_id === zoneId).length} sectores</span></button>)}</aside>}
      {current.level === 'sector' && <aside className="absolute bottom-3 left-3 z-20 max-h-[60%] w-[calc(100%-1.5rem)] max-w-[470px] overflow-y-auto border border-white/15 bg-slate-950/95 p-4 text-white shadow-2xl backdrop-blur-xl md:bottom-5 md:left-5" data-testid="geo-presentation-sector-panel">{selectedSector ? <><p className="text-xs font-bold uppercase text-cyan-400">Sector seleccionado</p><h2 className="mt-1 font-['Spectral'] text-2xl font-bold md:text-3xl">{selectedSector.name}</h2><div className="mt-4 grid grid-cols-2 gap-2 text-center md:grid-cols-4"><Metric icon={Users} value={selectedSector.stats?.people_count} label="Personas" testId="people" /><Metric icon={Home} value={selectedSector.stats?.households_count} label="Hogares" testId="households" /><Metric icon={Users} value={selectedSector.stats?.leaders_count} label="Líderes" testId="leaders" /><Metric icon={Church} value={selectedSector.stats?.cells_count} label="Células" testId="cells" /></div><Button className="mt-4 w-full bg-amber-500 text-slate-950 hover:bg-amber-400" onClick={() => navigate({ ...current, level: 'streets' })} data-testid="geo-presentation-explore-sector"><Route className="h-5 w-5" />Explorar calles</Button></> : <><p className="text-lg">Seleccione un sector en el mapa o en esta lista.</p><div className="mt-3 space-y-2">{visibleSectors.map((sector) => <button type="button" key={sector.sector_id} className="flex w-full items-center justify-between border border-white/15 bg-white/5 px-3 py-2 text-left hover:bg-white/10" onClick={() => chooseSector(sector.sector_id)} data-testid={`select-geo-presentation-sector-${sector.sector_id}`}><span><b className="block">{sector.name}</b><small className="text-slate-300">{sector.stats?.households_count || 0} hogares</small></span><ArrowRight className="h-4 w-4 text-amber-400" /></button>)}</div></>}</aside>}
      {current.level === 'streets' && <aside className="absolute bottom-5 left-5 z-20 border border-white/15 bg-slate-950/95 p-4 text-white shadow-2xl backdrop-blur-xl" data-testid="geo-presentation-streets-panel"><p className="text-xs font-bold uppercase text-cyan-400">Calles reales</p><h2 className="font-['Spectral'] text-2xl font-bold">{selectedSector?.name}</h2><Button className="mt-3 bg-amber-500 text-slate-950 hover:bg-amber-400" onClick={() => navigate({ ...current, level: 'households' })} data-testid="geo-presentation-show-households"><Home className="h-5 w-5" />Mostrar hogares</Button></aside>}
      {current.level === 'households' && <aside className="absolute bottom-5 left-5 z-20 max-h-[58%] w-[min(94%,480px)] overflow-y-auto border border-white/15 bg-slate-950/95 p-4 text-white shadow-2xl backdrop-blur-xl" data-testid="geo-presentation-household-panel">{selectedHousehold ? <><p className="text-xs font-bold uppercase text-amber-400">Hogar autorizado</p><h2 className="font-['Spectral'] text-2xl font-bold">{selectedHousehold.properties.address}</h2><div className="mt-3 space-y-2">{selectedHousehold.properties.residents?.map((resident) => <div key={resident.person_id} className="border-l-2 border-amber-400 bg-white/5 px-3 py-2" data-testid={`geo-presentation-resident-${resident.person_id}`}><b>{resident.name}</b><span className="ml-2 text-sm text-slate-300">{resident.household_role || resident.person_number || 'Persona 360'}</span></div>)}</div></> : <><p className="text-xs font-bold uppercase text-cyan-400">Hogares del sector</p><p className="text-2xl font-bold" data-testid="geo-presentation-household-count">{visibleFeatures.length} pines agrupados</p><p className="text-sm text-slate-300">Seleccione un pin 🏠 para ver las personas autorizadas.</p></>}</aside>}
    </div>
  </div>;
};

const Metric = ({ icon: Icon, value = 0, label, testId }) => <div className="bg-white/5 p-2"><Icon className="mx-auto h-4 w-4 text-amber-400" /><b className="mt-1 block text-2xl" data-testid={`geo-presentation-metric-${testId}`}>{value || 0}</b><span className="text-[10px] uppercase text-slate-300">{label}</span></div>;