import React, { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { CalendarClock, HeartHandshake, Loader2, Plus } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '../../context/AuthContext';
import { ProcessError, ProcessLoading, ProcessShell } from '../../components/processes/ProcessShell';
import { ProcessStatus } from '../../components/processes/ProcessStatus';
import { Button } from '../../components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '../../components/ui/dialog';
import { Input } from '../../components/ui/input';
import { Label } from '../../components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../../components/ui/select';
import { Switch } from '../../components/ui/switch';
import { Textarea } from '../../components/ui/textarea';

const MeetingDialog = ({ mentorship, onSaved }) => {
  const { API, getAuthHeaders } = useAuth(); const [open, setOpen] = useState(false); const [detail, setDetail] = useState(null); const [saving, setSaving] = useState(false); const [form, setForm] = useState({ attended: true, lesson_title: '', notes: '', commitments: '', next_meeting_at: '' });
  useEffect(() => { if (open) axios.get(`${API}/api/processes/mentorships/${mentorship.mentorship_id}`, getAuthHeaders()).then((response) => setDetail(response.data)); }, [API, getAuthHeaders, mentorship.mentorship_id, open]);
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { await axios.post(`${API}/api/processes/mentorships/${mentorship.mentorship_id}/meetings`, { attended: form.attended, lesson_title: form.lesson_title || null, notes: form.notes || null, commitments: form.commitments.split(',').map((item) => item.trim()).filter(Boolean), next_meeting_at: form.next_meeting_at ? new Date(form.next_meeting_at).toISOString() : null }, getAuthHeaders()); toast.success('Encuentro registrado'); setOpen(false); await onSaved(); } catch (error) { toast.error(error?.response?.data?.detail || 'No se pudo registrar el encuentro'); } finally { setSaving(false); } };
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="outline" size="sm" data-testid={`open-mentorship-${mentorship.mentorship_id}`}><CalendarClock className="mr-1 h-4 w-4" />Encuentros</Button></DialogTrigger><DialogContent className="max-h-[85vh] overflow-y-auto bg-white"><DialogHeader><DialogTitle>Seguimiento de Mentoría</DialogTitle><DialogDescription>{mentorship.person.name} con {mentorship.mentor.name}. Reuniones, lecciones y compromisos verificables.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-3"><label className="flex items-center gap-3 rounded-md border p-3"><Switch checked={form.attended} onCheckedChange={(value) => setForm((old) => ({ ...old, attended: value }))} data-testid="mentorship-attended-switch" /><span className="text-sm">Encuentro realizado</span></label><Input value={form.lesson_title} onChange={(event) => setForm((old) => ({ ...old, lesson_title: event.target.value }))} placeholder="Lección trabajada" data-testid="mentorship-lesson-input" /><Textarea value={form.notes} onChange={(event) => setForm((old) => ({ ...old, notes: event.target.value }))} placeholder="Seguimiento y resultado" data-testid="mentorship-notes-input" /><Input value={form.commitments} onChange={(event) => setForm((old) => ({ ...old, commitments: event.target.value }))} placeholder="Compromisos, separados por comas" data-testid="mentorship-commitments-input" /><div><Label htmlFor="mentorship-next-meeting">Próximo encuentro</Label><Input id="mentorship-next-meeting" type="datetime-local" value={form.next_meeting_at} onChange={(event) => setForm((old) => ({ ...old, next_meeting_at: event.target.value }))} data-testid="mentorship-next-meeting-input" /></div><Button type="submit" disabled={saving} className="w-full bg-slate-900" data-testid="mentorship-meeting-submit-button">{saving && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Registrar encuentro</Button></form><div className="space-y-2 border-t pt-4">{detail?.meetings?.map((meeting) => <div key={meeting.meeting_id} className="rounded-md border p-3"><p className="font-medium text-slate-900">{meeting.lesson_title || 'Encuentro de seguimiento'}</p><p className="text-xs text-slate-500">{new Date(meeting.occurred_at).toLocaleString('es')} · {meeting.attended ? 'Realizado' : 'No realizado'}</p>{meeting.notes && <p className="mt-1 text-sm text-slate-700">{meeting.notes}</p>}</div>)}</div></DialogContent></Dialog>;
};

export default function MentorshipPage() {
  const { API, getAuthHeaders, user } = useAuth(); const [items, setItems] = useState([]); const [people, setPeople] = useState([]); const [mentors, setMentors] = useState([]); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [form, setForm] = useState({ person_id: '', mentor_person_id: '', goals: '', next_meeting_at: '' });
  const load = useCallback(async () => { try { const requests = [axios.get(`${API}/api/processes/mentorships`, getAuthHeaders()), axios.get(`${API}/api/processes/catalog`, getAuthHeaders())]; if (user?.rol !== 'persona') requests.push(axios.get(`${API}/api/core/persons?limit=100`, getAuthHeaders())); const responses = await Promise.all(requests); setItems(responses[0].data.items || []); setMentors(responses[1].data.assignees || []); setPeople(responses[2]?.data?.items || []); } catch (requestError) { const detail = requestError?.response?.data?.detail; setError(typeof detail === 'string' ? detail : 'No se pudo cargar Mentoría.'); } finally { setLoading(false); } }, [API, getAuthHeaders, user?.rol]);
  useEffect(() => { load(); }, [load]);
  const create = async (event) => { event.preventDefault(); setSaving(true); try { await axios.post(`${API}/api/processes/mentorships`, { person_id: form.person_id, mentor_person_id: form.mentor_person_id, goals: form.goals.split(',').map((item) => item.trim()).filter(Boolean), next_meeting_at: form.next_meeting_at ? new Date(form.next_meeting_at).toISOString() : null }, getAuthHeaders()); toast.success('Mentoría iniciada'); setOpen(false); await load(); } catch (requestError) { toast.error(requestError?.response?.data?.detail || 'No se pudo iniciar Mentoría'); } finally { setSaving(false); } };
  const actions = <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="bg-amber-600 text-white hover:bg-amber-700" data-testid="open-create-mentorship-button"><Plus className="mr-2 h-4 w-4" />Nueva Mentoría</Button></DialogTrigger><DialogContent className="bg-white"><DialogHeader><DialogTitle>Asignar Mentoría</DialogTitle><DialogDescription>Mentor y persona se vinculan exclusivamente mediante sus person_id canónicos.</DialogDescription></DialogHeader><form onSubmit={create} className="space-y-4"><Select value={form.person_id} onValueChange={(value) => setForm((old) => ({ ...old, person_id: value }))}><SelectTrigger data-testid="mentorship-person-select"><SelectValue placeholder="Persona acompañada" /></SelectTrigger><SelectContent className="max-h-64 bg-white">{people.map((person) => <SelectItem key={person.person_id} value={person.person_id}>{person.nombre} {person.apellido} · {person.person_number}</SelectItem>)}</SelectContent></Select><Select value={form.mentor_person_id} onValueChange={(value) => setForm((old) => ({ ...old, mentor_person_id: value }))}><SelectTrigger data-testid="mentorship-mentor-select"><SelectValue placeholder="Mentor" /></SelectTrigger><SelectContent className="bg-white">{mentors.map((mentor) => <SelectItem key={mentor.person_id} value={mentor.person_id}>{mentor.name}</SelectItem>)}</SelectContent></Select><Input value={form.goals} onChange={(event) => setForm((old) => ({ ...old, goals: event.target.value }))} placeholder="Metas, separadas por comas" data-testid="mentorship-goals-input" /><Input type="datetime-local" value={form.next_meeting_at} onChange={(event) => setForm((old) => ({ ...old, next_meeting_at: event.target.value }))} data-testid="mentorship-start-date-input" /><Button type="submit" disabled={saving || !form.person_id || !form.mentor_person_id} className="w-full bg-slate-900" data-testid="mentorship-create-submit-button">{saving && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Iniciar Mentoría</Button></form></DialogContent></Dialog>;
  if (loading) return <ProcessShell title="Mentoría" description="Cargando acompañamientos..."><ProcessLoading /></ProcessShell>;
  return <ProcessShell title="Mentoría Individual" description="Mentor ↔ Persona, reuniones, lecciones, progreso, próximo encuentro e historial." actions={actions}>{error ? <ProcessError message={error} /> : items.length === 0 ? <div className="rounded-md border border-dashed bg-white p-12 text-center"><HeartHandshake className="mx-auto h-9 w-9 text-slate-400" /><p className="mt-3 font-medium text-slate-800" data-testid="mentorship-empty-state">No hay Mentorías en este alcance.</p></div> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <article key={item.mentorship_id} className="rounded-md border border-slate-200 bg-white p-5 shadow-sm" data-testid={`mentorship-card-${item.mentorship_id}`}><div className="flex items-start justify-between"><div><p className="font-semibold text-slate-900">{item.person.name}</p><p className="text-xs text-slate-500">Mentor: {item.mentor.name}</p></div><ProcessStatus value={item.status} /></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-amber-600" style={{ width: `${item.progress_pct || 0}%` }} /></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs text-slate-500"><span>{item.meeting_count || 0} encuentros</span><span className="text-right">{item.progress_pct || 0}%</span></div><p className="mt-3 text-xs text-slate-500">Próximo encuentro</p><p className="text-sm font-medium text-slate-800">{item.next_meeting_at ? new Date(item.next_meeting_at).toLocaleString('es') : 'Sin programar'}</p><div className="mt-4"><MeetingDialog mentorship={item} onSaved={load} /></div></article>)}</div>}</ProcessShell>;
}