import React, { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { AlertTriangle, CheckCircle2, Clock3, Settings2, ShieldAlert, UserMinus, Waypoints } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '../../context/AuthContext';
import { ProcessError, ProcessLoading, ProcessShell } from '../../components/processes/ProcessShell';
import { Button } from '../../components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '../../components/ui/dialog';
import { Input } from '../../components/ui/input';
import { Label } from '../../components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../../components/ui/select';
import { Switch } from '../../components/ui/switch';

const metricConfig = [
  ['total', 'Personas en procesos', Waypoints], ['on_sla', 'En SLA', CheckCircle2], ['due_soon', 'Próximas a vencer', Clock3], ['overdue', 'Vencidas', ShieldAlert], ['without_responsible', 'Sin responsable', UserMinus], ['without_next_action', 'Sin próxima acción', AlertTriangle], ['average_progress', 'Avance promedio', Waypoints], ['retention', 'Retención', CheckCircle2], ['completed', 'Terminados', CheckCircle2], ['stalled', 'Detenidos', ShieldAlert], ['critical_alerts', 'Alertas críticas', ShieldAlert],
];

export default function ProcessesDashboardPage() {
  const { API, getAuthHeaders, user } = useAuth();
  const [dashboard, setDashboard] = useState(null); const [rules, setRules] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setError(''); try { const [dash, ruleResponse] = await Promise.all([axios.get(`${API}/api/processes/dashboard`, getAuthHeaders()), axios.get(`${API}/api/processes/alert-rules`, getAuthHeaders())]); setDashboard(dash.data); setRules(ruleResponse.data.items || []); } catch (requestError) { setError(requestError?.response?.data?.detail || 'No se pudo cargar el dashboard.'); } finally { setLoading(false); } }, [API, getAuthHeaders]);
  useEffect(() => { load(); }, [load]);
  const resolveAlert = async (alertId) => { await axios.put(`${API}/api/processes/alerts/${alertId}`, { status: 'resolved', resolution: 'Revisado por el responsable' }, getAuthHeaders()); toast.success('Alerta resuelta'); await load(); };
  const saveRule = async (rule) => { await axios.put(`${API}/api/processes/alert-rules/${rule.rule_key}`, { enabled: rule.enabled, threshold: Number(rule.threshold), severity: rule.severity }, getAuthHeaders()); toast.success('Regla SLA actualizada'); await load(); };
  if (loading) return <ProcessShell title="Dashboard de Procesos" description="Cargando operación real..."><ProcessLoading /></ProcessShell>;
  return <ProcessShell title="Dashboard de Procesos" description="Embudo operativo, SLA y alertas tempranas basados en hechos registrados. No toma decisiones pastorales automáticas." actions={user?.rol === 'pastor' ? <Dialog><DialogTrigger asChild><Button variant="outline" className="border-slate-600 bg-slate-800 text-white hover:bg-slate-700" data-testid="open-alert-rules-button"><Settings2 className="mr-2 h-4 w-4" />Configurar SLA</Button></DialogTrigger><DialogContent className="max-h-[80vh] max-w-2xl overflow-y-auto bg-white"><DialogHeader><DialogTitle>Reglas de alertas tempranas</DialogTitle><DialogDescription>Detectan hechos y retrasos operativos. Nunca califican decisiones pastorales.</DialogDescription></DialogHeader><div className="space-y-3">{rules.map((rule, index) => <div key={rule.rule_key} className="grid gap-3 rounded-md border border-slate-200 p-3 sm:grid-cols-[1fr_100px_130px_auto] sm:items-end" data-testid={`alert-rule-${rule.rule_key}`}><div><p className="font-medium text-slate-900">{rule.name}</p><p className="text-xs text-slate-500">{rule.condition}</p></div><div><Label>Umbral</Label><Input type="number" value={rule.threshold} onChange={(event) => setRules((old) => old.map((item, i) => i === index ? { ...item, threshold: event.target.value } : item))} data-testid={`alert-rule-threshold-${rule.rule_key}`} /></div><Select value={rule.severity} onValueChange={(value) => setRules((old) => old.map((item, i) => i === index ? { ...item, severity: value } : item))}><SelectTrigger data-testid={`alert-rule-severity-${rule.rule_key}`}><SelectValue /></SelectTrigger><SelectContent className="bg-white"><SelectItem value="info">Info</SelectItem><SelectItem value="warning">Atención</SelectItem><SelectItem value="critical">Crítica</SelectItem></SelectContent></Select><div className="flex items-center gap-2"><Switch checked={rule.enabled} onCheckedChange={(value) => setRules((old) => old.map((item, i) => i === index ? { ...item, enabled: value } : item))} data-testid={`alert-rule-enabled-${rule.rule_key}`} /><Button size="sm" onClick={() => saveRule(rule)} data-testid={`alert-rule-save-${rule.rule_key}`}>Guardar</Button></div></div>)}</div></DialogContent></Dialog> : null}>
    {error ? <ProcessError message={error} /> : <>
      <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4" data-testid="process-dashboard-metrics">{metricConfig.map(([key, label, Icon]) => <div key={key} className="rounded-md border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase text-slate-500">{label}</p><p className="mt-2 text-3xl font-semibold text-slate-900" data-testid={`process-metric-${key}`}>{dashboard?.metrics?.[key] ?? 0}{['average_progress', 'retention'].includes(key) ? '%' : ''}</p></div><Icon className={`h-5 w-5 ${['overdue', 'critical_alerts', 'stalled'].includes(key) ? 'text-rose-600' : 'text-amber-600'}`} /></div></div>)}</section>
      <section className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div><h2 className="font-['Spectral'] text-2xl font-semibold text-slate-900">Personas por etapa</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{Object.entries(dashboard?.by_stage || {}).length === 0 ? <div className="rounded-md border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500" data-testid="process-funnel-empty">Sin inscripciones todavía.</div> : Object.entries(dashboard.by_stage).map(([key, count]) => <div key={key} className="flex items-center justify-between rounded-md border border-slate-200 bg-white p-3" data-testid={`process-stage-count-${key}`}><span className="text-sm text-slate-700">{key.replace(':', ' · ').replaceAll('_', ' ')}</span><strong className="text-slate-900">{count}</strong></div>)}</div></div><div><h2 className="font-['Spectral'] text-2xl font-semibold text-slate-900">Alertas abiertas</h2><div className="mt-3 space-y-2">{dashboard?.alerts?.length === 0 ? <div className="rounded-md border border-emerald-200 bg-emerald-50 p-6 text-sm text-emerald-800" data-testid="process-alerts-empty">Sin alertas operativas abiertas.</div> : dashboard.alerts.map((alert) => <article key={alert.alert_id} className={`rounded-md border p-3 ${alert.severity === 'critical' ? 'border-rose-200 bg-rose-50' : 'border-amber-200 bg-amber-50'}`} data-testid={`process-alert-${alert.alert_id}`}><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-slate-900">{alert.rule_name}</p><p className="text-xs text-slate-600">{alert.person?.name} · {alert.fact}</p></div>{user?.rol !== 'persona' && <Button size="sm" variant="outline" onClick={() => resolveAlert(alert.alert_id)} data-testid={`resolve-alert-${alert.alert_id}`}>Resolver</Button>}</div></article>)}</div></div></section>
    </>}
  </ProcessShell>;
}