import React, { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { CalendarPlus, ChevronRight, Loader2, Plus } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { toast } from 'sonner';
import { useAuth } from '../../context/AuthContext';
import { EnrollmentDialog } from '../../components/processes/EnrollmentDialog';
import { ProcessError, ProcessLoading, ProcessShell } from '../../components/processes/ProcessShell';
import { ProcessStatus, SlaPill } from '../../components/processes/ProcessStatus';
import { Button } from '../../components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '../../components/ui/dialog';
import { Input } from '../../components/ui/input';
import { Label } from '../../components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../../components/ui/select';

export default function SevenWeeksPage() {
  const { API, getAuthHeaders, user } = useAuth(); const navigate = useNavigate();
  const [cycles, setCycles] = useState([]); const [enrollments, setEnrollments] = useState([]); const [assignees, setAssignees] = useState([]); const [filter, setFilter] = useState('all'); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [cycleOpen, setCycleOpen] = useState(false); const [saving, setSaving] = useState(false);
  const [cycle, setCycle] = useState({ name: '', start_date: '', end_date: '', capacity: '', status: 'planned' });
  const load = useCallback(async () => { setError(''); try { const [cycleResponse, enrollmentResponse, catalogResponse] = await Promise.all([axios.get(`${API}/api/processes/cycles`, getAuthHeaders()), axios.get(`${API}/api/processes/enrollments?process_key=seven_weeks`, getAuthHeaders()), axios.get(`${API}/api/processes/catalog`, getAuthHeaders())]); setCycles(cycleResponse.data.items || []); setEnrollments(enrollmentResponse.data.items || []); setAssignees(catalogResponse.data.assignees || []); } catch (requestError) { setError(requestError?.response?.data?.detail || 'No se pudo cargar 7 Semanas.'); } finally { setLoading(false); } }, [API, getAuthHeaders]);
  useEffect(() => { load(); }, [load]);
  const createCycle = async (event) => { event.preventDefault(); setSaving(true); try { await axios.post(`${API}/api/processes/cycles`, { ...cycle, capacity: cycle.capacity ? Number(cycle.capacity) : null }, getAuthHeaders()); toast.success('Ciclo creado'); setCycleOpen(false); setCycle({ name: '', start_date: '', end_date: '', capacity: '', status: 'planned' }); await load(); } catch (requestError) { toast.error(requestError?.response?.data?.detail || 'No se pudo crear el ciclo'); } finally { setSaving(false); } };
  const visible = filter === 'all' ? enrollments : enrollments.filter((item) => item.cycle_id === filter);
  const actions = <><Dialog open={cycleOpen} onOpenChange={setCycleOpen}><DialogTrigger asChild><Button variant="outline" className="border-slate-600 bg-slate-800 text-white hover:bg-slate-700" data-testid="open-cycle-dialog-button"><CalendarPlus className="mr-2 h-4 w-4" />Nuevo ciclo</Button></DialogTrigger><DialogContent className="bg-white"><DialogHeader><DialogTitle>Crear ciclo de 7 Semanas</DialogTitle><DialogDescription>Las fechas definen el marco operativo; cada semana conserva su SLA y evidencia.</DialogDescription></DialogHeader><form onSubmit={createCycle} className="space-y-4"><div><Label htmlFor="cycle-name">Nombre</Label><Input id="cycle-name" value={cycle.name} onChange={(event) => setCycle((old) => ({ ...old, name: event.target.value }))} required data-testid="cycle-name-input" /></div><div className="grid gap-3 sm:grid-cols-2"><div><Label htmlFor="cycle-start">Inicio</Label><Input id="cycle-start" type="date" value={cycle.start_date} onChange={(event) => setCycle((old) => ({ ...old, start_date: event.target.value }))} required data-testid="cycle-start-input" /></div><div><Label htmlFor="cycle-end">Fin</Label><Input id="cycle-end" type="date" value={cycle.end_date} onChange={(event) => setCycle((old) => ({ ...old, end_date: event.target.value }))} required data-testid="cycle-end-input" /></div></div><div><Label htmlFor="cycle-capacity">Capacidad</Label><Input id="cycle-capacity" type="number" value={cycle.capacity} onChange={(event) => setCycle((old) => ({ ...old, capacity: event.target.value }))} data-testid="cycle-capacity-input" /></div><Select value={cycle.status} onValueChange={(value) => setCycle((old) => ({ ...old, status: value }))}><SelectTrigger data-testid="cycle-status-select"><SelectValue /></SelectTrigger><SelectContent className="bg-white"><SelectItem value="planned">Planificado</SelectItem><SelectItem value="active">Activo</SelectItem></SelectContent></Select><Button type="submit" disabled={saving} className="w-full bg-slate-900" data-testid="cycle-submit-button">{saving && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Crear ciclo</Button></form></DialogContent></Dialog><EnrollmentDialog processKey="seven_weeks" cycles={cycles} assignees={assignees} onCreated={load} /></>;
  if (loading) return <ProcessShell title="Ley de las 7 Semanas" description="Cargando ciclos e inscripciones..."><ProcessLoading /></ProcessShell>;
  return <ProcessShell title="Ley de las 7 Semanas" description="Ciclos, asistencia, tareas, evidencia, resultados, histórico y próximo paso sobre el Perfil 360." actions={actions}>{error ? <ProcessError message={error} /> : <>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4" data-testid="seven-weeks-cycle-summary"><div className="rounded-md border bg-white p-4"><p className="text-xs uppercase text-slate-500">Ciclos</p><p className="mt-2 text-3xl font-semibold" data-testid="cycle-count">{cycles.length}</p></div><div className="rounded-md border bg-white p-4"><p className="text-xs uppercase text-slate-500">Inscripciones</p><p className="mt-2 text-3xl font-semibold" data-testid="seven-weeks-enrollment-count">{enrollments.length}</p></div><div className="rounded-md border bg-white p-4"><p className="text-xs uppercase text-slate-500">Activas</p><p className="mt-2 text-3xl font-semibold text-emerald-700">{enrollments.filter((item) => item.status === 'active').length}</p></div><div className="rounded-md border bg-white p-4"><p className="text-xs uppercase text-slate-500">Completadas</p><p className="mt-2 text-3xl font-semibold text-blue-700">{enrollments.filter((item) => item.status === 'completed').length}</p></div></section>
    <section><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><h2 className="font-['Spectral'] text-2xl font-semibold text-slate-900">Inscripciones</h2><Select value={filter} onValueChange={setFilter}><SelectTrigger className="w-full bg-white sm:w-64" data-testid="cycle-filter-select"><SelectValue /></SelectTrigger><SelectContent className="bg-white"><SelectItem value="all">Todos los ciclos</SelectItem>{cycles.map((item) => <SelectItem key={item.cycle_id} value={item.cycle_id}>{item.name}</SelectItem>)}</SelectContent></Select></div>{visible.length === 0 ? <div className="rounded-md border border-dashed border-slate-300 bg-white p-12 text-center"><Plus className="mx-auto h-8 w-8 text-slate-400" /><p className="mt-3 font-medium text-slate-800" data-testid="seven-weeks-empty-state">No hay inscripciones en este alcance.</p><p className="mt-1 text-sm text-slate-500">Cree un ciclo e inscriba Personas canónicas cuando corresponda.</p></div> : <div className="grid gap-3">{visible.map((item) => <button key={item.enrollment_id} type="button" onClick={() => navigate(`/procesos/7-semanas/${item.enrollment_id}`)} className="grid w-full gap-3 rounded-md border border-slate-200 bg-white p-4 text-left shadow-sm transition hover:border-amber-300 hover:shadow-md sm:grid-cols-[1fr_auto_auto_auto] sm:items-center" data-testid={`seven-weeks-enrollment-card-${item.enrollment_id}`}><div><p className="font-semibold text-slate-900">{item.person?.name}</p><p className="font-mono text-xs text-amber-700">{item.person?.person_number}</p></div><ProcessStatus value={item.status} /><div><p className="text-xs text-slate-500">Etapa</p><p className="text-sm font-medium text-slate-800">{item.current_stage?.stage_name || item.current_stage_key}</p></div><div className="flex items-center justify-between gap-3 sm:justify-end"><SlaPill dueAt={item.current_stage?.due_at} /><ChevronRight className="h-4 w-4 text-slate-400" /></div></button>)}</div>}</section>
  </>}</ProcessShell>;
}