import React, { useEffect, useState } from 'react';
import { CalendarPlus, Loader2, Repeat2 } from 'lucide-react';
import { Button } from '../ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '../ui/dialog';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { Textarea } from '../ui/textarea';

const localValue = (date) => { const value = new Date(date); value.setMinutes(value.getMinutes() - value.getTimezoneOffset()); return value.toISOString().slice(0, 16); };
const defaultForm = () => { const start = new Date(Date.now() + 86400000); start.setHours(19, 0, 0, 0); const end = new Date(start.getTime() + 2 * 3600000); return { title: '', event_type: 'service', description: '', location: '', starts_at: localValue(start), ends_at: localValue(end), capacity: '', registration_mode: 'open', frequency: 'none', interval: 1, weekdays: [start.getDay() === 0 ? 6 : start.getDay() - 1], end_mode: 'count', count: 8, until: '' }; };
const weekdays = [['L', 0], ['M', 1], ['X', 2], ['J', 3], ['V', 4], ['S', 5], ['D', 6]];

export const EventCreateDialog = ({ open, onOpenChange, onCreate, saving, error }) => {
  const [form, setForm] = useState(defaultForm());
  useEffect(() => { if (open) setForm(defaultForm()); }, [open]);
  const update = (field) => (event) => setForm((current) => ({ ...current, [field]: event.target.value }));
  const submit = (event) => { event.preventDefault(); const recurring = form.frequency !== 'none'; onCreate({ title: form.title, event_type: form.event_type, description: form.description || null, location: form.location, timezone: Intl.DateTimeFormat().resolvedOptions().timeZone || 'America/New_York', starts_at: new Date(form.starts_at).toISOString(), ends_at: new Date(form.ends_at).toISOString(), capacity: form.capacity ? Number(form.capacity) : null, registration_mode: form.registration_mode, recurrence: { frequency: form.frequency, interval: Number(form.interval), weekdays: form.weekdays, month_day: null, end_mode: recurring ? form.end_mode : 'count', count: recurring && form.end_mode === 'count' ? Number(form.count) : 1, until: recurring && form.end_mode === 'until' && form.until ? new Date(`${form.until}T23:59:00`).toISOString() : null } }); };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92vh] max-w-3xl overflow-y-auto bg-white" data-testid="event-create-dialog"><DialogHeader><DialogTitle className="flex items-center gap-2 font-['Spectral'] text-2xl"><CalendarPlus className="h-5 w-5 text-emerald-700" />Crear evento</DialogTitle><DialogDescription>Configure una fecha única o una serie recurrente. Las ocurrencias quedarán listas para turnos, inscripciones y check-in.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-5" data-testid="event-create-form">
    {error && <div className="border border-red-300 bg-red-50 p-3 text-sm text-red-800" data-testid="event-create-error">{error}</div>}
    <div className="grid gap-4 sm:grid-cols-[1fr_220px]"><div><Label htmlFor="event-title">Nombre del evento *</Label><Input id="event-title" required value={form.title} onChange={update('title')} placeholder="Servicio de celebración" data-testid="event-title-input" /></div><div><Label htmlFor="event-type">Tipo</Label><select id="event-type" value={form.event_type} onChange={update('event_type')} className="h-10 w-full border bg-white px-3 text-sm" data-testid="event-type-select"><option value="service">Servicio</option><option value="conference">Conferencia</option><option value="training">Capacitación</option><option value="outreach">Evangelismo</option><option value="meeting">Reunión</option><option value="other">Otro</option></select></div></div>
    <div><Label htmlFor="event-location">Lugar *</Label><Input id="event-location" required value={form.location} onChange={update('location')} placeholder="Santuario principal" data-testid="event-location-input" /></div>
    <div className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="event-start">Inicio *</Label><Input id="event-start" type="datetime-local" required value={form.starts_at} onChange={update('starts_at')} data-testid="event-start-input" /></div><div><Label htmlFor="event-end">Final *</Label><Input id="event-end" type="datetime-local" required value={form.ends_at} onChange={update('ends_at')} data-testid="event-end-input" /></div></div>
    <div className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="event-capacity">Capacidad</Label><Input id="event-capacity" type="number" min="1" value={form.capacity} onChange={update('capacity')} placeholder="Sin límite" data-testid="event-capacity-input" /></div><div><Label htmlFor="event-registration">Inscripciones</Label><select id="event-registration" value={form.registration_mode} onChange={update('registration_mode')} className="h-10 w-full border bg-white px-3 text-sm" data-testid="event-registration-mode-select"><option value="open">Abiertas</option><option value="internal">Solo comunidad</option><option value="closed">Cerradas</option></select></div></div>
    <div className="border-l-4 border-blue-600 bg-blue-50 p-4" data-testid="event-recurrence-section"><div className="grid gap-4 sm:grid-cols-[1fr_140px]"><div><Label htmlFor="event-frequency" className="flex items-center gap-2"><Repeat2 className="h-4 w-4" />Recurrencia</Label><select id="event-frequency" value={form.frequency} onChange={update('frequency')} className="h-10 w-full border bg-white px-3 text-sm" data-testid="event-recurrence-frequency-select"><option value="none">Evento único</option><option value="daily">Diario</option><option value="weekly">Semanal</option><option value="monthly">Mensual</option></select></div>{form.frequency !== 'none' && <div><Label htmlFor="event-interval">Cada</Label><Input id="event-interval" type="number" min="1" max="12" value={form.interval} onChange={update('interval')} data-testid="event-recurrence-interval-input" /></div>}</div>
      {form.frequency === 'weekly' && <div className="mt-4"><Label>Días</Label><div className="mt-2 flex flex-wrap gap-2">{weekdays.map(([label, value]) => <Button key={value} type="button" size="icon" variant={form.weekdays.includes(value) ? 'default' : 'outline'} onClick={() => setForm((current) => ({ ...current, weekdays: current.weekdays.includes(value) ? current.weekdays.filter((item) => item !== value) : [...current.weekdays, value].sort() }))} data-testid={`event-weekday-${value}`}>{label}</Button>)}</div></div>}
      {form.frequency !== 'none' && <div className="mt-4 grid gap-4 sm:grid-cols-2"><div><Label htmlFor="event-end-mode">Finaliza</Label><select id="event-end-mode" value={form.end_mode} onChange={update('end_mode')} className="h-10 w-full border bg-white px-3 text-sm" data-testid="event-recurrence-end-mode-select"><option value="count">Después de varias ocurrencias</option><option value="until">En una fecha</option><option value="never">Sin fecha definida</option></select></div>{form.end_mode === 'count' && <div><Label htmlFor="event-count">Ocurrencias</Label><Input id="event-count" type="number" min="1" max="200" value={form.count} onChange={update('count')} data-testid="event-recurrence-count-input" /></div>}{form.end_mode === 'until' && <div><Label htmlFor="event-until">Hasta</Label><Input id="event-until" type="date" required value={form.until} onChange={update('until')} data-testid="event-recurrence-until-input" /></div>}</div>}
    </div>
    <div><Label htmlFor="event-description">Descripción</Label><Textarea id="event-description" value={form.description} onChange={update('description')} rows={3} data-testid="event-description-input" /></div>
    <DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)} data-testid="event-create-cancel-button">Cancelar</Button><Button type="submit" disabled={saving || (form.frequency === 'weekly' && form.weekdays.length === 0)} className="bg-emerald-700 hover:bg-emerald-800" data-testid="event-create-submit-button">{saving && <Loader2 className="h-4 w-4 animate-spin" />}Crear y materializar</Button></DialogFooter>
  </form></DialogContent></Dialog>;
};