import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { Save, ShieldCheck } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { Textarea } from '../ui/textarea';
import { useAuth } from '../../context/AuthContext';

export const ConfidentialityPolicyPanel = () => { const { API, getAuthHeaders } = useAuth(); const [policy, setPolicy] = useState(null); const [saving, setSaving] = useState(false); useEffect(() => { axios.get(`${API}/api/access/onboarding`, getAuthHeaders()).then((response) => setPolicy(response.data.policy)); }, [API, getAuthHeaders]); if (!policy) return null; const save = async () => { setSaving(true); try { const response = await axios.put(`${API}/api/access/policy`, { title: policy.title, body: policy.body, finance_max_users: policy.finance_max_users ? Number(policy.finance_max_users) : null }, getAuthHeaders()); setPolicy(response.data); toast.success(`Política versión ${response.data.version} publicada`); } catch (error) { toast.error(error?.response?.data?.detail || 'No se pudo publicar'); } finally { setSaving(false); } }; return <section className="mx-4 mt-6 border bg-white p-5 sm:mx-6 lg:mx-8" data-testid="confidentiality-policy-panel"><div className="flex items-start gap-3"><ShieldCheck className="mt-1 h-5 w-5 text-[#9A7A2F]" /><div><h2 className="font-['Spectral'] text-xl font-bold">Política de privacidad y confidencialidad</h2><p className="text-sm text-slate-500">Cada publicación crea una versión nueva; las firmas conservan el texto aceptado.</p></div></div><div className="mt-5 grid gap-4"><div><Label htmlFor="policy-title">Título</Label><Input id="policy-title" value={policy.title} onChange={(event) => setPolicy((old) => ({ ...old, title: event.target.value }))} data-testid="policy-title-input" /></div><div><Label htmlFor="policy-body">Texto vigente</Label><Textarea id="policy-body" className="min-h-36" value={policy.body} onChange={(event) => setPolicy((old) => ({ ...old, body: event.target.value }))} data-testid="policy-body-input" /></div><div className="max-w-xs"><Label htmlFor="finance-limit">Máximo de accesos a Finanzas (vacío = sin máximo)</Label><Input id="finance-limit" type="number" min="1" max="100" value={policy.finance_max_users || ''} onChange={(event) => setPolicy((old) => ({ ...old, finance_max_users: event.target.value }))} data-testid="finance-access-limit-input" /></div><Button onClick={save} disabled={saving || policy.body.length < 100} className="w-fit bg-[#101D36]" data-testid="save-policy-button"><Save className="mr-2 h-4 w-4" />Publicar nueva versión</Button></div></section>; };