import React, { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { ArrowRight, Filter, Loader2, SearchX } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { apiErrorMessage } from '../../lib/apiErrors';
import { PastoralCaseDialog } from '../../components/pastoral/PastoralCaseDialog';
import { PastoralShell } from '../../components/pastoral/PastoralShell';
import { caseTypeLabel, careStatusLabel, dateTime, priorityLabel, statusTone } from '../../lib/careLabels';

export default function PastoralCasesInboxPage() {
  const { API, getAuthHeaders, user } = useAuth(); const [params] = useSearchParams(); const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [status, setStatus] = useState(''); const [priority, setPriority] = useState('');
  const personId = params.get('person_id'); const canManage = user?.rol === 'pastor' || (user?.capabilities || []).includes('care.manage');
  const load = useCallback(() => { setLoading(true); setError(''); axios.get(`${API}/api/care/cases`, { ...getAuthHeaders(), params: { status: status || undefined, priority: priority || undefined, person_id: personId || undefined } }).then((response) => setItems(response.data.items || [])).catch((requestError) => setError(apiErrorMessage(requestError, 'No se pudo cargar la bandeja'))).finally(() => setLoading(false)); }, [API, getAuthHeaders, personId, priority, status]);
  useEffect(load, [load]);
  return <PastoralShell eyebrow="Bandeja operativa" title="Casos pastorales" description="Seguimiento por estado, prioridad, responsable y próximo paso." actions={canManage ? <PastoralCaseDialog onCreated={load} /> : null}>
    <div className="mb-5 flex flex-col gap-3 border bg-white p-4 sm:flex-row sm:items-end" data-testid="pastoral-case-filters"><div className="flex items-center gap-2 text-sm font-semibold text-slate-700"><Filter className="h-4 w-4" />Filtrar</div><label className="flex-1 text-xs font-semibold text-slate-500">Estado<select value={status} onChange={(event) => setStatus(event.target.value)} className="mt-1 h-10 w-full border bg-white px-3 text-sm" data-testid="pastoral-case-status-filter"><option value="">Todos</option>{Object.entries(careStatusLabel).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label className="flex-1 text-xs font-semibold text-slate-500">Prioridad<select value={priority} onChange={(event) => setPriority(event.target.value)} className="mt-1 h-10 w-full border bg-white px-3 text-sm" data-testid="pastoral-case-priority-filter"><option value="">Todas</option>{Object.entries(priorityLabel).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label></div>
    {error && <div className="border border-red-200 bg-red-50 p-4 text-sm text-red-800" data-testid="pastoral-cases-error">{error}</div>}
    {loading && <div className="flex justify-center py-24" data-testid="pastoral-cases-loading"><Loader2 className="h-8 w-8 animate-spin text-[#9A7E32]" /></div>}
    {!loading && !error && <section className="border bg-white" data-testid="pastoral-cases-list"><header className="flex items-center justify-between border-b p-4"><h2 className="font-['Spectral'] text-2xl font-semibold text-[#0B1428]">{personId ? 'Expedientes de la Persona' : 'Bandeja confidencial'}</h2><span className="text-sm text-slate-500" data-testid="pastoral-cases-total">{items.length} caso(s)</span></header>{items.length === 0 ? <div className="flex flex-col items-center px-6 py-16 text-center" data-testid="pastoral-cases-list-empty"><SearchX className="h-10 w-10 text-[#C8A951]" /><b className="mt-3 text-slate-800">No hay casos en esta bandeja</b><p className="mt-1 text-sm text-slate-500">Ajuste los filtros o abra un nuevo expediente autorizado.</p></div> : <div className="divide-y">{items.map((item) => <Link key={item.case_id} to={`/cuidado-pastoral/casos/${item.case_id}`} className="grid gap-3 p-4 transition-colors hover:bg-[#FDF9EE] md:grid-cols-[1.2fr_.8fr_.8fr_auto] md:items-center" data-testid={`pastoral-inbox-case-${item.case_id}`}><div className="min-w-0"><b className="block truncate text-sm text-[#0B1428]" data-testid={`pastoral-inbox-person-${item.case_id}`}>{item.person?.name}</b><span className="text-xs text-slate-500">{item.person?.person_number} · {caseTypeLabel[item.case_type]}</span></div><div><span className={`inline-flex border px-2 py-1 text-xs font-semibold ${statusTone(item.status)}`} data-testid={`pastoral-inbox-status-${item.case_id}`}>{careStatusLabel[item.status]}</span><p className="mt-1 text-xs text-slate-500">Prioridad {priorityLabel[item.priority]}</p></div><div className="text-xs text-slate-500"><p className="font-semibold text-slate-700">{item.next_step || 'Sin próximo paso'}</p><p>{dateTime(item.next_step_at)}</p></div><ArrowRight className="hidden h-4 w-4 text-slate-400 md:block" /></Link>)}</div>}</section>}
  </PastoralShell>;
}