import React, { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { ArrowLeft, Clock3, Link2, Loader2, PhoneCall, UserPlus } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { toast } from 'sonner';
import { useAuth } from '../../context/AuthContext';
import { apiErrorMessage } from '../../lib/apiErrors';
import { PastoralEscalationDialog } from '../../components/pastoral/PastoralEscalationDialog';
import { PastoralShell } from '../../components/pastoral/PastoralShell';
import { PastoralVaultPanel } from '../../components/pastoral/PastoralVaultPanel';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';
import { Label } from '../../components/ui/label';
import { Textarea } from '../../components/ui/textarea';
import { alertLabel, caseTypeLabel, careStatusLabel, dateTime, priorityLabel, statusTone } from '../../lib/careLabels';

export default function PastoralExpedienteDetailPage() {
  const { caseId } = useParams(); const { API, getAuthHeaders } = useAuth(); const [item, setItem] = useState(null); const [catalog, setCatalog] = useState({ assignees: [], authorities: [] }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [assignee, setAssignee] = useState(''); const [contact, setContact] = useState({ method: 'call', outcome: 'successful', next_step: '', next_step_at: '' }); const [transition, setTransition] = useState({ status: 'follow_up', reason: '' });
  const load = useCallback(() => { setError(''); Promise.all([axios.get(`${API}/api/care/cases/${caseId}`, getAuthHeaders()), axios.get(`${API}/api/care/catalog`, getAuthHeaders())]).then(([caseResponse, catalogResponse]) => { setItem(caseResponse.data); setCatalog(catalogResponse.data); }).catch((requestError) => setError(apiErrorMessage(requestError, 'No se pudo abrir el expediente'))); }, [API, caseId, getAuthHeaders]);
  useEffect(load, [load]);
  const act = async (path, body, success) => { setSaving(true); try { await axios.post(`${API}${path}`, body, getAuthHeaders()); toast.success(success); await load(); } catch (requestError) { toast.error(apiErrorMessage(requestError, 'No se pudo completar la acción')); } finally { setSaving(false); } };
  if (!item) return <PastoralShell title="Expediente pastoral" description="Acceso confidencial auditado."><div className="flex justify-center py-24" data-testid="pastoral-case-detail-loading">{error ? <p className="text-red-700" data-testid="pastoral-case-detail-error">{error}</p> : <Loader2 className="h-8 w-8 animate-spin text-[#9A7E32]" />}</div></PastoralShell>;
  const activePrimary = item.assignments?.find((assignment) => assignment.assignment_role === 'primary');
  return <PastoralShell eyebrow={caseTypeLabel[item.case_type]} title={item.person?.name || 'Expediente pastoral'} description={`${item.person?.person_number || ''} · La información libre permanece dentro de la bóveda cifrada.`} actions={item.permissions?.write ? <PastoralEscalationDialog authorities={catalog.authorities} saving={saving} onEscalate={(body) => act(`/api/care/cases/${caseId}/escalate`, body, 'Caso escalado y auditado')} /> : null}>
    <Link to="/cuidado-pastoral/casos" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-slate-600" data-testid="pastoral-case-back-link"><ArrowLeft className="h-4 w-4" />Volver a casos</Link>
    {item.op72 && <div className="mb-5 flex flex-col gap-3 border border-[#C8A951]/50 bg-[#FDF9EE] p-4 sm:flex-row sm:items-center" data-testid="pastoral-case-op72-banner"><Clock3 className="h-6 w-6 text-[#9A7E32]" /><div className="flex-1"><b className="text-sm text-[#0B1428]">Operación 72 histórica única</b><p className="text-xs text-slate-600">Primera decisión: {dateTime(item.op72.first_conversion_at)} · El registro original nunca se reinicia.</p></div><Link to="/cuidado-pastoral/operacion-72" className="text-sm font-semibold text-[#1B2A4A]" data-testid="pastoral-case-op72-link"><Link2 className="mr-1 inline h-4 w-4" />Abrir Operación 72</Link></div>}
    <div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]">
      <div className="space-y-6"><section className="border bg-white p-5" data-testid="pastoral-case-summary"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><small className="text-xs uppercase text-slate-400">Estado</small><p className={`mt-1 inline-flex border px-2 py-1 text-xs font-semibold ${statusTone(item.status)}`} data-testid="pastoral-case-current-status">{careStatusLabel[item.status]}</p></div><div><small className="text-xs uppercase text-slate-400">Prioridad</small><p className="mt-1 text-sm font-semibold" data-testid="pastoral-case-current-priority">{priorityLabel[item.priority]}</p></div><div><small className="text-xs uppercase text-slate-400">Responsable</small><p className="mt-1 text-sm font-semibold" data-testid="pastoral-case-current-assignee">{activePrimary?.assignee?.name || 'Sin asignar'}</p></div><div><small className="text-xs uppercase text-slate-400">Próximo paso</small><p className="mt-1 text-sm font-semibold" data-testid="pastoral-case-next-step">{item.next_step || 'Sin definir'}</p><p className="text-xs text-slate-500">{dateTime(item.next_step_at)}</p></div></div>{item.operational_summary && <p className="mt-5 border-t pt-4 text-sm text-slate-600" data-testid="pastoral-case-operational-summary">{item.operational_summary}</p>}</section>
        {(item.alerts || []).length > 0 && <section className="border border-red-200 bg-red-50 p-4" data-testid="pastoral-case-alerts"><h2 className="font-['Spectral'] text-xl font-semibold text-red-900">Alertas activas</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{item.alerts.map((alert) => <div key={alert.alert_id} className="border border-red-200 bg-white p-3 text-sm text-red-800" data-testid={`pastoral-case-alert-${alert.alert_id}`}><b>{alertLabel[alert.alert_type]}</b><p className="text-xs">{dateTime(alert.due_at)}</p></div>)}</div></section>}
        <PastoralVaultPanel caseId={caseId} permissions={item.permissions} />
      </div>
      <aside className="space-y-5">
        {item.permissions?.assign && <section className="border bg-white p-4" data-testid="pastoral-assignment-panel"><h2 className="flex items-center gap-2 font-['Spectral'] text-xl font-semibold"><UserPlus className="h-5 w-5 text-[#9A7E32]" />Asignación</h2><div className="mt-3 flex gap-2"><select value={assignee} onChange={(event) => setAssignee(event.target.value)} className="h-10 min-w-0 flex-1 border bg-white px-2 text-sm" data-testid="pastoral-assignee-select"><option value="">Responsable principal</option>{catalog.assignees.map((option) => <option key={option.person_id} value={option.person_id}>{option.name}</option>)}</select><Button disabled={!assignee || saving} onClick={() => act(`/api/care/cases/${caseId}/assignments`, { assignee_person_id: assignee, assignment_role: 'primary' }, 'Responsable asignado')} data-testid="pastoral-assign-submit-button">Asignar</Button></div></section>}
        {item.permissions?.write && <section className="border bg-white p-4" data-testid="pastoral-contact-panel"><h2 className="flex items-center gap-2 font-['Spectral'] text-xl font-semibold"><PhoneCall className="h-5 w-5 text-[#9A7E32]" />Registrar contacto</h2><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold text-slate-500">Medio<select value={contact.method} onChange={(event) => setContact((old) => ({ ...old, method: event.target.value }))} className="mt-1 h-10 w-full border bg-white px-2 text-sm" data-testid="pastoral-contact-method-select"><option value="call">Llamada</option><option value="message">Mensaje</option><option value="visit">Visita</option><option value="in_person">Presencial</option><option value="other">Otro</option></select></label><label className="text-xs font-semibold text-slate-500">Resultado<select value={contact.outcome} onChange={(event) => setContact((old) => ({ ...old, outcome: event.target.value }))} className="mt-1 h-10 w-full border bg-white px-2 text-sm" data-testid="pastoral-contact-outcome-select"><option value="successful">Exitoso</option><option value="no_answer">Sin respuesta</option><option value="wrong_number">Número incorrecto</option><option value="rescheduled">Reprogramado</option><option value="refused">Rechazado</option></select></label><Input value={contact.next_step} onChange={(event) => setContact((old) => ({ ...old, next_step: event.target.value }))} placeholder="Próximo paso" data-testid="pastoral-contact-next-step-input" /><Input type="datetime-local" value={contact.next_step_at} onChange={(event) => setContact((old) => ({ ...old, next_step_at: event.target.value }))} data-testid="pastoral-contact-next-date-input" /></div><Button className="mt-3 w-full bg-[#1B2A4A]" disabled={saving} onClick={() => act(`/api/care/cases/${caseId}/contacts`, { ...contact, next_step: contact.next_step || null, next_step_at: contact.next_step_at ? new Date(contact.next_step_at).toISOString() : null }, 'Contacto registrado')} data-testid="pastoral-contact-submit-button">Guardar contacto</Button></section>}
        {item.permissions?.write && <section className="border bg-white p-4" data-testid="pastoral-transition-panel"><h2 className="font-['Spectral'] text-xl font-semibold">Cambiar estado</h2><div className="mt-3 space-y-3"><select value={transition.status} onChange={(event) => setTransition((old) => ({ ...old, status: event.target.value }))} className="h-10 w-full border bg-white px-2 text-sm" data-testid="pastoral-transition-status-select">{Object.entries(careStatusLabel).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><Textarea value={transition.reason} onChange={(event) => setTransition((old) => ({ ...old, reason: event.target.value }))} placeholder="Motivo obligatorio" data-testid="pastoral-transition-reason-input" /><Button className="w-full" variant="outline" disabled={saving || transition.reason.trim().length < 3} onClick={() => act(`/api/care/cases/${caseId}/transition`, transition, 'Estado actualizado')} data-testid="pastoral-transition-submit-button">Actualizar estado</Button></div></section>}
        <section className="border bg-white" data-testid="pastoral-contact-history"><header className="border-b p-4"><h2 className="font-['Spectral'] text-xl font-semibold">Historial de contactos</h2></header><div className="divide-y">{(item.contacts || []).length === 0 ? <p className="p-4 text-sm text-slate-500">Sin contactos registrados.</p> : item.contacts.map((entry) => <div key={entry.contact_id} className="p-4" data-testid={`pastoral-contact-${entry.contact_id}`}><b className="text-sm capitalize">{entry.method} · {entry.outcome}</b><p className="text-xs text-slate-500">{dateTime(entry.occurred_at)}</p>{entry.next_step && <p className="mt-1 text-xs text-slate-600">Siguiente: {entry.next_step}</p>}</div>)}</div></section>
      </aside>
    </div>
  </PastoralShell>;
}