import React, { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { CalendarDays, Home, Loader2, Play, Plus, UserRound } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '../../context/AuthContext';
import { apiErrorMessage } from '../../lib/apiErrors';
import { CarePersonPicker } from '../../components/pastoral/CarePersonPicker';
import { CompleteVisitDialog } from '../../components/pastoral/CompleteVisitDialog';
import { PastoralShell } from '../../components/pastoral/PastoralShell';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';
import { Textarea } from '../../components/ui/textarea';
import { dateTime } from '../../lib/careLabels';

export default function PastoralVisitsPage() {
  const { API, getAuthHeaders, user } = useAuth(); const [items, setItems] = useState([]); const [catalog, setCatalog] = useState({ assignees: [] }); const [person, setPerson] = useState(null); const [household, setHousehold] = useState(null); const [selected, setSelected] = useState([]); const [lead, setLead] = useState(''); const [scheduledAt, setScheduledAt] = useState(''); const [purpose, setPurpose] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const canManage = user?.rol === 'pastor' || (user?.capabilities || []).includes('care.manage'); const canWriteSummary = user?.rol === 'pastor' || (user?.capabilities || []).includes('care.confidential.write');
  const load = useCallback(() => { setLoading(true); setError(''); Promise.all([axios.get(`${API}/api/care/visitations`, getAuthHeaders()), axios.get(`${API}/api/care/catalog`, getAuthHeaders())]).then(([visits, options]) => { setItems(visits.data.items || []); setCatalog(options.data); }).catch((requestError) => setError(apiErrorMessage(requestError, 'No se pudo cargar la agenda'))).finally(() => setLoading(false)); }, [API, getAuthHeaders]);
  useEffect(load, [load]);
  useEffect(() => { if (!person) { setHousehold(null); setSelected([]); return; } setSelected([person.person_id]); axios.get(`${API}/api/care/households/by-person/${person.person_id}`, getAuthHeaders()).then((response) => setHousehold(response.data)); }, [API, getAuthHeaders, person]);
  const schedule = async (event) => { event.preventDefault(); if (!person || !lead || !scheduledAt || !purpose.trim()) return; setSaving(true); try { const grouped = selected.length > 1; await axios.post(`${API}/api/care/visitations`, { household_id: grouped ? household?.household?._id || household?.household?.household_id : null, participants: selected.map((person_id) => ({ person_id })), scheduled_at: new Date(scheduledAt).toISOString(), lead_visitor_person_id: lead, visitor_person_ids: [], purpose }, getAuthHeaders()); toast.success('Visita programada con historial individual'); setPerson(null); setPurpose(''); setScheduledAt(''); await load(); } catch (requestError) { toast.error(apiErrorMessage(requestError, 'No se pudo programar la visita')); } finally { setSaving(false); } };
  const start = async (visitId) => { setSaving(true); try { await axios.post(`${API}/api/care/visitations/${visitId}/start`, {}, getAuthHeaders()); toast.success('Visita iniciada'); await load(); } catch (requestError) { toast.error(apiErrorMessage(requestError, 'No se pudo iniciar la visita')); } finally { setSaving(false); } };
  const complete = async (visitId, payload) => { setSaving(true); try { await axios.post(`${API}/api/care/visitations/${visitId}/complete`, payload, getAuthHeaders()); toast.success('Visita cerrada e historiales actualizados'); await load(); } catch (requestError) { toast.error(apiErrorMessage(requestError, 'No se pudo completar la visita')); } finally { setSaving(false); } };
  const householdId = household?.household?._id || household?.household?.household_id;
  return <PastoralShell eyebrow="Agenda de acompañamiento" title="Visitas pastorales" description="Agrupe una visita por Hogar canónico y conserve el resultado individual de cada Persona.">
    {canManage && <form onSubmit={schedule} className="mb-7 grid gap-5 border border-[#C8A951]/40 bg-white p-5 lg:grid-cols-2" data-testid="pastoral-visit-create-form"><div className="space-y-3"><label className="text-xs font-semibold uppercase text-slate-500">Persona principal</label><CarePersonPicker value={person} onChange={setPerson} testId="visit-primary-person" />{person && householdId && <div className="border bg-[#FDF9EE] p-3" data-testid="visit-household-members"><p className="flex items-center gap-2 text-sm font-semibold text-[#0B1428]"><Home className="h-4 w-4 text-[#9A7E32]" />{household.household.nombre_hogar || 'Hogar canónico'}</p><div className="mt-3 grid gap-2 sm:grid-cols-2">{(household.members || []).filter(Boolean).map((member) => <label key={member.person_id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={selected.includes(member.person_id)} onChange={(event) => setSelected((old) => event.target.checked ? [...new Set([...old, member.person_id])] : old.filter((id) => id !== member.person_id))} data-testid={`visit-member-${member.person_id}`} />{member.name}</label>)}</div></div>}</div><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold uppercase text-slate-500">Responsable<select value={lead} onChange={(event) => setLead(event.target.value)} className="mt-2 h-10 w-full border bg-white px-3 text-sm" required data-testid="visit-lead-select"><option value="">Seleccione visitante</option>{catalog.assignees.map((option) => <option key={option.person_id} value={option.person_id}>{option.name}</option>)}</select></label><label className="text-xs font-semibold uppercase text-slate-500">Fecha<Input type="datetime-local" value={scheduledAt} onChange={(event) => setScheduledAt(event.target.value)} className="mt-2" required data-testid="visit-scheduled-at-input" /></label><Textarea value={purpose} onChange={(event) => setPurpose(event.target.value)} placeholder="Propósito operativo de la visita" className="sm:col-span-2" required data-testid="visit-purpose-input" /><Button disabled={saving || !person || selected.length === 0 || !lead || !scheduledAt} className="sm:col-span-2 bg-[#C8A951] text-[#0B1428] hover:bg-[#D8BC61]" data-testid="visit-create-submit-button">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}Programar {selected.length > 1 ? 'visita de hogar' : 'visita individual'}</Button></div></form>}
    {error && <div className="border border-red-200 bg-red-50 p-4 text-sm text-red-800" data-testid="pastoral-visits-error">{error}</div>}{loading && <div className="flex justify-center py-24" data-testid="pastoral-visits-loading"><Loader2 className="h-8 w-8 animate-spin text-[#9A7E32]" /></div>}
    {!loading && !error && <section className="border bg-white" data-testid="pastoral-visits-list"><header className="flex items-center justify-between border-b p-4"><h2 className="font-['Spectral'] text-2xl font-semibold">Agenda e historial</h2><span className="text-sm text-slate-500" data-testid="pastoral-visits-total">{items.length} visita(s)</span></header>{items.length === 0 ? <div className="flex flex-col items-center py-16 text-center" data-testid="pastoral-visits-list-empty"><CalendarDays className="h-10 w-10 text-[#C8A951]" /><b className="mt-3">No hay visitas programadas</b></div> : <div className="divide-y">{items.map((visit) => <article key={visit.visit_id} className="grid gap-4 p-5 lg:grid-cols-[1.2fr_1fr_auto] lg:items-center" data-testid={`pastoral-visit-row-${visit.visit_id}`}><div><p className="flex items-center gap-2 text-xs font-semibold uppercase text-[#9A7E32]">{visit.household_id ? <Home className="h-4 w-4" /> : <UserRound className="h-4 w-4" />}{visit.household_id ? 'Visita de hogar' : 'Visita individual'}</p><b className="mt-1 block text-sm text-[#0B1428]">{visit.purpose}</b><p className="text-xs text-slate-500">{dateTime(visit.scheduled_at)} · {visit.status}</p></div><div className="flex flex-wrap gap-2">{(visit.participants || []).map((participant) => <span key={participant.person_id} className="border bg-slate-50 px-2 py-1 text-xs" data-testid={`visit-participant-${visit.visit_id}-${participant.person_id}`}>{participant.person?.name}</span>)}</div><div className="flex gap-2">{visit.status === 'scheduled' && <Button size="sm" variant="outline" disabled={saving} onClick={() => start(visit.visit_id)} data-testid={`visit-start-${visit.visit_id}`}><Play className="h-4 w-4" />Iniciar</Button>}{visit.status !== 'completed' && <CompleteVisitDialog visit={visit} saving={saving} canWriteSummary={canWriteSummary} onComplete={(payload) => complete(visit.visit_id, payload)} />}</div></article>)}</div>}</section>}
  </PastoralShell>;
}