import React, { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { ArrowRight, Award, BookOpenCheck, FileUp, Loader2 } from 'lucide-react';
import { toast } from 'sonner';

import { useAuth } from '../../context/AuthContext';
import { canAccreditHistoricalFormation, canEnrollFormation } from '../../lib/accessControl';
import { displayLabel } from '../../lib/displayLabels';
import { Badge } from '../ui/badge';
import { Button } from '../ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '../ui/dialog';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select';
import { Textarea } from '../ui/textarea';

const statusTone = { completed: 'bg-emerald-50 text-emerald-800', historical_accredited: 'bg-amber-50 text-amber-800', eligible: 'bg-sky-50 text-sky-800', in_progress: 'bg-indigo-50 text-indigo-800', remediation_required: 'bg-rose-50 text-rose-800' };

export const FormationProfileSection = ({ personId }) => {
  const { API, getAuthHeaders, user } = useAuth(); const [data, setData] = useState(null); const [cohorts, setCohorts] = useState([]); const [loading, setLoading] = useState(true);
  const [creditOpen, setCreditOpen] = useState(false); const [enrollOpen, setEnrollOpen] = useState(false); const [saving, setSaving] = useState(false);
  const [credit, setCredit] = useState({ module_id: '', historical_completion_date: '', date_precision: 'unknown', observation: '', evidence: null }); const [cohortId, setCohortId] = useState('');
  const load = useCallback(async () => { setLoading(true); try { const response = await axios.get(`${API}/api/formation/persons/${personId}/progress`, getAuthHeaders()); setData(response.data); const available = await axios.get(`${API}/api/formation/cohorts?status=open`, getAuthHeaders()); setCohorts(available.data.items || []); } catch (error) { toast.error(error?.response?.data?.detail || 'No se pudo cargar Formación'); } finally { setLoading(false); } }, [API, getAuthHeaders, personId]);
  useEffect(() => { load(); }, [load]);
  const accredit = async (event) => { event.preventDefault(); setSaving(true); try { let evidence_document_id = null; if (credit.evidence) { const body = new FormData(); body.append('purpose', 'historical_credit'); body.append('file', credit.evidence); const upload = await axios.post(`${API}/api/formation/persons/${personId}/documents`, body, { ...getAuthHeaders(), headers: { ...getAuthHeaders().headers, 'Content-Type': 'multipart/form-data' } }); evidence_document_id = upload.data.document_id; } await axios.post(`${API}/api/formation/persons/${personId}/historical-credits`, { module_id: credit.module_id, historical_completion_date: credit.historical_completion_date || null, date_precision: credit.historical_completion_date ? credit.date_precision : 'unknown', observation: credit.observation, evidence_document_id }, getAuthHeaders()); toast.success('Formación histórica acreditada'); setCreditOpen(false); await load(); } catch (error) { toast.error(error?.response?.data?.detail || 'No se pudo acreditar'); } finally { setSaving(false); } };
  const enroll = async () => { setSaving(true); try { await axios.post(`${API}/api/formation/cohorts/${cohortId}/enrollments`, { person_id: personId }, getAuthHeaders()); toast.success('Persona inscrita'); setEnrollOpen(false); await load(); } catch (error) { toast.error(error?.response?.data?.detail || 'No se pudo inscribir'); } finally { setSaving(false); } };
  if (loading) return <div className="flex min-h-40 items-center justify-center" data-testid="formation-profile-loading"><Loader2 className="h-5 w-5 animate-spin" /></div>;
  const next = data?.next_recommended; const eligibleCohorts = cohorts.filter((item) => item.module_id === next?.module_id);
  return <section className="space-y-6" data-testid="profile-formation-section">
    <header className="flex flex-col gap-4 border-b pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase text-[#B58A24]">Ruta educativa</p><h2 className="font-['Spectral'] text-3xl font-semibold text-[#101D36]">Formación / Discipulado</h2></div><div className="flex flex-wrap gap-2">
      {canAccreditHistoricalFormation(user) && <Dialog open={creditOpen} onOpenChange={setCreditOpen}><DialogTrigger asChild><Button variant="outline" data-testid="open-historical-credit-button"><Award className="h-4 w-4" />Acreditar formación histórica</Button></DialogTrigger><DialogContent data-testid="historical-credit-dialog"><DialogHeader><DialogTitle>Acreditar módulo histórico</DialogTitle></DialogHeader><form onSubmit={accredit} className="space-y-4"><div><Label>Módulo</Label><Select value={credit.module_id} onValueChange={(value) => setCredit({ ...credit, module_id: value })}><SelectTrigger data-testid="historical-credit-module-select"><SelectValue placeholder="Seleccione módulo" /></SelectTrigger><SelectContent className="bg-white">{(data?.items || []).filter((item) => !['completed','historical_accredited'].includes(item.status)).map((item) => <SelectItem key={item.module_id} value={item.module_id}>{item.program_name} · {item.module_name}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-3 sm:grid-cols-2"><div><Label>Fecha conocida</Label><Input type="date" value={credit.historical_completion_date} onChange={(event) => setCredit({ ...credit, historical_completion_date: event.target.value })} data-testid="historical-credit-date-input" /></div><div><Label>Precisión</Label><Select value={credit.date_precision} onValueChange={(value) => setCredit({ ...credit, date_precision: value })} disabled={!credit.historical_completion_date}><SelectTrigger data-testid="historical-credit-precision-select"><SelectValue /></SelectTrigger><SelectContent className="bg-white"><SelectItem value="exact">Exacta</SelectItem><SelectItem value="month">Mes</SelectItem><SelectItem value="year">Año</SelectItem><SelectItem value="unknown">Desconocida</SelectItem></SelectContent></Select></div></div><div><Label>Observación</Label><Textarea required value={credit.observation} onChange={(event) => setCredit({ ...credit, observation: event.target.value })} data-testid="historical-credit-observation-input" /></div><div><Label>Evidencia opcional</Label><Input type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.docx" onChange={(event) => setCredit({ ...credit, evidence: event.target.files?.[0] })} data-testid="historical-credit-evidence-input" /></div><Button className="w-full" disabled={saving || !credit.module_id} data-testid="confirm-historical-credit-button">{saving && <Loader2 className="h-4 w-4 animate-spin" />}Acreditar</Button></form></DialogContent></Dialog>}
      {next && canEnrollFormation(user) && <Dialog open={enrollOpen} onOpenChange={setEnrollOpen}><DialogTrigger asChild><Button data-testid="open-next-module-enrollment-button"><ArrowRight className="h-4 w-4" />Inscribir en próximo módulo</Button></DialogTrigger><DialogContent data-testid="next-module-enrollment-dialog"><DialogHeader><DialogTitle>{next.module_name_snapshot || next.name}</DialogTitle></DialogHeader><div className="space-y-4"><Select value={cohortId} onValueChange={setCohortId}><SelectTrigger data-testid="next-cohort-select"><SelectValue placeholder="Seleccione cohorte abierta" /></SelectTrigger><SelectContent className="bg-white">{eligibleCohorts.map((item) => <SelectItem key={item.cohort_id} value={item.cohort_id}>{item.name} · {item.start_date}</SelectItem>)}</SelectContent></Select><Button className="w-full" disabled={!cohortId || saving} onClick={enroll} data-testid="confirm-next-module-enrollment-button">Confirmar inscripción</Button></div></DialogContent></Dialog>}
    </div></header>
    {next && <div className="border-l-4 border-[#B58A24] bg-[#FBF7EA] p-4" data-testid="formation-next-step"><p className="text-xs font-semibold uppercase text-[#785E24]">Próximo paso recomendado</p><p className="mt-1 font-semibold text-[#101D36]">{next.program_name_snapshot || next.program_name} · {next.module_name_snapshot || next.name}</p></div>}
    <div className="border" data-testid="formation-progress-table"><div className="space-y-3 p-3 sm:hidden">{(data?.items || []).map((item) => <article key={item.module_id} className="border-l-4 border-[#0879BE] bg-slate-50 p-3" data-testid={`formation-progress-mobile-${item.module_id}`}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs text-slate-500">{item.program_name}</p><p className="break-words font-semibold text-[#101D36]">{item.module_name}</p></div><Badge className={statusTone[item.status] || 'bg-slate-100 text-slate-700'}>{displayLabel(item.status)}</Badge></div><dl className="mt-3 grid grid-cols-2 gap-2 text-xs"><div><dt className="text-slate-500">Cohorte</dt><dd>{item.cohort_name || '—'}</dd></div><div><dt className="text-slate-500">Asistencia</dt><dd>{item.attendance_pct == null ? '—' : `${item.attendance_pct}%`}</dd></div><div><dt className="text-slate-500">Nota</dt><dd>{item.final_grade_pct == null ? '—' : `${item.final_grade_pct}%`}</dd></div><div><dt className="text-slate-500">Fecha</dt><dd>{item.completed_at?.slice?.(0,10) || '—'}</dd></div></dl></article>)}</div><table className="hidden w-full text-left text-sm sm:table"><thead className="bg-[#101D36] text-white"><tr>{['Programa','Módulo','Estado','Cohorte','Asistencia','Nota','Fecha'].map((label) => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{(data?.items || []).map((item) => <tr key={item.module_id} className="border-t"><td className="px-4 py-3">{item.program_name}</td><td className="px-4 py-3 font-medium">{item.module_name}</td><td className="px-4 py-3"><Badge className={statusTone[item.status] || 'bg-slate-100 text-slate-700'}>{displayLabel(item.status)}</Badge></td><td className="px-4 py-3">{item.cohort_name || '—'}</td><td className="px-4 py-3">{item.attendance_pct == null ? '—' : `${item.attendance_pct}%`}</td><td className="px-4 py-3">{item.final_grade_pct == null ? '—' : `${item.final_grade_pct}%`}</td><td className="px-4 py-3">{item.completed_at?.slice?.(0,10) || '—'}</td></tr>)}</tbody></table></div>
    {(data?.legacy_discipleship || []).length > 0 && <div className="border border-dashed p-4" data-testid="legacy-discipleship-history"><div className="flex gap-2"><BookOpenCheck className="h-5 w-5 text-slate-500" /><div><p className="font-semibold">Discipulado legado · solo lectura</p><p className="text-sm text-slate-500">No se convierte automáticamente en módulos completados. Use acreditación histórica cuando exista evidencia.</p></div></div></div>}
  </section>;
};