import React, { useCallback, useEffect, useMemo, useState } from 'react';
import axios from 'axios';
import { GitBranch, Loader2, Network, ShieldCheck } from 'lucide-react';

import { useAuth } from '../context/AuthContext';
import { FrontGroupDetailPanel } from '../components/front-groups/FrontGroupDetailPanel';
import { FrontGroupDialog } from '../components/front-groups/FrontGroupDialog';
import { FrontGroupTreeNav } from '../components/front-groups/FrontGroupTreeNav';
import { isPastoralAuthority } from '../lib/accessControl';
import { apiErrorMessage } from '../lib/apiErrors';

const flattenTree = (nodes) => nodes.flatMap((node) => [{ ...node, children: undefined }, ...flattenTree(node.children || [])]);

export default function FrontGroupsPage() {
  const { API, getAuthHeaders, user } = useAuth(); const [tree, setTree] = useState([]); const [selected, setSelected] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const groups = useMemo(() => flattenTree(tree), [tree]);
  const load = useCallback(async (created) => { setLoading(true); setError(''); try { const response = await axios.get(`${API}/api/front-groups/tree`, getAuthHeaders()); const items = response.data.items || []; setTree(items); const flat = flattenTree(items); setSelected((current) => flat.find((item) => item.front_group_id === (created?.front_group_id || current?.front_group_id)) || flat[0] || null); } catch (requestError) { setError(apiErrorMessage(requestError, 'No se pudo cargar el árbol frontal')); } finally { setLoading(false); } }, [API, getAuthHeaders]);
  useEffect(() => { load(); }, [load]);
  return <main className="min-h-full bg-[#F8FAFC]" data-testid="front-groups-page"><header className="border-b border-slate-800 bg-slate-950 px-4 py-8 text-white sm:px-8"><div className="mx-auto flex max-w-[1500px] flex-wrap items-end justify-between gap-6"><div><p className="font-mono text-xs uppercase text-amber-400">Liderazgo · Cobertura · Ejecución</p><h1 className="mt-2 font-['Spectral'] text-4xl font-semibold sm:text-5xl">Grupos Frontales</h1><p className="mt-3 max-w-3xl text-sm text-slate-300">Árbol humano recursivo para distribuir trabajo hacia cada rama y consolidar resultados hasta la Pastora.</p></div>{isPastoralAuthority(user) && groups.length > 0 && <FrontGroupDialog groups={groups} root onCreated={load} />}</div></header>
    {loading ? <div className="grid min-h-[55vh] place-items-center" data-testid="front-groups-loading"><Loader2 className="h-8 w-8 animate-spin text-amber-700" /></div> : error ? <div className="mx-auto mt-8 max-w-4xl border border-red-200 bg-red-50 p-5 text-red-700" data-testid="front-group-error-alert">{error}</div> : !groups.length ? <section className="mx-auto grid min-h-[58vh] max-w-3xl place-items-center px-5 text-center" data-testid="front-groups-empty-state"><div><div className="mx-auto grid h-16 w-16 place-items-center border border-amber-300 bg-amber-50"><GitBranch className="h-7 w-7 text-amber-700" /></div><h2 className="mt-6 font-['Spectral'] text-3xl font-semibold">El árbol real comienza limpio</h2><p className="mx-auto mt-3 max-w-xl text-sm text-slate-600">Los residuos QA fueron archivados con trazabilidad. Cree el primer Grupo Frontal seleccionando una Persona 360 real como líder.</p><div className="mt-6 flex justify-center">{isPastoralAuthority(user) ? <FrontGroupDialog groups={[]} root onCreated={load} /> : <span className="inline-flex items-center gap-2 border border-slate-200 bg-white px-4 py-3 text-sm text-slate-600"><ShieldCheck className="h-4 w-4" />La Pastora iniciará la estructura raíz.</span>}</div></div></section> : <div className="mx-auto grid max-w-[1500px] gap-6 px-4 py-6 sm:px-8 lg:grid-cols-[340px_minmax(0,1fr)]"><FrontGroupTreeNav tree={tree} selectedId={selected?.front_group_id} onSelect={setSelected} /><section className="min-w-0 border border-slate-200 bg-white p-5 sm:p-7" data-testid="front-group-workspace">{selected ? <FrontGroupDetailPanel group={selected} groups={groups} onUpdated={load} /> : <div className="grid min-h-64 place-items-center text-sm text-slate-500"><Network className="h-6 w-6" />Seleccione una rama.</div>}</section></div>}
  </main>;
}