import React, { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { CalendarDays, MapPin, RadioTower, ShieldCheck, UsersRound } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { CellDetailActions } from '../../components/cellular/CellDetailActions';
import { CellularError, CellularLoading, CellularShell, EmptyState } from '../../components/cellular/CellularShell';
import { displayLabel, statusLabel } from '../../lib/displayLabels';

export default function CellularDetailPage() {
  const { id } = useParams(); const { API, getAuthHeaders, user } = useAuth(); const [cell, setCell] = useState(null); const [catalog, setCatalog] = useState({}); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { try { const [detail, cat] = await Promise.all([axios.get(`${API}/api/cellular/cells/${id}`, getAuthHeaders()), axios.get(`${API}/api/cellular/catalog`, getAuthHeaders())]); setCell(detail.data); setCatalog(cat.data); } catch (requestError) { setError(requestError?.response?.data?.detail || 'No se pudo cargar la célula.'); } finally { setLoading(false); } }, [API, getAuthHeaders, id]);
  useEffect(() => { load(); }, [load]);
  if (loading) return <CellularShell title="Perfil de célula" description="Cargando perfil..." guideKey="cellular_cells"><CellularLoading /></CellularShell>;
  return <CellularShell title={cell?.name || 'Perfil de célula'} description={`${cell?.code || ''} · ${cell?.network_name || ''}`} guideKey="cellular_cells" actions={cell && user?.rol !== 'persona' ? <CellDetailActions cell={cell} catalog={catalog} onSaved={load} /> : null}>{error ? <CellularError message={error} /> : <>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="border bg-white p-4"><UsersRound className="h-5 w-5 text-[#9E8232]" /><b className="mt-2 block text-2xl" data-testid="cell-detail-active-members">{cell.metrics.active_members}</b><span className="text-xs text-[#718096]">Miembros activos</span></div><div className="border bg-white p-4"><CalendarDays className="h-5 w-5 text-[#9E8232]" /><b className="mt-2 block text-2xl">{cell.metrics.meetings_count}</b><span className="text-xs text-[#718096]">Reuniones recientes</span></div><div className="border bg-white p-4"><RadioTower className="h-5 w-5 text-[#9E8232]" /><b className="mt-2 block text-2xl">{cell.metrics.average_attendance}</b><span className="text-xs text-[#718096]">Promedio de asistencia</span></div><div className="border bg-white p-4"><ShieldCheck className="h-5 w-5 text-[#9E8232]" /><b className="mt-2 block text-2xl">{cell.metrics.open_needs}</b><span className="text-xs text-[#718096]">Necesidades abiertas</span></div></section>
    <section className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><div className="space-y-5"><div className="border border-[#E2D9CC] bg-white p-5"><h2 className="text-lg font-semibold">Información</h2><p className="mt-3 flex gap-2 text-sm"><MapPin className="h-4 w-4" />{cell.address}</p><p className="mt-2 text-sm">{cell.meeting_day} · {cell.meeting_time} · capacidad {cell.capacity}</p></div><div className="border border-[#E2D9CC] bg-white p-5"><h2 className="text-lg font-semibold">Equipo celular</h2><div className="mt-3 space-y-2">{cell.roles.length ? cell.roles.map((role) => <div key={role.role_assignment_id} className="flex justify-between border-b pb-2 text-sm" data-testid={`cell-role-${role.role_assignment_id}`}><span>{role.person?.name}</span><span className="text-[#9E8232]">{displayLabel(role.role)}</span></div>) : <p className="text-sm text-[#718096]">Sin funciones asignadas.</p>}</div></div></div><div className="space-y-5"><div className="border border-[#E2D9CC] bg-white p-5"><h2 className="text-lg font-semibold">Membresías e historial</h2><div className="mt-3 space-y-2">{cell.memberships.length ? cell.memberships.map((member) => <div key={member.membership_id} className="flex flex-col gap-1 border-b pb-3 text-sm sm:flex-row sm:items-center sm:justify-between" data-testid={`cell-membership-${member.membership_id}`}><div><Link to={member.person?.profile_path || '#'} className="font-medium text-[#0F1A33]">{member.person?.name}</Link><p className="text-xs text-[#718096]">Ingreso {member.joined_at} · {displayLabel(member.membership_type, 'Miembro')}</p></div><span className={member.active ? 'text-green-700' : 'text-[#718096]'}>{member.active ? 'Activa' : `Finalizada · ${member.left_at || ''}`}</span></div>) : <EmptyState testId="cell-memberships-empty">Sin membresías registradas.</EmptyState>}</div></div><div className="border border-[#E2D9CC] bg-white p-5"><h2 className="text-lg font-semibold">Reuniones</h2><div className="mt-3 space-y-2">{cell.meetings.length ? cell.meetings.map((meeting) => <Link key={meeting.meeting_id} to={`/celulas/${cell.cell_id}/reunion-movil?meeting=${meeting.meeting_id}`} className="flex items-center justify-between border p-3 text-sm hover:border-[#C8A951]" data-testid={`cell-meeting-${meeting.meeting_id}`}><span><b className="block">{meeting.topic}</b>{new Date(meeting.scheduled_at).toLocaleString('es')}</span><span>{statusLabel(meeting.status)}</span></Link>) : <EmptyState testId="cell-meetings-empty">Aún no hay reuniones.</EmptyState>}</div></div></div></section>
  </>}</CellularShell>;
}