import React, { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { Network, Plus, ShieldCheck } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '../../context/AuthContext';
import { PersonSelect } from '../../components/cellular/CellularFields';
import { CellularError, CellularLoading, CellularShell, EmptyState } from '../../components/cellular/CellularShell';
import { Button } from '../../components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '../../components/ui/dialog';
import { Input } from '../../components/ui/input';
import { Label } from '../../components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../../components/ui/select';
import { Textarea } from '../../components/ui/textarea';
import { displayLabel } from '../../lib/displayLabels';

export default function CellularNetworksPage() {
  const { API, getAuthHeaders, user } = useAuth(); const [items, setItems] = useState([]); const [catalog, setCatalog] = useState({ staff: [] }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [open, setOpen] = useState(false); const [form, setForm] = useState({ name: '', description: '' }); const [assignment, setAssignment] = useState({ network_id: '', person_id: '', role: 'supervisor' });
  const load = useCallback(async () => { try { const [networks, cat] = await Promise.all([axios.get(`${API}/api/cellular/networks`, getAuthHeaders()), axios.get(`${API}/api/cellular/catalog`, getAuthHeaders())]); setItems(networks.data.items || []); setCatalog(cat.data); } catch (requestError) { setError(requestError?.response?.data?.detail || 'No se pudieron cargar las redes.'); } finally { setLoading(false); } }, [API, getAuthHeaders]);
  useEffect(() => { load(); }, [load]);
  const create = async (event) => { event.preventDefault(); try { await axios.post(`${API}/api/cellular/networks`, { ...form, description: form.description || null, status: 'active' }, getAuthHeaders()); toast.success('Red creada'); setOpen(false); await load(); } catch (requestError) { toast.error(requestError?.response?.data?.detail || 'No se pudo crear la red'); } };
  const assign = async () => { try { await axios.post(`${API}/api/cellular/networks/${assignment.network_id}/assignments`, { person_id: assignment.person_id, role: assignment.role }, getAuthHeaders()); toast.success('Responsabilidad asignada'); setAssignment({ network_id: '', person_id: '', role: 'supervisor' }); await load(); } catch (requestError) { toast.error(requestError?.response?.data?.detail || 'No se pudo asignar'); } };
  if (loading) return <CellularShell title="Redes celulares" description="Cargando redes..." guideKey="cellular_networks"><CellularLoading /></CellularShell>;
  const action = user?.rol === 'pastor' ? <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="bg-[#C8A951] text-[#0F1A33]" data-testid="open-create-network-button"><Plus className="mr-2 h-4 w-4" />Nueva red</Button></DialogTrigger><DialogContent className="bg-white"><DialogHeader><DialogTitle>Nueva red celular</DialogTitle><DialogDescription>Organiza células y supervisión sin crear identidades alternas.</DialogDescription></DialogHeader><form onSubmit={create} className="space-y-4"><div><Label htmlFor="network-name">Nombre</Label><Input id="network-name" value={form.name} onChange={(event) => setForm((old) => ({ ...old, name: event.target.value }))} required data-testid="network-name-input" /></div><div><Label htmlFor="network-description">Descripción</Label><Textarea id="network-description" value={form.description} onChange={(event) => setForm((old) => ({ ...old, description: event.target.value }))} data-testid="network-description-input" /></div><Button type="submit" className="w-full bg-[#0F1A33]" data-testid="create-network-submit-button">Crear red</Button></form></DialogContent></Dialog> : null;
  return <CellularShell title="Redes celulares" description="Gobierno por redes, directores y supervisores con asignaciones históricas." guideKey="cellular_networks" actions={action}>{error ? <CellularError message={error} /> : <><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{items.length ? items.map((network) => <article key={network.network_id} className="border border-[#E2D9CC] bg-white p-5 shadow-sm" data-testid={`network-card-${network.network_id}`}><Network className="h-6 w-6 text-[#9E8232]" /><h2 className="mt-3 text-xl font-semibold text-[#0F1A33]">{network.name}</h2><p className="mt-1 text-sm text-[#718096]">{network.description || 'Sin descripción operativa.'}</p><div className="mt-4 flex gap-5 text-sm"><span><b className="block text-xl">{network.cell_count}</b>Células</span><span><b className="block text-xl">{network.member_count}</b>Miembros</span></div><div className="mt-4 border-t pt-3">{network.assignments?.length ? network.assignments.map((item) => <p key={item.assignment_id} className="flex items-center gap-2 text-xs text-[#4A5568]"><ShieldCheck className="h-3 w-3" />{item.person?.name} · {displayLabel(item.role)}</p>) : <p className="text-xs text-amber-700">Sin supervisión asignada</p>}</div></article>) : <EmptyState testId="networks-empty">Aún no hay redes disponibles.</EmptyState>}</section>{user?.rol === 'pastor' && <section className="border border-[#E2D9CC] bg-white p-5"><h2 className="text-lg font-semibold">Asignar gobierno de red</h2><div className="mt-4 grid gap-3 md:grid-cols-4 md:items-end"><div><Label>Red</Label><Select value={assignment.network_id} onValueChange={(value) => setAssignment((old) => ({ ...old, network_id: value }))}><SelectTrigger data-testid="network-assignment-network-select"><SelectValue placeholder="Red" /></SelectTrigger><SelectContent className="bg-white">{items.map((item) => <SelectItem key={item.network_id} value={item.network_id}>{item.name}</SelectItem>)}</SelectContent></Select></div><PersonSelect id="network-assignment-person-select" label="Persona" items={catalog.staff || []} value={assignment.person_id} onChange={(value) => setAssignment((old) => ({ ...old, person_id: value }))} /><div><Label>Función</Label><Select value={assignment.role} onValueChange={(value) => setAssignment((old) => ({ ...old, role: value }))}><SelectTrigger data-testid="network-assignment-role-select"><SelectValue /></SelectTrigger><SelectContent className="bg-white"><SelectItem value="general_coordinator">Coordinador general</SelectItem><SelectItem value="network_director">Director de red</SelectItem><SelectItem value="supervisor">Supervisor</SelectItem></SelectContent></Select></div><Button onClick={assign} disabled={!assignment.network_id || !assignment.person_id} data-testid="network-assignment-submit-button">Asignar</Button></div></section>}</>}</CellularShell>;
}