import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { Link2, Loader2 } from 'lucide-react';
import { toast } from 'sonner';

import { useAuth } from '../../context/AuthContext';
import { apiErrorMessage } from '../../lib/apiErrors';
import { Button } from '../ui/button';
import { Label } from '../ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select';
import { Textarea } from '../ui/textarea';

export const FrontGroupCellLinkPanel = ({ group, canConfigure }) => {
  const { API, getAuthHeaders } = useAuth(); const [cells, setCells] = useState([]); const [cellId, setCellId] = useState(''); const [routeConversions, setRouteConversions] = useState(false); const [reason, setReason] = useState('Vinculación operativa aprobada'); const [saving, setSaving] = useState(false); const [history, setHistory] = useState([]);
  useEffect(() => { if (!canConfigure) return; axios.get(`${API}/api/cellular/cells`, getAuthHeaders()).then((response) => setCells(response.data.items || [])).catch(() => setCells([])); }, [API, canConfigure, getAuthHeaders]);
  useEffect(() => { if (!cellId) { setHistory([]); return; } axios.get(`${API}/api/front-group-routing/cell-links/${cellId}`, getAuthHeaders()).then((response) => setHistory(response.data.items || [])).catch(() => setHistory([])); }, [API, cellId, getAuthHeaders]);
  const save = async () => { setSaving(true); try { await axios.put(`${API}/api/front-group-routing/cell-links/${cellId}`, { front_group_id: group.front_group_id, route_conversions: routeConversions, reason }, getAuthHeaders()); toast.success('Vínculo Célula ↔ Grupo guardado'); const response = await axios.get(`${API}/api/front-group-routing/cell-links/${cellId}`, getAuthHeaders()); setHistory(response.data.items || []); } catch (error) { toast.error(apiErrorMessage(error, 'No se pudo guardar el vínculo')); } finally { setSaving(false); } };
  if (!canConfigure) return <div className="border border-slate-200 bg-white p-8 text-center text-sm text-slate-500" data-testid="front-group-cell-link-restricted"><Link2 className="mx-auto mb-2 h-6 w-6" />La configuración Célula ↔ Grupo está reservada a la autoridad de enrutamiento.</div>;
  return <div className="grid gap-6 xl:grid-cols-[380px_1fr]" data-testid="front-group-cell-link-panel"><section className="space-y-4 border border-slate-200 bg-white p-5"><h3 className="font-['Spectral'] text-xl font-semibold">Vincular Célula</h3><div><Label>Célula de origen</Label><Select value={cellId} onValueChange={setCellId}><SelectTrigger data-testid="front-group-cell-link-select"><SelectValue placeholder="Seleccionar Célula" /></SelectTrigger><SelectContent className="bg-white">{cells.map((cell) => <SelectItem key={cell.cell_id} value={cell.cell_id}>{cell.name || cell.cell_name || cell.cell_id}</SelectItem>)}</SelectContent></Select></div><label className="flex items-start gap-3 border border-slate-200 p-3 text-sm" data-testid="front-group-cell-route-policy"><input type="checkbox" checked={routeConversions} onChange={(event) => setRouteConversions(event.target.checked)} className="mt-1" data-testid="front-group-cell-route-checkbox" /><span><b className="block">Conservar conversiones en este Grupo</b><small className="text-slate-500">La Célula de origen siempre se conserva, aunque esta política esté desactivada.</small></span></label><div><Label htmlFor="fg-cell-reason">Motivo</Label><Textarea id="fg-cell-reason" value={reason} onChange={(event) => setReason(event.target.value)} data-testid="front-group-cell-link-reason-input" /></div><Button onClick={save} disabled={saving || !cellId || reason.trim().length < 3} className="w-full bg-slate-900" data-testid="front-group-cell-link-save-button">{saving && <Loader2 className="h-4 w-4 animate-spin" />}Guardar vínculo</Button></section><section className="border border-slate-200 bg-white"><header className="border-b border-slate-200 px-5 py-4"><h3 className="font-['Spectral'] text-xl font-semibold">Historial del vínculo</h3></header>{history.length ? <div className="divide-y divide-slate-200">{history.map((item) => <div key={item.link_id} className="px-5 py-4 text-sm" data-testid={`front-group-cell-link-history-${item.link_id}`}><b>{item.active ? 'Vínculo activo' : 'Vínculo histórico'}</b><span className="block text-slate-500">Grupo: {item.front_group_id} · Enrutamiento: {item.route_conversions ? 'Sí' : 'No'}</span><span className="block text-xs text-slate-400">{item.reason}</span></div>)}</div> : <p className="p-8 text-center text-sm text-slate-500">Seleccione una Célula para consultar su historial.</p>}</section></div>;
};