import React, { useState } from 'react';
import axios from 'axios';
import { BadgeCheck, Loader2, UserCog } from 'lucide-react';
import { toast } from 'sonner';

import { useAuth } from '../../context/AuthContext';
import { apiErrorMessage } from '../../lib/apiErrors';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select';

export const FrontGroupTeamPanel = ({ group, assignments, people, canManage, onChanged }) => {
  const { API, getAuthHeaders } = useAuth(); const [personId, setPersonId] = useState(''); const [role, setRole] = useState('member'); const [reason, setReason] = useState('Asignación estructural'); const [busy, setBusy] = useState(false);
  const submit = async () => { setBusy(true); try { const endpoint = role === 'leader' ? `${API}/api/front-groups/${group.front_group_id}/leader` : `${API}/api/front-groups/${group.front_group_id}/members`; const payload = role === 'leader' ? { person_id: personId, reason } : { person_id: personId, role, notes: reason }; await axios.post(endpoint, payload, getAuthHeaders()); toast.success('Estructura actualizada'); setPersonId(''); await onChanged(); } catch (error) { toast.error(apiErrorMessage(error, 'No se pudo actualizar el equipo')); } finally { setBusy(false); } };
  return <div className="grid gap-6 xl:grid-cols-[1fr_360px]" data-testid="front-group-team-panel"><section className="border border-slate-200 bg-white"><header className="border-b border-slate-200 px-5 py-4"><h3 className="font-['Spectral'] text-xl font-semibold">Equipo e historial</h3></header>{assignments.length ? <div className="divide-y divide-slate-200">{assignments.map((item) => <div key={item.assignment_id} className="flex flex-wrap items-center justify-between gap-3 px-5 py-4" data-testid={`front-group-assignment-${item.assignment_id}`}><div><b>{item.person_name || item.person_id}</b><span className="block text-xs text-slate-500">{item.role === 'leader' ? 'Liderazgo de rama' : item.role === 'member' ? 'Miembro' : 'Mentoría'} · {item.notes || 'Sin nota'}</span></div><span className={`border px-2 py-1 text-[10px] uppercase ${item.active ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : 'border-slate-200 bg-slate-50 text-slate-600'}`}>{item.active ? 'Activo' : 'Histórico'}</span></div>)}</div> : <p className="p-8 text-center text-sm text-slate-500">No hay asignaciones.</p>}</section>
    {canManage && <section className="space-y-4 border border-slate-200 bg-white p-5" data-testid="front-group-team-assignment-form"><h3 className="flex items-center gap-2 font-['Spectral'] text-xl font-semibold"><UserCog className="h-5 w-5 text-amber-700" />Asignar Persona</h3><div><Label>Persona 360</Label><Select value={personId} onValueChange={setPersonId}><SelectTrigger data-testid="front-group-person-select"><SelectValue placeholder="Seleccionar Persona" /></SelectTrigger><SelectContent className="max-h-72 bg-white">{people.map((person) => <SelectItem key={person.person_id} value={person.person_id}>{person.nombre} {person.apellido}</SelectItem>)}</SelectContent></Select></div><div><Label>Responsabilidad</Label><Select value={role} onValueChange={setRole}><SelectTrigger data-testid="front-group-role-select"><SelectValue /></SelectTrigger><SelectContent className="bg-white"><SelectItem value="member">Miembro</SelectItem><SelectItem value="mentor">Mentor</SelectItem><SelectItem value="leader">Líder principal</SelectItem></SelectContent></Select></div><div><Label htmlFor="fg-team-reason">Motivo</Label><Input id="fg-team-reason" value={reason} onChange={(event) => setReason(event.target.value)} data-testid="front-group-assignment-reason-input" /></div><Button onClick={submit} disabled={busy || !personId || reason.trim().length < 2} className="w-full bg-slate-900" data-testid="front-group-assign-button">{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <BadgeCheck className="h-4 w-4" />}Asignar</Button></section>}
  </div>;
};