import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { GitBranchPlus, Loader2, Plus } from 'lucide-react';
import { toast } from 'sonner';

import { useAuth } from '../../context/AuthContext';
import { apiErrorMessage } from '../../lib/apiErrors';
import { Button } from '../ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '../ui/dialog';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select';
import { Textarea } from '../ui/textarea';

export const FrontGroupDialog = ({ groups = [], parentGroup = null, onCreated, root = false }) => {
  const { API, getAuthHeaders } = useAuth(); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [people, setPeople] = useState([]);
  const [form, setForm] = useState({ name: '', description: '', parent_group_id: parentGroup?.front_group_id || '', primary_leader_person_id: '', leadership_reason: 'Responsabilidad inicial de la rama' });
  useEffect(() => { if (!open) return; axios.get(`${API}/api/core/persons?limit=100`, getAuthHeaders()).then((response) => setPeople(response.data.items || [])).catch(() => setPeople([])); }, [API, getAuthHeaders, open]);
  useEffect(() => setForm((current) => ({ ...current, parent_group_id: parentGroup?.front_group_id || '' })), [parentGroup]);
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { const response = await axios.post(`${API}/api/front-groups`, { ...form, parent_group_id: form.parent_group_id || null, description: form.description || null }, getAuthHeaders()); toast.success(root ? 'Grupo raíz creado' : 'Subrama creada'); setOpen(false); setForm({ name: '', description: '', parent_group_id: parentGroup?.front_group_id || '', primary_leader_person_id: '', leadership_reason: 'Responsabilidad inicial de la rama' }); await onCreated(response.data); } catch (error) { toast.error(apiErrorMessage(error, 'No se pudo crear el Grupo Frontal')); } finally { setSaving(false); } };
  const buttonId = root ? 'front-group-create-root-button' : `front-group-create-child-${parentGroup?.front_group_id || 'selected'}`;
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className={root ? 'bg-amber-600 text-white hover:bg-amber-700' : ''} variant={root ? 'default' : 'outline'} data-testid={buttonId}>{root ? <Plus className="h-4 w-4" /> : <GitBranchPlus className="h-4 w-4" />}{root ? 'Nuevo grupo raíz' : 'Crear subrama'}</Button></DialogTrigger><DialogContent className="max-h-[90vh] max-w-xl overflow-y-auto bg-white" data-testid="front-group-dialog"><DialogHeader><DialogTitle>{root ? 'Crear Grupo Frontal raíz' : 'Crear subrama'}</DialogTitle><DialogDescription>La nueva estructura conserva una Persona 360 como líder principal y puede crecer sin límite de niveles.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><div><Label htmlFor="front-group-name">Nombre</Label><Input id="front-group-name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} data-testid="front-group-name-input" /></div>{!parentGroup && !root && <div><Label>Grupo padre</Label><Select value={form.parent_group_id || 'none'} onValueChange={(value) => setForm({ ...form, parent_group_id: value === 'none' ? '' : value })}><SelectTrigger data-testid="front-group-parent-select"><SelectValue /></SelectTrigger><SelectContent className="bg-white"><SelectItem value="none">Sin padre</SelectItem>{groups.map((item) => <SelectItem key={item.front_group_id} value={item.front_group_id}>{item.name}</SelectItem>)}</SelectContent></Select></div>}<div><Label>Líder principal</Label><Select value={form.primary_leader_person_id} onValueChange={(value) => setForm({ ...form, primary_leader_person_id: value })}><SelectTrigger data-testid="front-group-primary-leader-select"><SelectValue placeholder="Seleccionar Persona 360" /></SelectTrigger><SelectContent className="max-h-72 bg-white">{people.map((person) => <SelectItem key={person.person_id} value={person.person_id}>{person.nombre} {person.apellido}</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor="front-group-description">Descripción</Label><Textarea id="front-group-description" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} data-testid="front-group-description-input" /></div><div><Label htmlFor="front-group-leadership-reason">Motivo del liderazgo</Label><Input id="front-group-leadership-reason" value={form.leadership_reason} onChange={(event) => setForm({ ...form, leadership_reason: event.target.value })} data-testid="front-group-leadership-reason-input" /></div><Button type="submit" className="w-full bg-slate-900" disabled={saving || form.name.trim().length < 2 || !form.primary_leader_person_id} data-testid="front-group-submit-button">{saving && <Loader2 className="h-4 w-4 animate-spin" />}Crear Grupo Frontal</Button></form></DialogContent></Dialog>;
};