import React, { useMemo, useState } from 'react';
import axios from 'axios';
import { ArrowDownRight, CheckCircle2, Clock3, Loader2 } from 'lucide-react';
import { toast } from 'sonner';

import { useAuth } from '../../context/AuthContext';
import { apiErrorMessage } from '../../lib/apiErrors';
import { Button } from '../ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '../ui/dialog';
import { Label } from '../ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select';
import { Textarea } from '../ui/textarea';
import { FrontGroupTaskDialog } from './FrontGroupTaskDialog';

export const FrontGroupWorkPanel = ({ group, work, groups, assignments, canManage, onChanged }) => {
  const { API, getAuthHeaders } = useAuth(); const [selected, setSelected] = useState(null); const [saving, setSaving] = useState(false);
  const [targetGroupId, setTargetGroupId] = useState(group.front_group_id); const [personId, setPersonId] = useState('none'); const [reason, setReason] = useState('Delegación operativa a la siguiente responsabilidad');
  const targets = useMemo(() => groups.filter((item) => item.front_group_id === group.front_group_id || (item.ancestor_group_ids || []).includes(group.front_group_id)), [group.front_group_id, groups]);
  const people = assignments.filter((item) => item.active && item.front_group_id === targetGroupId);
  const delegate = async () => { setSaving(true); try { await axios.post(`${API}/api/front-group-work/${selected.assignment_id}/delegate`, { assigned_group_id: targetGroupId, assigned_person_id: personId === 'none' ? null : personId, reason }, getAuthHeaders()); toast.success('Trabajo delegado'); setSelected(null); await onChanged(); } catch (error) { toast.error(apiErrorMessage(error, 'No se pudo delegar el trabajo')); } finally { setSaving(false); } };
  return <section className="space-y-4" data-testid="front-group-work-inbox"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-['Spectral'] text-xl font-semibold">Bandeja de trabajo</h3><p className="text-sm text-slate-500">Asignaciones activas de esta rama y sus subramas.</p></div>{canManage && <FrontGroupTaskDialog group={group} onCreated={onChanged} />}</div>
    <div className="border border-slate-200 bg-white">{work.length ? <div className="divide-y divide-slate-200">{work.map((item) => <article key={item.assignment_id} className="grid gap-3 p-4 md:grid-cols-[1fr_auto]" data-testid={`front-group-work-item-${item.assignment_id}`}><div><div className="flex flex-wrap items-center gap-2"><b>{item.title}</b><span className="border border-slate-200 bg-slate-50 px-2 py-0.5 text-[10px] uppercase text-slate-600" data-testid={`front-group-work-status-${item.assignment_id}`}>{item.status}</span></div><p className="mt-1 text-sm text-slate-600">{item.description || 'Sin detalle adicional'}</p><span className="mt-2 block text-xs text-slate-500"><Clock3 className="mr-1 inline h-3 w-3" />{item.assigned_group_name}{item.assigned_person_name ? ` · ${item.assigned_person_name}` : ''}</span></div>{canManage && item.active && <Button variant="outline" onClick={() => { setSelected(item); setTargetGroupId(item.assigned_group_id); setPersonId('none'); }} data-testid={`front-group-work-delegate-${item.assignment_id}`}><ArrowDownRight className="h-4 w-4" />Delegar</Button>}</article>)}</div> : <div className="p-10 text-center text-sm text-slate-500" data-testid="front-group-work-empty"><CheckCircle2 className="mx-auto mb-2 h-6 w-6 text-emerald-600" />No hay trabajo activo en esta rama.</div>}</div>
    <Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><DialogContent className="bg-white" data-testid="front-group-delegate-dialog"><DialogHeader><DialogTitle>Delegar trabajo</DialogTitle><DialogDescription>El trabajo solo puede bajar a esta rama o a una subrama.</DialogDescription></DialogHeader><div className="space-y-4"><div><Label>Grupo destino</Label><Select value={targetGroupId} onValueChange={(value) => { setTargetGroupId(value); setPersonId('none'); }}><SelectTrigger data-testid="front-group-delegate-group-select"><SelectValue /></SelectTrigger><SelectContent className="bg-white">{targets.map((item) => <SelectItem key={item.front_group_id} value={item.front_group_id}>{item.name}</SelectItem>)}</SelectContent></Select></div><div><Label>Responsable final</Label><Select value={personId} onValueChange={setPersonId}><SelectTrigger data-testid="front-group-delegate-person-select"><SelectValue /></SelectTrigger><SelectContent className="bg-white"><SelectItem value="none">Pendiente en el Grupo</SelectItem>{people.map((item) => <SelectItem key={item.assignment_id} value={item.person_id}>{item.person_name}</SelectItem>)}</SelectContent></Select></div><div><Label htmlFor="fg-delegate-reason">Motivo</Label><Textarea id="fg-delegate-reason" value={reason} onChange={(event) => setReason(event.target.value)} data-testid="front-group-delegate-reason-input" /></div><Button onClick={delegate} disabled={saving || reason.trim().length < 2} className="w-full bg-slate-900" data-testid="front-group-delegate-submit-button">{saving && <Loader2 className="h-4 w-4 animate-spin" />}Confirmar delegación</Button></div></DialogContent></Dialog>
  </section>;
};