import React, { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { Loader2, LockKeyhole, MapPinned, Power } from 'lucide-react';
import { toast } from 'sonner';

import { useAuth } from '../../context/AuthContext';
import { apiErrorMessage } from '../../lib/apiErrors';
import { Button } from '../ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../ui/tabs';
import { EvangelismCaptureDialog } from '../geo/EvangelismCaptureDialog';
import { FrontGroupCellLinkPanel } from './FrontGroupCellLinkPanel';
import { FrontGroupDialog } from './FrontGroupDialog';
import { FrontGroupOverview } from './FrontGroupOverview';
import { FrontGroupTeamPanel } from './FrontGroupTeamPanel';
import { FrontGroupWorkPanel } from './FrontGroupWorkPanel';

export const FrontGroupDetailPanel = ({ group, groups, onUpdated }) => {
  const { API, getAuthHeaders, user } = useAuth(); const [detail, setDetail] = useState(null); const [report, setReport] = useState(null); const [work, setWork] = useState([]); const [people, setPeople] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [invasionOpen, setInvasionOpen] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [detailResult, reportResult, workResult, peopleResult] = await Promise.allSettled([axios.get(`${API}/api/front-groups/${group.front_group_id}`, getAuthHeaders()), axios.get(`${API}/api/front-group-reports/${group.front_group_id}`, getAuthHeaders()), axios.get(`${API}/api/front-group-work`, { ...getAuthHeaders(), params: { group_id: group.front_group_id } }), axios.get(`${API}/api/core/persons?limit=100`, getAuthHeaders())]); if (detailResult.status !== 'fulfilled') throw detailResult.reason; setDetail(detailResult.value.data); setReport(reportResult.status === 'fulfilled' ? reportResult.value.data : null); setWork(workResult.status === 'fulfilled' ? workResult.value.data.items || [] : []); setPeople(peopleResult.status === 'fulfilled' ? peopleResult.value.data.items || [] : []); } catch (requestError) { setError(apiErrorMessage(requestError, 'No se pudo cargar el Grupo Frontal')); } finally { setLoading(false); } }, [API, getAuthHeaders, group.front_group_id]);
  useEffect(() => { load(); }, [load]);
  const refresh = async () => { await load(); await onUpdated(); };
  const toggleStatus = async () => { try { await axios.put(`${API}/api/front-groups/${group.front_group_id}`, { status: detail.status === 'active' ? 'inactive' : 'active' }, getAuthHeaders()); toast.success('Estado actualizado'); await refresh(); } catch (requestError) { toast.error(apiErrorMessage(requestError, 'No se pudo cambiar el estado')); } };
  if (loading) return <div className="grid min-h-80 place-items-center" data-testid="front-group-detail-loading"><Loader2 className="h-7 w-7 animate-spin text-amber-700" /></div>;
  if (error || !detail) return <div className="border border-red-200 bg-red-50 p-5 text-sm text-red-700" data-testid="front-group-detail-error-alert">{error}</div>;
  const canManage = Boolean(detail.permissions?.manage); const canConfigure = user?.capabilities?.includes('front_groups.rotation.manage') || ['pastor', 'pastora', 'admin', 'superadmin'].includes(String(user?.rol || '').toLowerCase());
  return <section className="space-y-6" data-testid="front-group-detail-panel"><header className="border-b border-slate-200 pb-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-[10px] uppercase text-amber-700">Profundidad {detail.depth || 0}</span><span className={`border px-2 py-0.5 text-[10px] uppercase ${detail.status === 'active' ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : 'border-slate-200 bg-slate-100 text-slate-600'}`} data-testid="front-group-status-badge">{detail.status}</span></div><h2 className="mt-2 font-['Spectral'] text-3xl font-semibold text-slate-950" data-testid="front-group-detail-name">{detail.name}</h2><p className="mt-1 max-w-2xl text-sm text-slate-500">{detail.description || 'Rama de liderazgo y ejecución.'}</p></div><div className="flex flex-wrap gap-2">{canManage && <><FrontGroupDialog groups={groups} parentGroup={detail} onCreated={refresh} /><Button variant="outline" onClick={toggleStatus} data-testid="front-group-status-button"><Power className="h-4 w-4" />{detail.status === 'active' ? 'Desactivar' : 'Activar'}</Button></>}<Button onClick={() => setInvasionOpen(true)} className="bg-emerald-700 text-white hover:bg-emerald-800" data-testid="front-group-crear-invasion-button"><MapPinned className="h-4 w-4" />Crear invasión</Button></div></div><div className="mt-5 inline-flex items-center gap-2 border border-slate-200 bg-slate-50 px-3 py-2 text-xs text-slate-600" data-testid="front-group-pastoral-isolation-badge"><LockKeyhole className="h-4 w-4 text-slate-700" />Cuidado Pastoral permanece aislado del scope frontal.</div></header>
    <Tabs defaultValue="overview" className="w-full"><TabsList className="h-auto w-full justify-start gap-1 overflow-x-auto rounded-none border-b bg-transparent p-0"><TabsTrigger value="overview" className="rounded-none border-b-2 border-transparent px-4 py-3 data-[state=active]:border-amber-600 data-[state=active]:shadow-none" data-testid="front-group-tab-overview">Resumen</TabsTrigger><TabsTrigger value="work" className="rounded-none border-b-2 border-transparent px-4 py-3 data-[state=active]:border-amber-600 data-[state=active]:shadow-none" data-testid="front-group-tab-work">Trabajo</TabsTrigger><TabsTrigger value="team" className="rounded-none border-b-2 border-transparent px-4 py-3 data-[state=active]:border-amber-600 data-[state=active]:shadow-none" data-testid="front-group-tab-team">Equipo</TabsTrigger><TabsTrigger value="cells" className="rounded-none border-b-2 border-transparent px-4 py-3 data-[state=active]:border-amber-600 data-[state=active]:shadow-none" data-testid="front-group-tab-cells">Células</TabsTrigger></TabsList><TabsContent value="overview" className="mt-6"><FrontGroupOverview detail={detail} report={report} /></TabsContent><TabsContent value="work" className="mt-6"><FrontGroupWorkPanel group={detail} groups={groups} assignments={detail.assignments || []} work={work} canManage={canManage} onChanged={refresh} /></TabsContent><TabsContent value="team" className="mt-6"><FrontGroupTeamPanel group={detail} assignments={detail.assignments || []} people={people} canManage={canManage} onChanged={refresh} /></TabsContent><TabsContent value="cells" className="mt-6"><FrontGroupCellLinkPanel group={detail} canConfigure={canConfigure} /></TabsContent></Tabs>
    <EvangelismCaptureDialog open={invasionOpen} onOpenChange={setInvasionOpen} onCreated={refresh} frontGroup={detail} />
  </section>;
};