import React, { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { ArrowLeft, CheckCircle2, ClipboardCheck, Clock3, Loader2, LockKeyhole, Plus, UserPlus, UsersRound, XCircle } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { toast } from 'sonner';
import { useAuth } from '../../context/AuthContext';
import { apiErrorMessage } from '../../lib/apiErrors';
import { Button } from '../../components/ui/button';
import { OperationsMetrics } from '../../components/operations/OperationsMetrics';
import { OperationsShell } from '../../components/operations/OperationsShell';
import { RegistrationDialog } from '../../components/operations/RegistrationDialog';
import { VolunteerAssignDialog } from '../../components/operations/VolunteerAssignDialog';

const dateTime = (value) => new Intl.DateTimeFormat('es-US', { dateStyle: 'full', timeStyle: 'short' }).format(new Date(value));
const statusColor = { confirmed: 'bg-emerald-50 text-emerald-800', checked_in: 'bg-blue-50 text-blue-800', invited: 'bg-amber-50 text-amber-900', declined: 'bg-red-50 text-red-800', no_show: 'bg-slate-100 text-slate-600' };

export default function OperationOccurrencePage() {
  const { occurrenceId } = useParams(); const { API, getAuthHeaders, user } = useAuth(); const [data, setData] = useState(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [shift, setShift] = useState(null); const [registrationOpen, setRegistrationOpen] = useState(false);
  const load = useCallback(() => axios.get(`${API}/api/operations/occurrences/${occurrenceId}`, getAuthHeaders()).then((response) => setData(response.data)).catch((requestError) => setError(apiErrorMessage(requestError, 'No se pudo cargar la ocurrencia'))), [API, getAuthHeaders, occurrenceId]);
  useEffect(() => { load(); }, [load]);
  const assign = async (person) => { setSaving(true); setError(''); try { await axios.post(`${API}/api/operations/shifts/${shift.shift_id}/assignments`, { person_id: person.person_id }, getAuthHeaders()); toast.success('Convocatoria enviada'); setShift(null); await load(); } catch (requestError) { setError(apiErrorMessage(requestError, 'No se pudo asignar')); } finally { setSaving(false); } };
  const respond = async (assignmentId, status) => { try { await axios.patch(`${API}/api/operations/volunteer-assignments/${assignmentId}`, { status }, getAuthHeaders()); toast.success(status === 'confirmed' ? 'Turno confirmado' : 'Turno declinado'); await load(); } catch (requestError) { toast.error(apiErrorMessage(requestError, 'No se pudo responder')); } };
  const register = async (payload) => { setSaving(true); setError(''); try { const response = await axios.post(`${API}/api/operations/occurrences/${occurrenceId}/registrations`, payload, getAuthHeaders()); toast.success(`Inscripción ${response.data.registration_code}`); setRegistrationOpen(false); await load(); } catch (requestError) { setError(apiErrorMessage(requestError, 'No se pudo registrar')); } finally { setSaving(false); } };
  const close = async () => { setSaving(true); try { await axios.post(`${API}/api/operations/occurrences/${occurrenceId}/close`, { notes: 'Cierre operativo' }, getAuthHeaders()); toast.success('Asistencia cerrada'); await load(); } catch (requestError) { toast.error(apiErrorMessage(requestError, 'No se pudo cerrar')); } finally { setSaving(false); } };
  if (!data) return <OperationsShell title="Ocurrencia"><div className="flex justify-center py-20">{error ? <p className="text-red-700">{error}</p> : <Loader2 className="h-7 w-7 animate-spin" />}</div></OperationsShell>;
  const metricCards = { upcoming_occurrences: data.registrations.length, checkins_today: data.metrics.checkins, volunteers_confirmed: data.metrics.confirmed_volunteers, open_volunteer_slots: data.metrics.open_volunteer_slots };
  const actions = <>{data.permissions.checkin && data.occurrence.status !== 'closed' && <Button asChild className="bg-[#E5B94B] text-slate-950 hover:bg-[#F1CB68]" data-testid="occurrence-open-checkin-button"><Link to={`/operaciones/checkin/${occurrenceId}`}><ClipboardCheck className="h-4 w-4" />Abrir check-in</Link></Button>}{data.permissions.manage && data.occurrence.status !== 'closed' && <Button variant="outline" onClick={close} disabled={saving} data-testid="occurrence-close-button"><LockKeyhole className="h-4 w-4" />Cerrar asistencia</Button>}</>;
  return <OperationsShell eyebrow={dateTime(data.occurrence.starts_at)} title={data.event.title} description={`${data.event.location} · ${data.occurrence.status}`} actions={actions}>
    <Link to={`/operaciones/eventos/${data.event.event_id}`} className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-slate-600" data-testid="occurrence-back-link"><ArrowLeft className="h-4 w-4" />Volver al evento</Link>
    <OperationsMetrics metrics={metricCards} />
    <div className="mt-7 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><section className="space-y-5"><div className="border bg-white" data-testid="occurrence-shifts-section"><header className="flex items-center justify-between border-b p-4"><div><p className="text-xs font-bold uppercase text-blue-700">Equipos</p><h2 className="font-['Spectral'] text-2xl font-semibold">Turnos de voluntariado</h2></div></header><div className="divide-y">{data.shifts.length === 0 ? <p className="p-6 text-sm text-slate-500">No hay turnos para esta ocurrencia.</p> : data.shifts.map((item) => { const assignments = data.assignments.filter((entry) => entry.shift_id === item.shift_id); return <article key={item.shift_id} className="p-4" data-testid={`occurrence-shift-${item.shift_id}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{item.name} · {item.role_name}</h3><p className="mt-1 flex items-center gap-2 text-xs text-slate-500"><Clock3 className="h-3.5 w-3.5" />{new Date(item.starts_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} · {assignments.length}/{item.required_volunteers} asignados</p></div>{data.permissions.manage && <Button size="sm" variant="outline" onClick={() => setShift(item)} data-testid={`shift-assign-button-${item.shift_id}`}><UserPlus className="h-4 w-4" />Asignar</Button>}</div><div className="mt-3 flex flex-wrap gap-2">{assignments.map((assignment) => <div key={assignment.assignment_id} className={`border px-3 py-2 text-xs ${statusColor[assignment.status] || 'bg-white'}`} data-testid={`volunteer-assignment-${assignment.assignment_id}`}><b>{assignment.person?.name || 'Persona'}</b><span className="ml-2 uppercase">{assignment.status}</span>{assignment.person_id === user?.person_id && assignment.status === 'invited' && <span className="ml-2 inline-flex gap-1"><button onClick={() => respond(assignment.assignment_id, 'confirmed')} aria-label="Confirmar turno" data-testid={`volunteer-confirm-${assignment.assignment_id}`}><CheckCircle2 className="h-4 w-4" /></button><button onClick={() => respond(assignment.assignment_id, 'declined')} aria-label="Declinar turno" data-testid={`volunteer-decline-${assignment.assignment_id}`}><XCircle className="h-4 w-4" /></button></span>}</div>)}</div></article>; })}</div></div>
      <div className="border bg-white" data-testid="occurrence-registrations-section"><header className="flex items-center justify-between border-b p-4"><div><p className="text-xs font-bold uppercase text-emerald-700">Asistentes</p><h2 className="font-['Spectral'] text-2xl font-semibold">Inscripciones</h2></div>{data.occurrence.status !== 'closed' && <Button size="sm" onClick={() => setRegistrationOpen(true)} data-testid="occurrence-register-button"><Plus className="h-4 w-4" />Registrar</Button>}</header><div className="divide-y">{data.registrations.length === 0 ? <p className="p-6 text-sm text-slate-500">No hay inscripciones visibles.</p> : data.registrations.map((item) => <div key={item.registration_id} className="flex items-center justify-between gap-3 p-4" data-testid={`registration-row-${item.registration_id}`}><div><b className="block text-sm">{item.person?.name || item.guest_name || 'Invitado'}</b><small className="text-slate-500">{item.registration_code} · {item.party_size} persona(s)</small></div><span className="border px-2 py-1 text-xs font-bold uppercase">{item.status}</span></div>)}</div></div></section>
      <aside className="space-y-4"><section className="border bg-white p-5" data-testid="occurrence-attendance-summary"><h2 className="flex items-center gap-2 font-['Spectral'] text-xl font-semibold"><UsersRound className="h-5 w-5" />Resumen de asistencia</h2><dl className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><dt>Personas esperadas</dt><dd className="font-bold">{data.metrics.registered_people}</dd></div><div className="flex justify-between"><dt>Check-ins</dt><dd className="font-bold">{data.metrics.checkins}</dd></div><div className="flex justify-between border-t pt-3"><dt>Tasa de asistencia</dt><dd className="font-bold text-emerald-700">{data.metrics.attendance_rate}%</dd></div></dl></section>{data.occurrence.status === 'closed' && <div className="border-l-4 border-slate-800 bg-white p-4" data-testid="occurrence-closed-alert"><LockKeyhole className="h-5 w-5" /><b className="mt-2 block">Asistencia cerrada</b><p className="mt-1 text-sm text-slate-500">Las métricas quedaron congeladas en el cierre operativo.</p></div>}</aside></div>
    <VolunteerAssignDialog open={Boolean(shift)} onOpenChange={(value) => { if (!value) { setShift(null); setError(''); } }} occurrenceId={occurrenceId} shift={shift} onAssign={assign} saving={saving} error={shift ? error : ''} />
    <RegistrationDialog open={registrationOpen} onOpenChange={(value) => { setRegistrationOpen(value); if (!value) setError(''); }} occurrenceId={occurrenceId} selfPersonId={user?.person_id} privileged={data.permissions.checkin || data.permissions.manage} onRegister={register} saving={saving} error={registrationOpen ? error : ''} />
  </OperationsShell>;
}