import React, { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { ArrowLeft, Check, CheckCircle2, Hash, Loader2, Search, ShieldAlert, UserRoundCheck } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { toast } from 'sonner';
import { useAuth } from '../../context/AuthContext';
import { apiErrorMessage } from '../../lib/apiErrors';
import { Button } from '../../components/ui/button';
import { Input } from '../../components/ui/input';
import { QrScanner } from '../../components/operations/QrScanner';

const newKey = () => `checkin:${Date.now()}:${globalThis.crypto?.randomUUID?.() || Math.random().toString(36).slice(2)}`;

export default function OperationCheckInPage() {
  const { occurrenceId } = useParams(); const { API, getAuthHeaders } = useAuth(); const [data, setData] = useState(null); const [q, setQ] = useState(''); const [results, setResults] = useState([]); const [code, setCode] = useState(''); const [busy, setBusy] = useState(false); const [last, setLast] = useState(null); const [error, setError] = useState('');
  const load = useCallback(() => axios.get(`${API}/api/operations/occurrences/${occurrenceId}`, getAuthHeaders()).then((response) => setData(response.data)).catch((requestError) => setError(apiErrorMessage(requestError, 'No se pudo abrir el check-in'))), [API, getAuthHeaders, occurrenceId]);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { if (q.trim().length < 2) { setResults([]); return undefined; } const timer = setTimeout(() => axios.get(`${API}/api/operations/occurrences/${occurrenceId}/checkin/search`, { ...getAuthHeaders(), params: { q } }).then((response) => setResults(response.data.items || [])).catch(() => setResults([])), 200); return () => clearTimeout(timer); }, [API, getAuthHeaders, occurrenceId, q]);
  const checkin = async (reference) => { setBusy(true); setError(''); try { const response = await axios.post(`${API}/api/operations/occurrences/${occurrenceId}/check-ins`, { ...reference, kind: 'auto', idempotency_key: newKey() }, getAuthHeaders()); setLast(response.data); if (response.data.duplicate) toast.warning('La Persona ya tenía check-in'); else toast.success('Check-in registrado'); setQ(''); setCode(''); setResults([]); await load(); } catch (requestError) { setError(apiErrorMessage(requestError, 'No se pudo registrar el check-in')); } finally { setBusy(false); } };
  if (!data) return <main className="flex min-h-screen items-center justify-center bg-[#101820] text-white">{error || <Loader2 className="h-8 w-8 animate-spin" />}</main>;
  return <main className="min-h-screen bg-[#101820] text-white" data-testid="operation-checkin-page"><header className="border-b border-white/10 px-4 py-4"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4"><div><Link to={`/operaciones/ocurrencias/${occurrenceId}`} className="inline-flex items-center gap-2 text-xs text-slate-300" data-testid="checkin-back-link"><ArrowLeft className="h-4 w-4" />Volver a ocurrencia</Link><h1 className="mt-2 font-['Spectral'] text-3xl font-semibold" data-testid="checkin-event-title">{data.event.title}</h1><p className="mt-1 text-sm text-slate-300">{data.event.location} · {new Date(data.occurrence.starts_at).toLocaleString()}</p></div><div className="border border-emerald-400/40 bg-emerald-400/10 px-4 py-3 text-center"><strong className="block text-3xl text-emerald-300" data-testid="checkin-live-count">{data.metrics.checkins}</strong><span className="text-xs uppercase text-emerald-100">admitidos</span></div></div></header>
    <div className="mx-auto grid max-w-6xl gap-5 px-4 py-6 lg:grid-cols-[1.35fr_1fr]"><section className="space-y-4"><div className="border border-white/10 bg-white p-4 text-slate-950"><h2 className="flex items-center gap-2 font-['Spectral'] text-2xl font-semibold"><Search className="h-5 w-5 text-blue-700" />Búsqueda rápida</h2><div className="relative mt-4"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><Input value={q} onChange={(event) => setQ(event.target.value)} placeholder="Nombre o número VV" autoFocus className="h-12 pl-9 text-base" data-testid="checkin-search-input" /></div>{results.length > 0 && <div className="mt-2 max-h-80 divide-y overflow-y-auto border">{results.map((item, index) => <button key={`${item.kind}-${item.person_id || item.registration_id}-${index}`} disabled={busy} onClick={() => checkin(item.person_id ? { person_id: item.person_id } : { registration_id: item.registration_id })} className="flex w-full items-center gap-3 p-3 text-left hover:bg-emerald-50 disabled:opacity-50" data-testid={`checkin-search-result-${item.person_id || item.registration_id}`}><span className={`flex h-10 w-10 items-center justify-center ${item.already_checked_in_at ? 'bg-amber-100 text-amber-800' : 'bg-emerald-100 text-emerald-800'}`}>{item.already_checked_in_at ? <CheckCircle2 className="h-5 w-5" /> : <UserRoundCheck className="h-5 w-5" />}</span><span className="min-w-0 flex-1"><b className="block truncate">{item.name}</b><small className="text-slate-500">{item.person_number || item.registration_code || item.registration_status}</small></span><Check className="h-5 w-5 text-slate-400" /></button>)}</div>}</div>
      <div className="border border-white/10 bg-white p-4 text-slate-950"><h2 className="flex items-center gap-2 font-['Spectral'] text-2xl font-semibold"><Hash className="h-5 w-5 text-amber-700" />Código de acceso</h2><div className="mt-4 grid grid-cols-[1fr_auto] gap-2"><Input value={code} onChange={(event) => setCode(event.target.value)} placeholder="N.º miembro, OP-… o contenido QR" className="h-12" data-testid="checkin-code-input" /><Button onClick={() => checkin({ code })} disabled={busy || !code.trim()} className="h-12 bg-amber-600 hover:bg-amber-700" data-testid="checkin-code-submit-button">{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Check className="h-4 w-4" />}Ingresar</Button></div></div>
      {error && <div className="border border-red-400 bg-red-950/60 p-3 text-sm text-red-100" data-testid="checkin-error-alert">{error}</div>}{last && <div className={`border-l-4 p-4 ${last.duplicate ? 'border-amber-400 bg-amber-950/60' : 'border-emerald-400 bg-emerald-950/60'}`} data-testid="checkin-result-alert">{last.duplicate ? <ShieldAlert className="h-6 w-6 text-amber-300" /> : <CheckCircle2 className="h-6 w-6 text-emerald-300" />}<b className="mt-2 block text-lg">{last.duplicate ? 'Check-in ya existente' : 'Entrada confirmada'}</b><p className="mt-1 text-xs text-slate-300">{new Date(last.checked_in_at).toLocaleTimeString()} · {last.method}</p></div>}</section>
      <aside><QrScanner onScan={(value) => checkin({ code: value })} /><section className="mt-4 border border-white/10 bg-white/5 p-4" data-testid="checkin-recent-section"><h2 className="font-['Spectral'] text-xl font-semibold">Actividad reciente</h2><div className="mt-3 space-y-2">{data.checkins.slice(0, 8).map((item) => <div key={item.checkin_id} className="flex items-center justify-between border-b border-white/10 py-2 text-sm"><span>{item.method}</span><time className="text-slate-400">{new Date(item.checked_in_at).toLocaleTimeString()}</time></div>)}</div></section></aside></div>
  </main>;
}