import React, { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { ArrowLeft, CalendarClock, Clock3, Download, FileUp, Loader2, MapPin, Plus, RefreshCw, Repeat2 } from 'lucide-react';
import { Link, useParams } from 'react-router-dom';
import { toast } from 'sonner';
import { useAuth } from '../../context/AuthContext';
import { apiErrorMessage } from '../../lib/apiErrors';
import { Button } from '../../components/ui/button';
import { ShiftTemplateDialog } from '../../components/operations/ShiftTemplateDialog';
import { OperationsShell } from '../../components/operations/OperationsShell';

const dateTime = (value) => new Intl.DateTimeFormat('es-US', { dateStyle: 'full', timeStyle: 'short' }).format(new Date(value));

export default function OperationEventDetailPage() {
  const { eventId } = useParams(); const { API, getAuthHeaders } = useAuth(); const [event, setEvent] = useState(null); const [shiftOpen, setShiftOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [file, setFile] = useState(null);
  const load = useCallback(() => axios.get(`${API}/api/operations/events/${eventId}`, getAuthHeaders()).then((response) => setEvent(response.data)).catch((requestError) => setError(apiErrorMessage(requestError, 'No se pudo cargar el evento'))), [API, eventId, getAuthHeaders]);
  useEffect(() => { load(); }, [load]);
  const createShift = async (payload) => { setSaving(true); setError(''); try { await axios.post(`${API}/api/operations/events/${eventId}/shift-templates`, payload, getAuthHeaders()); toast.success('Turno creado para las ocurrencias'); setShiftOpen(false); await load(); } catch (requestError) { setError(apiErrorMessage(requestError, 'No se pudo crear el turno')); } finally { setSaving(false); } };
  const materialize = async () => { setSaving(true); try { const response = await axios.post(`${API}/api/operations/events/${eventId}/materialize?horizon_days=365`, {}, getAuthHeaders()); toast.success(`${response.data.created_occurrences} ocurrencias nuevas`); await load(); } catch (requestError) { toast.error(apiErrorMessage(requestError, 'No se pudo ampliar la serie')); } finally { setSaving(false); } };
  const upload = async () => { if (!file) return; setSaving(true); const body = new FormData(); body.append('file', file); try { await axios.post(`${API}/api/operations/events/${eventId}/attachments`, body, getAuthHeaders()); toast.success('Archivo adjuntado'); setFile(null); await load(); } catch (requestError) { toast.error(apiErrorMessage(requestError, 'No se pudo adjuntar')); } finally { setSaving(false); } };
  const download = async (attachment) => { try { const response = await axios.get(`${API}/api/operations/events/${eventId}/attachments/${attachment.file_id}`, { ...getAuthHeaders(), responseType: 'blob' }); const url = URL.createObjectURL(response.data); const anchor = document.createElement('a'); anchor.href = url; anchor.download = attachment.filename; anchor.click(); URL.revokeObjectURL(url); } catch (requestError) { toast.error(apiErrorMessage(requestError, 'No se pudo descargar')); } };
  if (!event) return <OperationsShell title="Evento"><div className="flex justify-center py-20">{error ? <p className="text-red-700">{error}</p> : <Loader2 className="h-7 w-7 animate-spin" />}</div></OperationsShell>;
  const actions = event.permissions?.manage ? <><Button variant="outline" onClick={materialize} disabled={saving} data-testid="event-materialize-button"><RefreshCw className="h-4 w-4" />Extender serie</Button><Button onClick={() => setShiftOpen(true)} className="bg-[#E5B94B] text-slate-950 hover:bg-[#F1CB68]" data-testid="event-new-shift-button"><Plus className="h-4 w-4" />Nuevo turno</Button></> : null;
  return <OperationsShell eyebrow={event.recurrence?.frequency === 'none' ? 'Evento único' : 'Serie recurrente'} title={event.title} description={event.description || 'Evento operativo'} actions={actions}>
    <Link to="/operaciones/eventos" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-slate-600" data-testid="event-detail-back-link"><ArrowLeft className="h-4 w-4" />Volver a eventos</Link>
    <div className="grid gap-6 lg:grid-cols-[1.55fr_1fr]"><section className="space-y-4"><div className="border bg-white p-5"><div className="grid gap-4 sm:grid-cols-3"><div><small className="uppercase text-slate-400">Lugar</small><p className="mt-1 flex items-center gap-2 text-sm font-semibold"><MapPin className="h-4 w-4 text-emerald-700" />{event.location}</p></div><div><small className="uppercase text-slate-400">Patrón</small><p className="mt-1 flex items-center gap-2 text-sm font-semibold"><Repeat2 className="h-4 w-4 text-blue-700" />{event.recurrence?.frequency === 'none' ? 'Único' : `${event.recurrence.frequency} · cada ${event.recurrence.interval}`}</p></div><div><small className="uppercase text-slate-400">Ocurrencias</small><p className="mt-1 text-sm font-semibold">{event.occurrences.length}</p></div></div></div>
      <section className="border bg-white" data-testid="event-occurrences-list"><header className="border-b p-4"><h2 className="font-['Spectral'] text-2xl font-semibold">Calendario de ocurrencias</h2></header><div className="divide-y">{event.occurrences.map((item) => <Link key={item.occurrence_id} to={`/operaciones/ocurrencias/${item.occurrence_id}`} className="flex items-center gap-4 p-4 hover:bg-blue-50" data-testid={`event-occurrence-${item.occurrence_id}`}><span className="flex h-10 w-10 items-center justify-center bg-blue-50 text-blue-700"><CalendarClock className="h-5 w-5" /></span><span className="min-w-0 flex-1"><b className="block text-sm">{dateTime(item.starts_at)}</b><small className="text-slate-500">{item.registrations} inscritos · {item.checkins} check-ins · {item.volunteers} voluntarios</small></span><span className="border px-2 py-1 text-xs font-bold uppercase">{item.status}</span></Link>)}</div></section></section>
      <aside className="space-y-4"><section className="border bg-white p-4"><h2 className="flex items-center gap-2 font-['Spectral'] text-xl font-semibold"><Clock3 className="h-5 w-5" />Turnos recurrentes</h2><p className="mt-2 text-sm leading-6 text-slate-500">Los turnos creados aquí se materializan en toda la serie y también en nuevas ocurrencias futuras.</p>{event.permissions?.manage && <Button className="mt-4 w-full" variant="outline" onClick={() => setShiftOpen(true)} data-testid="event-shift-empty-action"><Plus className="h-4 w-4" />Añadir equipo o turno</Button>}</section>
        <section className="border bg-white p-4" data-testid="event-attachments-section"><h2 className="flex items-center gap-2 font-['Spectral'] text-xl font-semibold"><FileUp className="h-5 w-5" />Archivos</h2><div className="mt-3 space-y-2">{(event.attachments || []).map((attachment) => <button key={attachment.file_id} onClick={() => download(attachment)} className="flex w-full items-center justify-between border p-2 text-left text-sm hover:bg-slate-50" data-testid={`event-attachment-${attachment.file_id}`}><span className="truncate">{attachment.filename}</span><Download className="h-4 w-4" /></button>)}</div>{event.permissions?.manage && <div className="mt-4 space-y-2"><input type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={(e) => setFile(e.target.files?.[0] || null)} className="block w-full text-xs" data-testid="event-attachment-input" /><Button onClick={upload} disabled={!file || saving} className="w-full" data-testid="event-attachment-upload-button"><FileUp className="h-4 w-4" />Adjuntar archivo</Button></div>}</section></aside></div>
    <ShiftTemplateDialog open={shiftOpen} onOpenChange={(value) => { setShiftOpen(value); if (!value) setError(''); }} onCreate={createShift} saving={saving} error={shiftOpen ? error : ''} />
  </OperationsShell>;
}