import React, { useEffect, useState } from 'react';
import { CheckCircle2, Loader2 } from 'lucide-react';
import { Button } from '../ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '../ui/dialog';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { Textarea } from '../ui/textarea';

export const CompleteVisitDialog = ({ visit, onComplete, saving, canWriteSummary }) => {
  const [open, setOpen] = useState(false); const [results, setResults] = useState({}); const [summary, setSummary] = useState('');
  useEffect(() => { setResults(Object.fromEntries((visit.participants || []).map((item) => [item.person_id, { outcome: 'successful', next_step: '', next_step_at: '' }]))); }, [visit]);
  const submit = async (event) => { event.preventDefault(); await onComplete({ participant_results: Object.entries(results).map(([person_id, value]) => ({ person_id, outcome: value.outcome, next_step: value.next_step || null, next_step_at: value.next_step_at ? new Date(value.next_step_at).toISOString() : null })), confidential_summary: canWriteSummary ? summary || null : null }); setOpen(false); setSummary(''); };
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" className="bg-[#1B2A4A]" data-testid={`visit-complete-open-${visit.visit_id}`}><CheckCircle2 className="h-4 w-4" />Cerrar visita</Button></DialogTrigger><DialogContent className="max-h-[85vh] max-w-2xl overflow-y-auto" data-testid={`visit-complete-dialog-${visit.visit_id}`}><DialogHeader><DialogTitle className="font-['Spectral'] text-2xl">Cierre individual de la visita</DialogTitle></DialogHeader><form onSubmit={submit} className="space-y-4">{(visit.participants || []).map((participant) => <div key={participant.person_id} className="grid gap-3 border p-4 sm:grid-cols-2" data-testid={`visit-result-${participant.person_id}`}><div className="sm:col-span-2"><b>{participant.person?.name}</b><p className="text-xs text-slate-500">{participant.person?.person_number}</p></div><label className="text-xs font-semibold text-slate-500">Resultado<select value={results[participant.person_id]?.outcome || 'successful'} onChange={(event) => setResults((old) => ({ ...old, [participant.person_id]: { ...old[participant.person_id], outcome: event.target.value } }))} className="mt-1 h-10 w-full border bg-white px-3 text-sm" data-testid={`visit-outcome-${participant.person_id}`}><option value="successful">Contacto exitoso</option><option value="no_access">Sin acceso</option><option value="absent">Ausente</option><option value="rescheduled">Reprogramado</option><option value="refused">Rechazado</option></select></label><label className="text-xs font-semibold text-slate-500">Próxima fecha<Input type="datetime-local" value={results[participant.person_id]?.next_step_at || ''} onChange={(event) => setResults((old) => ({ ...old, [participant.person_id]: { ...old[participant.person_id], next_step_at: event.target.value } }))} className="mt-1" data-testid={`visit-next-date-${participant.person_id}`} /></label><Input value={results[participant.person_id]?.next_step || ''} onChange={(event) => setResults((old) => ({ ...old, [participant.person_id]: { ...old[participant.person_id], next_step: event.target.value } }))} placeholder="Próximo paso individual" className="sm:col-span-2" data-testid={`visit-next-step-${participant.person_id}`} /></div>)}{canWriteSummary && <div className="space-y-2"><Label>Resumen confidencial de hogar</Label><Textarea value={summary} onChange={(event) => setSummary(event.target.value)} placeholder="Se cifrará en la bóveda; no se copiará a otros módulos" data-testid="visit-confidential-summary-input" /></div>}<Button disabled={saving} className="w-full bg-[#1B2A4A]" data-testid="visit-complete-submit-button">{saving && <Loader2 className="h-4 w-4 animate-spin" />}Completar y guardar historiales</Button></form></DialogContent></Dialog>;
};