import React, { useState } from 'react';
import axios from 'axios';
import { Loader2, Plus } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '../../context/AuthContext';
import { Button } from '../ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '../ui/dialog';
import { Label } from '../ui/label';
import { Textarea } from '../ui/textarea';
import { CarePersonPicker } from './CarePersonPicker';
import { apiErrorMessage } from '../../lib/apiErrors';

export const PastoralCaseDialog = ({ onCreated }) => {
  const { API, getAuthHeaders } = useAuth(); const [open, setOpen] = useState(false); const [person, setPerson] = useState(null); const [caseType, setCaseType] = useState('pastoral_care'); const [priority, setPriority] = useState('medium'); const [summary, setSummary] = useState(''); const [saving, setSaving] = useState(false);
  const submit = async (event) => { event.preventDefault(); if (!person) return; setSaving(true); try { const response = await axios.post(`${API}/api/care/cases`, { person_id: person.person_id, case_type: caseType, priority, source_type: 'manual', operational_summary: summary || null }, getAuthHeaders()); toast.success('Expediente pastoral creado'); setOpen(false); setPerson(null); setSummary(''); onCreated?.(response.data); } catch (error) { toast.error(apiErrorMessage(error, 'No se pudo crear el expediente')); } finally { setSaving(false); } };
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button className="bg-[#C8A951] text-[#0B1428] hover:bg-[#D8BC61]" data-testid="create-pastoral-case-button"><Plus className="h-4 w-4" />Nuevo caso</Button></DialogTrigger><DialogContent className="max-w-xl" data-testid="create-pastoral-case-dialog"><DialogHeader><DialogTitle className="font-['Spectral'] text-2xl">Abrir expediente pastoral</DialogTitle></DialogHeader><form onSubmit={submit} className="space-y-4"><div className="space-y-2"><Label>Persona canónica</Label><CarePersonPicker value={person} onChange={setPerson} testId="new-case-person" /></div><div className="grid gap-3 sm:grid-cols-2"><div className="space-y-2"><Label>Tipo de cuidado</Label><select value={caseType} onChange={(event) => setCaseType(event.target.value)} className="h-10 w-full border bg-white px-3 text-sm" data-testid="new-case-type-select"><option value="pastoral_care">Cuidado pastoral</option><option value="reconciliation">Reconciliación</option><option value="restoration">Restauración</option><option value="return">Regreso</option><option value="crisis">Crisis</option><option value="bereavement">Duelo</option><option value="family">Familia</option><option value="health">Salud</option><option value="other">Otro</option></select></div><div className="space-y-2"><Label>Prioridad</Label><select value={priority} onChange={(event) => setPriority(event.target.value)} className="h-10 w-full border bg-white px-3 text-sm" data-testid="new-case-priority-select"><option value="low">Baja</option><option value="medium">Media</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></div></div><div className="space-y-2"><Label>Resumen operativo</Label><Textarea value={summary} onChange={(event) => setSummary(event.target.value)} placeholder="Sin incluir notas confidenciales" data-testid="new-case-summary-input" /></div><Button disabled={!person || saving} className="w-full bg-[#1B2A4A]" data-testid="new-case-submit-button">{saving && <Loader2 className="h-4 w-4 animate-spin" />}Crear expediente</Button></form></DialogContent></Dialog>;
};