import React, { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { FilePlus2, Loader2, LockKeyhole, MessageSquarePlus, ShieldCheck } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '../../context/AuthContext';
import { apiErrorMessage } from '../../lib/apiErrors';
import { Button } from '../ui/button';
import { Label } from '../ui/label';
import { Textarea } from '../ui/textarea';
import { dateTime } from '../../lib/careLabels';

export const PastoralVaultPanel = ({ caseId, permissions }) => {
  const { API, getAuthHeaders } = useAuth(); const [notes, setNotes] = useState([]); const [content, setContent] = useState(''); const [visibility, setVisibility] = useState(permissions?.confidential_write ? 'pastoral_core' : 'assigned_team'); const [parent, setParent] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const load = useCallback(() => { setLoading(true); setError(''); axios.get(`${API}/api/care/cases/${caseId}/notes`, getAuthHeaders()).then((response) => setNotes(response.data.items || [])).catch((requestError) => setError(apiErrorMessage(requestError, 'No se pudo abrir la bóveda'))).finally(() => setLoading(false)); }, [API, caseId, getAuthHeaders]);
  useEffect(load, [load]);
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { const path = parent ? `/api/care/cases/${caseId}/notes/${parent.note_id}/addendum` : `/api/care/cases/${caseId}/notes`; const body = parent ? { content } : { content, visibility }; await axios.post(`${API}${path}`, body, getAuthHeaders()); toast.success(parent ? 'Adenda cifrada y registrada' : 'Nota cifrada y guardada en bóveda'); setContent(''); setParent(null); await load(); } catch (requestError) { toast.error(apiErrorMessage(requestError, 'No se pudo guardar la nota')); } finally { setSaving(false); } };
  return <section className="border border-[#C8A951]/30 bg-[#0A1120] text-white" data-testid="pastoral-vault-panel"><header className="flex flex-col gap-3 border-b border-[#C8A951]/20 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="flex items-center gap-2 text-xs font-semibold uppercase text-[#D8BC61]"><LockKeyhole className="h-4 w-4" />Bóveda cifrada</p><h2 className="mt-1 font-['Spectral'] text-2xl">Notas pastorales</h2></div><span className="flex items-center gap-2 border border-[#C8A951]/30 px-3 py-1 text-xs text-slate-300" data-testid="pastoral-vault-audit-badge"><ShieldCheck className="h-4 w-4 text-[#D8BC61]" />Append-only · lectura auditada</span></header>
    <div className="grid gap-0 lg:grid-cols-[1fr_1.1fr]"><form onSubmit={submit} className="space-y-3 border-b border-[#C8A951]/20 p-5 lg:border-b-0 lg:border-r" data-testid="pastoral-vault-form"><div className="space-y-2"><Label className="text-slate-200">{parent ? `Adenda a nota del ${dateTime(parent.created_at)}` : 'Nueva nota confidencial'}</Label><Textarea value={content} onChange={(event) => setContent(event.target.value)} className="min-h-36 border-slate-700 bg-[#111C30] text-white placeholder:text-slate-500" placeholder="El contenido se cifra antes de guardarse" data-testid="pastoral-vault-note-input" required /></div>{!parent && permissions?.confidential_write && <select value={visibility} onChange={(event) => setVisibility(event.target.value)} className="h-10 w-full border border-slate-700 bg-[#111C30] px-3 text-sm" data-testid="pastoral-vault-visibility-select"><option value="pastoral_core">Solo núcleo pastoral</option><option value="assigned_team">Equipo asignado</option></select>}<div className="flex gap-2">{parent && <Button type="button" variant="outline" className="border-slate-600 bg-transparent text-white" onClick={() => { setParent(null); setContent(''); }} data-testid="pastoral-vault-cancel-addendum">Cancelar</Button>}<Button disabled={saving || content.trim().length < 2} className="flex-1 bg-[#C8A951] text-[#0B1428] hover:bg-[#D8BC61]" data-testid="pastoral-vault-save-note-button">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : parent ? <MessageSquarePlus className="h-4 w-4" /> : <FilePlus2 className="h-4 w-4" />}{parent ? 'Guardar adenda' : 'Cifrar y guardar'}</Button></div></form>
      <div className="max-h-[560px] overflow-y-auto p-5" data-testid="pastoral-vault-notes-list">{loading && <div className="flex justify-center py-12"><Loader2 className="h-6 w-6 animate-spin text-[#D8BC61]" /></div>}{error && <p className="border border-amber-700 bg-amber-950/50 p-3 text-sm text-amber-200" data-testid="pastoral-vault-error">{error}</p>}{!loading && !error && notes.length === 0 && <p className="py-12 text-center text-sm text-slate-400" data-testid="pastoral-vault-empty">No hay notas cifradas en este expediente.</p>}{notes.map((note) => <article key={note.note_id} className="mb-3 border border-slate-700 bg-[#111C30] p-4" data-testid={`pastoral-vault-note-${note.note_id}`}><div className="flex items-center justify-between gap-3"><span className="text-xs font-semibold uppercase text-[#D8BC61]">{note.visibility === 'pastoral_core' ? 'Núcleo pastoral' : 'Equipo asignado'}</span><time className="text-xs text-slate-500">{dateTime(note.created_at)}</time></div>{note.addendum_to_note_id && <p className="mt-2 text-xs text-slate-400">Adenda a {note.addendum_to_note_id.slice(0, 8)}</p>}<p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-200" data-testid={`pastoral-vault-note-content-${note.note_id}`}>{note.content}</p><Button type="button" variant="ghost" size="sm" className="mt-3 text-[#D8BC61] hover:bg-slate-800 hover:text-[#F3DA83]" onClick={() => { setParent(note); setVisibility(note.visibility); setContent(''); }} data-testid={`pastoral-vault-addendum-${note.note_id}`}><MessageSquarePlus className="h-4 w-4" />Añadir adenda</Button></article>)}</div></div>
  </section>;
};