import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { Loader2, Play, Save } from 'lucide-react';
import { toast } from 'sonner';

import { useAuth } from '../../context/AuthContext';
import { Button } from '../ui/button';
import { Checkbox } from '../ui/checkbox';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select';

const statuses = [['present', 'Presente'], ['absent', 'Ausente'], ['excused', 'Excusado'], ['remote', 'Remoto'], ['late', 'Llegó tarde'], ['left_early', 'Salió temprano']];

export const BoardAttendancePanel = ({ meeting, members, onReload, onStarted }) => {
  const { API, getAuthHeaders } = useAuth(); const [items, setItems] = useState([]); const [notice, setNotice] = useState(false); const [starting, setStarting] = useState(false); const [saving, setSaving] = useState(false);
  useEffect(() => { const saved = new Map((meeting.attendance || []).map((item) => [item.person_id, item])); setItems((members || []).filter(Boolean).map((member) => saved.get(member.person_id) || { person_id: member.person_id, status: 'absent', checked_in_at: null, checked_out_at: null, recording_notice_acknowledged: false })); }, [meeting.attendance, members]);
  const patch = (id, changes) => setItems((current) => current.map((item) => item.person_id === id ? { ...item, ...changes } : item));
  const persistAttendance = async () => axios.put(`${API}/api/board/meetings/${meeting.meeting_id}/attendance`, { items }, getAuthHeaders());
  const save = async () => { setSaving(true); try { await persistAttendance(); toast.success('Asistencia y quórum actualizados'); await onReload(); } catch (error) { toast.error(error?.response?.data?.detail || 'No se pudo guardar'); } finally { setSaving(false); } };
  const start = async () => { setStarting(true); try { await persistAttendance(); const response = await axios.post(`${API}/api/board/meetings/${meeting.meeting_id}/start`, { recording_notice_confirmed: notice }, getAuthHeaders()); onStarted?.(response.data); toast.success('Reunión abierta; control de grabación listo'); await onReload(); } catch (error) { toast.error(error?.response?.data?.detail || 'No se pudo abrir'); } finally { setStarting(false); } };
  return <section className="space-y-4" data-testid="board-attendance-panel"><div className={`border p-4 ${meeting.quorum?.has_quorum ? 'border-emerald-300 bg-emerald-50' : 'border-amber-300 bg-amber-50'}`} data-testid="board-quorum-status"><b>{meeting.quorum?.has_quorum ? 'Quórum confirmado' : 'Sin quórum'}</b><p className="text-xs">{meeting.quorum?.present_voting || 0} presentes con voto · se requieren {meeting.quorum?.required || 0}</p></div>{(members || []).filter(Boolean).map((member) => { const entry = items.find((item) => item.person_id === member.person_id); return <div key={member.person_id} className="border bg-white p-4" data-testid={`board-attendee-${member.person_id}`}><p className="font-semibold">{member.name}</p><div className="mt-3 grid gap-2 sm:grid-cols-[1fr_auto]"><Select value={entry?.status || 'absent'} onValueChange={(value) => patch(member.person_id, { status: value, checked_in_at: ['present', 'remote', 'late'].includes(value) ? new Date().toISOString() : null })}><SelectTrigger data-testid={`board-attendance-status-${member.person_id}`}><SelectValue /></SelectTrigger><SelectContent className="bg-white">{statuses.map(([value, label]) => <SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select><label className="flex min-h-10 items-center gap-2 border px-3 text-xs"><Checkbox checked={entry?.recording_notice_acknowledged || false} onCheckedChange={(value) => patch(member.person_id, { recording_notice_acknowledged: value })} data-testid={`board-recording-ack-${member.person_id}`} />Aviso recibido</label></div></div>; })}<div className="grid gap-3 sm:grid-cols-2"><Button onClick={save} disabled={saving || starting} variant="outline" data-testid="save-board-attendance-button">{saving ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Save className="mr-2 h-4 w-4" />}Guardar asistencia</Button>{meeting.status === 'scheduled' && <div className="space-y-2"><label className="flex items-center gap-2 text-xs"><Checkbox checked={notice} onCheckedChange={setNotice} data-testid="confirm-board-recording-notice" />Confirmo que el aviso de grabación fue comunicado</label><p className="text-xs text-slate-500">Al abrir la reunión se mostrará el control de audio desde el inicio.</p><Button onClick={start} disabled={!notice || starting || saving} className="w-full bg-emerald-700" data-testid="start-board-meeting-button">{starting ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Play className="mr-2 h-4 w-4" />}Abrir reunión e ir a grabación</Button></div>}</div></section>;
};