import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { Download, Headphones, Loader2, RefreshCw } from 'lucide-react';
import { toast } from 'sonner';

import { useAuth } from '../../context/AuthContext';
import { Button } from '../ui/button';

export const BoardRecordingList = ({ recordings, onRefresh }) => {
  const { API, getAuthHeaders } = useAuth(); const [loadingId, setLoadingId] = useState(null); const [audio, setAudio] = useState(null);
  useEffect(() => () => { if (audio?.url) URL.revokeObjectURL(audio.url); }, [audio]);
  const fetchBlob = async (item) => { const response = await axios.get(`${API}/api/board/recordings/${item.recording_id}`, { ...getAuthHeaders(), responseType: 'blob' }); return response.data; };
  const listen = async (item) => { setLoadingId(item.recording_id); try { const blob = await fetchBlob(item); if (audio?.url) URL.revokeObjectURL(audio.url); setAudio({ id: item.recording_id, url: URL.createObjectURL(blob) }); } catch { toast.error('No se pudo abrir el audio guardado'); } finally { setLoadingId(null); } };
  const download = async (item) => { setLoadingId(item.recording_id); try { const blob = await fetchBlob(item); const href = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = href; link.download = `junta-${item.recording_id}.webm`; link.click(); URL.revokeObjectURL(href); } catch { toast.error('No se pudo descargar el audio'); } finally { setLoadingId(null); } };
  return <section className="border bg-white p-4" data-testid="board-recordings-list"><div className="flex items-center justify-between"><h2 className="font-semibold">Audio original</h2><Button size="icon" variant="ghost" onClick={onRefresh} aria-label="Actualizar audio" data-testid="refresh-transcript-button"><RefreshCw className="h-4 w-4" /></Button></div>{recordings.length ? <div className="mt-3 space-y-3">{recordings.map((item) => <article key={item.recording_id} className="border p-3" data-testid={`board-recording-${item.recording_id}`}><div className="flex flex-wrap items-center justify-between gap-3"><div><b className="text-sm text-emerald-700">Audio guardado</b><p className="text-xs text-slate-500">{Math.round((item.bytes || 0) / 1024)} KB · {Math.round(item.duration_seconds || 0)} s</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => listen(item)} disabled={loadingId === item.recording_id} data-testid={`play-board-recording-${item.recording_id}`}>{loadingId === item.recording_id ? <Loader2 className="h-4 w-4 animate-spin" /> : <Headphones className="h-4 w-4" />}Escuchar</Button><Button size="icon" variant="outline" onClick={() => download(item)} disabled={loadingId === item.recording_id} aria-label="Descargar audio" data-testid={`download-board-recording-${item.recording_id}`}><Download className="h-4 w-4" /></Button></div></div>{item.transcription_status === 'blocked' && <p className="mt-3 border-l-2 border-amber-500 bg-amber-50 p-2 text-xs text-amber-900" data-testid="stt-diarization-blocked-message">El audio está guardado. Solo la transcripción automática está pendiente de configuración.</p>}{audio?.id === item.recording_id && <audio src={audio.url} controls autoPlay className="mt-3 w-full" data-testid={`board-recording-player-${item.recording_id}`}>Su navegador no puede reproducir este audio.</audio>}</article>)}</div> : <p className="mt-3 text-xs text-slate-500" data-testid="board-recordings-empty">Aún no hay audio guardado.</p>}</section>;
};