import React, { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { Bot, FileCheck2, Save, UserRoundCog } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '../../context/AuthContext';
import { speakerLabel } from '../../lib/displayLabels';
import { BoardRecorder } from './BoardRecorder';
import { BoardRecordingList } from './BoardRecordingList';
import { PersonSelect } from '../cellular/CellularFields';
import { Button } from '../ui/button';
import { Checkbox } from '../ui/checkbox';
import { Textarea } from '../ui/textarea';

export const TranscriptMinutesPanel = ({ meeting, members, onReload }) => {
  const { API, getAuthHeaders } = useAuth();
  const [transcript, setTranscript] = useState({ segments: [], mappings: [], live: { status: 'idle' } });
  const [recordings, setRecordings] = useState([]); const [manual, setManual] = useState(''); const [editing, setEditing] = useState({}); const [aiAck, setAiAck] = useState(false); const [loadError, setLoadError] = useState('');
  const loadTranscript = useCallback(async () => { const response = await axios.get(`${API}/api/board/meetings/${meeting.meeting_id}/transcript`, getAuthHeaders()); setTranscript({ ...response.data, segments: response.data.segments || [], mappings: response.data.mappings || [], live: response.data.live || { status: 'idle' } }); }, [API, getAuthHeaders, meeting.meeting_id]);
  const load = useCallback(async () => { setLoadError(''); const [tx, rec] = await Promise.allSettled([loadTranscript(), axios.get(`${API}/api/board/meetings/${meeting.meeting_id}/recordings`, getAuthHeaders())]); if (rec.status === 'fulfilled') setRecordings(rec.value.data.items || []); if (tx.status === 'rejected' || rec.status === 'rejected') setLoadError('Parte del espacio de audio no pudo actualizarse. Pulse actualizar para reintentar.'); }, [API, getAuthHeaders, loadTranscript, meeting.meeting_id]);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { if (meeting.status !== 'open') return undefined; const timer = window.setInterval(() => loadTranscript().catch(() => {}), 4000); return () => window.clearInterval(timer); }, [loadTranscript, meeting.status]);
  useEffect(() => {
    const latestManual = [...(meeting.minutes || [])]
      .filter((item) => item.minute_type === 'manual')
      .sort((left, right) => Number(right.version || 0) - Number(left.version || 0))[0];
    if (latestManual) setManual(typeof latestManual.content === 'string' ? latestManual.content : '');
  }, [meeting.minutes]);
  const mapSpeaker = async (speaker, personId) => { try { await axios.put(`${API}/api/board/meetings/${meeting.meeting_id}/speaker-mapping`, { speaker_label: speaker, person_id: personId, external_processing_acknowledged: aiAck }, getAuthHeaders()); toast.success('Participante identificado; los borradores se actualizarán'); await load(); } catch (error) { toast.error(error?.response?.data?.detail || 'No se pudo identificar al participante'); } };
  const correct = async (segment) => { try { await axios.put(`${API}/api/board/meetings/${meeting.meeting_id}/transcript-segment`, { segment_id: segment.segment_id, text: editing[segment.segment_id] || segment.text, external_processing_acknowledged: aiAck }, getAuthHeaders()); toast.success('Corrección guardada como nueva versión'); await load(); } catch (error) { toast.error(error?.response?.data?.detail || 'No se pudo corregir'); } };
  const generate = async () => { try { await axios.post(`${API}/api/board/meetings/${meeting.meeting_id}/ai-draft`, { external_processing_acknowledged: aiAck }, getAuthHeaders()); toast.success('Borrador asistido generado para revisión'); await onReload(); } catch (error) { toast.error(error?.response?.data?.detail || 'No se pudo generar'); } };
  const saveManual = async () => { try { await axios.put(`${API}/api/board/meetings/${meeting.meeting_id}/manual-minute`, { content: manual }, getAuthHeaders()); toast.success('Minuta manual guardada como nueva versión'); await onReload(); } catch (error) { toast.error(error?.response?.data?.detail || 'No se pudo guardar'); } };
  const speakerLabels = [...new Set((transcript.segments || []).map((item) => item.speaker_label))];
  return <section className="space-y-6" data-testid="transcript-minutes-panel">
    <BoardRecorder meetingId={meeting.meeting_id} enabled={meeting.status === 'open' && meeting.recording_notice_confirmed} onCompleted={load} onChunkUploaded={() => loadTranscript().catch(() => {})} />
    {loadError && <div className="border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900" data-testid="board-recordings-load-error">{loadError}</div>}
    <BoardRecordingList recordings={recordings} onRefresh={load} />
    {speakerLabels.length > 0 && <div className="border bg-white p-4"><h2 className="flex items-center gap-2 font-semibold"><UserRoundCog className="h-4 w-4" />Identificación de participantes</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{speakerLabels.map((speaker) => <PersonSelect key={speaker} id={`speaker-map-${speaker.replaceAll(' ', '-').toLowerCase()}`} label={speakerLabel(speaker)} items={members} value={transcript.mappings.find((item) => item.speaker_label === speaker)?.person_id || ''} onChange={(value) => mapSpeaker(speaker, value)} />)}</div></div>}
    <div><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">Transcripción en vivo</h2>{meeting.status === 'open' && <p className="text-xs font-semibold text-teal-700" data-testid="live-transcription-status">{transcript.live?.status === 'streaming' ? 'Transcribiendo progresivamente' : transcript.live?.status === 'processing' || transcript.live?.status === 'queued' ? 'Procesando el audio más reciente…' : transcript.live?.status === 'finalizing' ? 'Consolidando la transcripción completa…' : transcript.live?.status === 'completed' ? 'Transcripción completa disponible' : transcript.live?.status === 'retry' ? 'Reintentando el bloque más reciente…' : 'Escuchando nuevos bloques…'}</p>}</div><div className="mt-3 space-y-3">{(transcript.segments || []).length ? transcript.segments.map((segment) => <article key={segment.segment_id} className="border bg-white p-4" data-testid={`transcript-segment-${segment.segment_id}`}><p className="text-xs font-semibold text-[#9E8232]">{segment.person?.name || speakerLabel(segment.speaker_label)} · {Math.floor(segment.start_seconds || 0)} s</p><Textarea value={editing[segment.segment_id] ?? segment.text} onChange={(event) => setEditing((old) => ({ ...old, [segment.segment_id]: event.target.value }))} className="mt-2" data-testid={`transcript-text-${segment.segment_id}`} /><Button size="sm" variant="outline" className="mt-2" onClick={() => correct(segment)} data-testid={`save-transcript-${segment.segment_id}`}><Save className="mr-1 h-3 w-3" />Guardar corrección</Button></article>) : <p className="border border-dashed bg-white p-6 text-center text-sm text-slate-500" data-testid="live-transcription-empty">{meeting.status === 'open' ? 'La transcripción aparecerá progresivamente después de los primeros segundos de conversación.' : 'Aún no existe una transcripción para esta reunión.'}</p>}</div></div>
    <div className="grid gap-4 lg:grid-cols-2"><div className="border bg-white p-4"><h2 className="flex items-center gap-2 font-semibold"><FileCheck2 className="h-4 w-4" />Minuta manual</h2><Textarea value={manual} onChange={(event) => setManual(event.target.value)} className="mt-3 min-h-52" data-testid="manual-minute-editor" /><Button onClick={saveManual} disabled={!manual.trim()} className="mt-3" data-testid="save-manual-minute-button">Guardar versión manual</Button></div><div className="border bg-white p-4"><h2 className="flex items-center gap-2 font-semibold"><Bot className="h-4 w-4" />Borrador asistido</h2><p className="mt-2 text-sm text-slate-500">Las fuentes se procesan mediante un servicio externo con identidades protegidas. Las notas pueden contener información sensible y el resultado nunca se publica automáticamente.</p><label className="mt-3 flex items-start gap-2 border p-3 text-xs"><Checkbox checked={aiAck} onCheckedChange={setAiAck} data-testid="ai-external-processing-acknowledgement" />Confirmo el procesamiento externo para generar este borrador revisable.</label><Button onClick={generate} disabled={!aiAck} className="mt-3 bg-[#14213D]" data-testid="generate-ai-minute-button"><Bot className="mr-2 h-4 w-4" />Confirmar y generar</Button><div className="mt-4 space-y-2">{(meeting.minutes || []).filter((item) => item.minute_type === 'ai_draft').map((item) => <div key={item.minute_id} className="border p-3 text-xs" data-testid={`ai-minute-${item.minute_id}`}>Borrador asistido v{item.version} · revisión humana pendiente</div>)}</div></div></div>
  </section>;
};