/* eslint-disable react-hooks/exhaustive-deps */
import React,{useEffect,useRef,useState}from'react';
import axios from'axios';import{Download,FileSpreadsheet,RefreshCcw,ShieldAlert,Upload}from'lucide-react';import{toast}from'sonner';
import{FinanceShell}from'../../components/finance/FinanceShell';import{Button}from'../../components/ui/button';import{useAuth}from'../../context/AuthContext';

export default function FinanceIntegrationsPage(){
 const{API,getAuthHeaders}=useAuth();const[status,setStatus]=useState(null);const[file,setFile]=useState(null);const inputRef=useRef(null);useEffect(()=>{axios.get(`${API}/api/finance/integrations/pushpay`,getAuthHeaders()).then(r=>setStatus(r.data))},[]);
 const upload=async()=>{if(!file)return;const body=new FormData();body.append('file',file);try{const r=await axios.post(`${API}/api/finance/contributions/import-csv`,body,{headers:{...getAuthHeaders().headers,'Content-Type':'multipart/form-data'}});toast.success(`${r.data.imported} contribuciones importadas`)}catch(error){toast.error(error?.response?.data?.detail||'No se pudo importar')}};
 const template=()=>{const content='external_transaction_id,received_date,amount_cents,contribution_type,fund_code,person_id,anonymous,payment_method\n';const url=URL.createObjectURL(new Blob([content],{type:'text/csv'}));const link=document.createElement('a');link.href=url;link.download='plantilla_contribuciones_ven_y_ve.csv';link.click();URL.revokeObjectURL(url)};
 return <FinanceShell title="Integraciones e importación" description="Pushpay y CSV convergen en el mismo núcleo contable idempotente."><section className="grid gap-6 lg:grid-cols-2"><div className="border bg-white p-6" data-testid="pushpay-integration-card"><RefreshCcw className="h-6 w-6 text-[#9B7A29]"/><h2 className="mt-4 font-['Spectral'] text-2xl font-semibold">Pushpay</h2><p className="mt-2 text-sm text-slate-600">Adaptador desacoplado: pago → contribución → asignación → fondo → asiento → depósito → conciliación.</p>{status&&!status.configured&&<div className="mt-5 border border-amber-300 bg-amber-50 p-4 text-sm text-amber-900"><ShieldAlert className="mb-2 h-5 w-5"/><b>BLOQUEADO — credenciales sandbox pendientes</b><p className="mt-1">El núcleo financiero continúa operativo. La sincronización no está simulada.</p></div>}<Button className="mt-5" disabled={!status?.configured} data-testid="pushpay-sync-button">Sincronizar ahora</Button></div><div className="border bg-white p-6"><FileSpreadsheet className="h-6 w-6 text-[#2B7A6D]"/><h2 className="mt-4 font-['Spectral'] text-2xl font-semibold">CSV / histórico</h2><p className="mt-2 text-sm text-slate-600">La plantilla acepta identificador externo, fecha, monto en centavos, tipo, fondo, Perfil 360, indicador anónimo y método de pago.</p><input ref={inputRef} className="sr-only" type="file" accept=".csv" onChange={e=>setFile(e.target.files?.[0])} data-testid="finance-csv-input"/><div className="mt-5 flex flex-wrap gap-2"><Button type="button" variant="outline" onClick={()=>inputRef.current?.click()} data-testid="select-finance-csv-button"><Upload className="mr-2 h-4 w-4"/>Seleccionar archivo</Button><Button type="button" variant="outline" onClick={template} data-testid="download-finance-csv-template"><Download className="mr-2 h-4 w-4"/>Descargar plantilla</Button></div><p className="mt-2 text-xs text-slate-500" data-testid="selected-finance-csv-name">{file?.name||'Ningún archivo seleccionado'}</p><Button className="mt-3" onClick={upload} disabled={!file} data-testid="finance-csv-upload-button">Importar contribuciones</Button></div></section></FinanceShell>
}