import React, { useEffect, useMemo, useState } from 'react';
import axios from 'axios';
import { Check, Loader2, RotateCw, Search, UsersRound } from 'lucide-react';
import { toast } from 'sonner';

import { useAuth } from '../../context/AuthContext';
import { apiErrorMessage } from '../../lib/apiErrors';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { Label } from '../ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select';
import { Textarea } from '../ui/textarea';
import { RotationPolicyDialog } from './RotationPolicyDialog';

export const ConsolidationAssignmentDesk = ({ routing, groups, onAssigned, canConfigure = false }) => {
  const { API, getAuthHeaders } = useAuth(); const [search, setSearch] = useState(''); const [candidates, setCandidates] = useState([]); const [selected, setSelected] = useState([]); const [searching, setSearching] = useState(false); const [saving, setSaving] = useState(false); const [cells, setCells] = useState([]);
  const turnGroupId = routing?.week?.selected_group_id || ''; const [groupId, setGroupId] = useState(turnGroupId); const [entryMode, setEntryMode] = useState('direct_church'); const [cellId, setCellId] = useState(''); const [reason, setReason] = useState('Confirmación semanal de Consolidación');
  useEffect(() => { setGroupId(turnGroupId); }, [turnGroupId]);
  useEffect(() => { axios.get(`${API}/api/cellular/cells`, getAuthHeaders()).then((response) => setCells(response.data.items || [])).catch(() => setCells([])); }, [API, getAuthHeaders]);
  useEffect(() => { if (search.trim().length < 2) { setCandidates([]); return undefined; } const timer = setTimeout(async () => { setSearching(true); try { const response = await axios.get(`${API}/api/processes/consolidation/intake-candidates`, { ...getAuthHeaders(), params: { search: search.trim(), limit: 40 } }); setCandidates(response.data.items || []); } catch (error) { toast.error(apiErrorMessage(error, 'No se pudieron buscar Personas')); } finally { setSearching(false); } }, 250); return () => clearTimeout(timer); }, [API, getAuthHeaders, search]);
  const chosen = useMemo(() => candidates.filter((person) => selected.includes(person.person_id)), [candidates, selected]); const isOverride = Boolean(turnGroupId && groupId && turnGroupId !== groupId);
  const toggle = (personId) => setSelected((current) => current.includes(personId) ? current.filter((item) => item !== personId) : [...current, personId]);
  const assign = async () => { setSaving(true); try { const response = await axios.post(`${API}/api/processes/consolidation/batch-assign`, { items: chosen.map((person) => ({ person_id: person.person_id, entry_mode: entryMode, source_cell_id: entryMode === 'cell' ? cellId : null })), front_group_id: groupId, routing_policy_id: routing?.policy?.policy_id || null, reason }, getAuthHeaders()); toast.success(`${response.data.assigned} Persona(s) asignadas`); setSelected([]); setSearch(''); setCandidates([]); await onAssigned(); } catch (error) { toast.error(apiErrorMessage(error, 'No se pudo confirmar la asignación')); } finally { setSaving(false); } };
  return <section className="border border-slate-200 bg-white" data-testid="consolidation-assignment-desk"><header className="grid gap-4 border-b border-slate-200 p-5 lg:grid-cols-[1fr_auto]"><div><p className="font-mono text-[10px] uppercase text-amber-700">Autoridad de asignación</p><h2 className="font-['Spectral'] text-2xl font-semibold">Mesa semanal de Consolidación</h2></div><div className="flex flex-wrap items-center justify-end gap-2"><div className="border border-amber-200 bg-amber-50 px-4 py-3 text-sm" data-testid="consolidation-current-rotation"><RotateCw className="mr-2 inline h-4 w-4 text-amber-700" /><span>Grupo de turno</span><b className="ml-2">{groups.find((item) => item.front_group_id === turnGroupId)?.name || 'Sin rotación configurada'}</b></div>{canConfigure && <RotationPolicyDialog groups={groups} routing={routing} onSaved={onAssigned} />}</div></header>
    <div className="grid gap-6 p-5 xl:grid-cols-[1fr_360px]"><div><Label htmlFor="consolidation-batch-search">Personas nuevas o por continuar</Label><div className="relative mt-2"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><Input id="consolidation-batch-search" value={search} onChange={(event) => setSearch(event.target.value)} className="pl-9" placeholder="Nombre, teléfono o número VV" data-testid="consolidation-batch-search-input" />{searching && <Loader2 className="absolute right-3 top-2.5 h-4 w-4 animate-spin" />}</div><div className="mt-3 max-h-80 divide-y divide-slate-200 overflow-y-auto border border-slate-200" data-testid="consolidation-batch-candidates">{candidates.map((person) => <button type="button" key={person.person_id} onClick={() => toggle(person.person_id)} className={`flex w-full items-center justify-between gap-3 p-3 text-left ${selected.includes(person.person_id) ? 'bg-amber-50' : 'bg-white hover:bg-slate-50'}`} data-testid={`consolidation-batch-candidate-${person.person_id}`}><span><b className="block text-sm">{person.name}</b><small className="text-slate-500">{person.person_number}{person.continuation_status ? ` · Continúa: ${person.continuation_status}` : ''}</small></span><span className={`grid h-6 w-6 place-items-center border ${selected.includes(person.person_id) ? 'border-amber-600 bg-amber-600 text-white' : 'border-slate-300'}`}>{selected.includes(person.person_id) && <Check className="h-4 w-4" />}</span></button>)}{search.length >= 2 && !searching && !candidates.length && <p className="p-6 text-center text-sm text-slate-500">No hay Personas elegibles.</p>}</div></div>
      <div className="space-y-4"><div className="border border-slate-200 bg-slate-50 p-3 text-sm" data-testid="consolidation-batch-selection"><UsersRound className="mr-2 inline h-4 w-4" /><b>{selected.length}</b> seleccionada(s)</div><div><Label>Grupo Frontal responsable</Label><Select value={groupId} onValueChange={setGroupId}><SelectTrigger data-testid="consolidation-batch-group-select"><SelectValue placeholder="Seleccionar Grupo" /></SelectTrigger><SelectContent className="bg-white">{groups.map((group) => <SelectItem key={group.front_group_id} value={group.front_group_id}>{group.name}{group.front_group_id === turnGroupId ? ' · Turno' : ''}</SelectItem>)}</SelectContent></Select></div><div><Label>Puerta de entrada</Label><Select value={entryMode} onValueChange={setEntryMode}><SelectTrigger data-testid="consolidation-batch-entry-select"><SelectValue /></SelectTrigger><SelectContent className="bg-white"><SelectItem value="direct_church">Iglesia</SelectItem><SelectItem value="cell">Célula</SelectItem><SelectItem value="complete_cycle">Ciclo completo</SelectItem><SelectItem value="visitor_followup">Seguimiento</SelectItem></SelectContent></Select></div>{entryMode === 'cell' && <div><Label>Célula de origen</Label><Select value={cellId} onValueChange={setCellId}><SelectTrigger data-testid="consolidation-batch-cell-select"><SelectValue placeholder="Seleccionar Célula" /></SelectTrigger><SelectContent className="bg-white">{cells.map((cell) => <SelectItem key={cell.cell_id} value={cell.cell_id}>{cell.name || cell.cell_name || cell.cell_id}</SelectItem>)}</SelectContent></Select></div>}<div><Label htmlFor="consolidation-batch-reason">{isOverride ? 'Motivo de modificación *' : 'Motivo de confirmación'}</Label><Textarea id="consolidation-batch-reason" value={reason} onChange={(event) => setReason(event.target.value)} data-testid="front-group-audit-reason-input" /></div><Button onClick={assign} disabled={saving || !selected.length || !groupId || reason.trim().length < 3 || (entryMode === 'cell' && !cellId)} className="w-full bg-slate-900" data-testid="front-group-confirm-rotation-button">{saving && <Loader2 className="h-4 w-4 animate-spin" />}{isOverride ? 'Confirmar modificación' : 'Confirmar asignación'}</Button></div></div>
  </section>;
};