import React, { useEffect, useMemo, useState } from 'react';
import axios from 'axios';
import { Check, Loader2, Settings2 } from 'lucide-react';
import { toast } from 'sonner';

import { useAuth } from '../../context/AuthContext';
import { apiErrorMessage } from '../../lib/apiErrors';
import { Button } from '../ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '../ui/dialog';
import { Label } from '../ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../ui/select';

export const RotationPolicyDialog = ({ groups, routing, onSaved }) => {
  const { API, getAuthHeaders } = useAuth(); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false);
  const roots = groups.filter((item) => !item.parent_group_id); const [rootId, setRootId] = useState(routing?.policy?.root_group_id || roots[0]?.front_group_id || ''); const [ordered, setOrdered] = useState(routing?.policy?.ordered_group_ids || []); const [weekStart, setWeekStart] = useState(String(routing?.policy?.week_start_day ?? 6));
  useEffect(() => { if (routing?.policy) { setRootId(routing.policy.root_group_id); setOrdered(routing.policy.ordered_group_ids || []); setWeekStart(String(routing.policy.week_start_day ?? 6)); } }, [routing]);
  const eligible = useMemo(() => groups.filter((item) => item.front_group_id === rootId || item.root_group_id === rootId), [groups, rootId]);
  const toggle = (id) => setOrdered((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const save = async () => { setSaving(true); try { const policyId = routing?.policy?.policy_id || `rotation-${rootId}`; await axios.put(`${API}/api/front-group-routing/policies/${policyId}`, { root_group_id: rootId, ordered_group_ids: ordered, timezone_name: 'America/Santo_Domingo', week_start_day: Number(weekStart), active: true }, getAuthHeaders()); toast.success('Rotación semanal guardada'); setOpen(false); await onSaved(); } catch (error) { toast.error(apiErrorMessage(error, 'No se pudo guardar la rotación')); } finally { setSaving(false); } };
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="outline" data-testid="consolidation-rotation-settings-button"><Settings2 className="h-4 w-4" />Configurar rotación</Button></DialogTrigger><DialogContent className="max-h-[90vh] max-w-xl overflow-y-auto bg-white" data-testid="consolidation-rotation-dialog"><DialogHeader><DialogTitle>Rotación semanal</DialogTitle><DialogDescription>Seleccione el árbol y las ramas participantes en el orden operativo.</DialogDescription></DialogHeader><div className="space-y-4"><div><Label>Árbol raíz</Label><Select value={rootId} onValueChange={(value) => { setRootId(value); setOrdered([]); }}><SelectTrigger data-testid="consolidation-rotation-root-select"><SelectValue placeholder="Seleccionar raíz" /></SelectTrigger><SelectContent className="bg-white">{roots.map((root) => <SelectItem key={root.front_group_id} value={root.front_group_id}>{root.name}</SelectItem>)}</SelectContent></Select></div><div><Label>Ramas elegibles</Label><div className="mt-2 max-h-64 divide-y divide-slate-200 overflow-y-auto border border-slate-200">{eligible.map((group) => <button type="button" key={group.front_group_id} onClick={() => toggle(group.front_group_id)} className={`flex w-full items-center justify-between p-3 text-left ${ordered.includes(group.front_group_id) ? 'bg-amber-50' : 'hover:bg-slate-50'}`} data-testid={`consolidation-rotation-group-${group.front_group_id}`}><span><b className="block text-sm">{group.name}</b><small className="text-slate-500">Profundidad {group.depth || 0}{ordered.includes(group.front_group_id) ? ` · Orden ${ordered.indexOf(group.front_group_id) + 1}` : ''}</small></span>{ordered.includes(group.front_group_id) && <Check className="h-4 w-4 text-amber-700" />}</button>)}</div></div><div><Label>Inicio de semana</Label><Select value={weekStart} onValueChange={setWeekStart}><SelectTrigger data-testid="consolidation-rotation-week-start-select"><SelectValue /></SelectTrigger><SelectContent className="bg-white"><SelectItem value="6">Domingo</SelectItem><SelectItem value="0">Lunes</SelectItem><SelectItem value="5">Sábado</SelectItem></SelectContent></Select></div><Button onClick={save} disabled={saving || !rootId || !ordered.length} className="w-full bg-slate-900" data-testid="consolidation-rotation-save-button">{saving && <Loader2 className="h-4 w-4 animate-spin" />}Guardar rotación</Button></div></DialogContent></Dialog>;
};